//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.5.1 C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g 2025-04-21 15:00:12

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591
// CLS compliance checking will not be performed on 'type' because it is not visible from outside this assembly.
#pragma warning disable 3019


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.5.1")]
[System.CLSCompliant(false)]
public partial class Gram_SICXELexer : Antlr.Runtime.Lexer
{
	public const int EOF=-1;
	public const int T__41=41;
	public const int AT=4;
	public const int BASE=5;
	public const int BYTE=6;
	public const int CHCONST=7;
	public const int CONSTCAD=8;
	public const int CONSTHEX=9;
	public const int DIR=10;
	public const int DIV=11;
	public const int END=12;
	public const int EQU=13;
	public const int F1CODOP=14;
	public const int F1_INSTR=15;
	public const int F2CODOP=16;
	public const int F2_INSTR=17;
	public const int F34CODOP=18;
	public const int F34_INSTR=19;
	public const int FINL=20;
	public const int HEXCONST=21;
	public const int HEXSUF=22;
	public const int ID=23;
	public const int INDICE=24;
	public const int INSTR=25;
	public const int LPAREN=26;
	public const int MINUS=27;
	public const int NUM=28;
	public const int NUMERAL=29;
	public const int ORG=30;
	public const int PLUS=31;
	public const int REG=32;
	public const int RESB=33;
	public const int RESW=34;
	public const int RPAREN=35;
	public const int STAR=36;
	public const int START=37;
	public const int USE=38;
	public const int WORD=39;
	public const int WS=40;

	// delegates
	// delegators

	public Gram_SICXELexer()
	{
		OnCreated();
	}

	public Gram_SICXELexer(ICharStream input )
		: this(input, new RecognizerSharedState())
	{
	}

	public Gram_SICXELexer(ICharStream input, RecognizerSharedState state)
		: base(input, state)
	{

		OnCreated();
	}
	public override string GrammarFileName { get { return "C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g"; } }


	partial void OnCreated();
	partial void EnterRule(string ruleName, int ruleIndex);
	partial void LeaveRule(string ruleName, int ruleIndex);

	partial void EnterRule_T__41();
	partial void LeaveRule_T__41();

	// $ANTLR start "T__41"
	[GrammarRule("T__41")]
	private void mT__41()
	{
		EnterRule_T__41();
		EnterRule("T__41", 1);
		TraceIn("T__41", 1);
		try
		{
			int _type = T__41;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:7:7: ( ',' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:7:9: ','
			{
			DebugLocation(7, 9);
			Match(','); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__41", 1);
			LeaveRule("T__41", 1);
			LeaveRule_T__41();
		}
	}
	// $ANTLR end "T__41"

	partial void EnterRule_START();
	partial void LeaveRule_START();

	// $ANTLR start "START"
	[GrammarRule("START")]
	private void mSTART()
	{
		EnterRule_START();
		EnterRule("START", 2);
		TraceIn("START", 2);
		try
		{
			int _type = START;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:19:7: ( 'START' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:19:9: 'START'
			{
			DebugLocation(19, 9);
			Match("START"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("START", 2);
			LeaveRule("START", 2);
			LeaveRule_START();
		}
	}
	// $ANTLR end "START"

	partial void EnterRule_END();
	partial void LeaveRule_END();

	// $ANTLR start "END"
	[GrammarRule("END")]
	private void mEND()
	{
		EnterRule_END();
		EnterRule("END", 3);
		TraceIn("END", 3);
		try
		{
			int _type = END;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:20:7: ( 'END' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:20:9: 'END'
			{
			DebugLocation(20, 9);
			Match("END"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("END", 3);
			LeaveRule("END", 3);
			LeaveRule_END();
		}
	}
	// $ANTLR end "END"

	partial void EnterRule_BYTE();
	partial void LeaveRule_BYTE();

	// $ANTLR start "BYTE"
	[GrammarRule("BYTE")]
	private void mBYTE()
	{
		EnterRule_BYTE();
		EnterRule("BYTE", 4);
		TraceIn("BYTE", 4);
		try
		{
			int _type = BYTE;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:21:7: ( 'BYTE' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:21:9: 'BYTE'
			{
			DebugLocation(21, 9);
			Match("BYTE"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("BYTE", 4);
			LeaveRule("BYTE", 4);
			LeaveRule_BYTE();
		}
	}
	// $ANTLR end "BYTE"

	partial void EnterRule_WORD();
	partial void LeaveRule_WORD();

	// $ANTLR start "WORD"
	[GrammarRule("WORD")]
	private void mWORD()
	{
		EnterRule_WORD();
		EnterRule("WORD", 5);
		TraceIn("WORD", 5);
		try
		{
			int _type = WORD;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:22:7: ( 'WORD' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:22:9: 'WORD'
			{
			DebugLocation(22, 9);
			Match("WORD"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("WORD", 5);
			LeaveRule("WORD", 5);
			LeaveRule_WORD();
		}
	}
	// $ANTLR end "WORD"

	partial void EnterRule_RESB();
	partial void LeaveRule_RESB();

	// $ANTLR start "RESB"
	[GrammarRule("RESB")]
	private void mRESB()
	{
		EnterRule_RESB();
		EnterRule("RESB", 6);
		TraceIn("RESB", 6);
		try
		{
			int _type = RESB;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:23:7: ( 'RESB' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:23:9: 'RESB'
			{
			DebugLocation(23, 9);
			Match("RESB"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("RESB", 6);
			LeaveRule("RESB", 6);
			LeaveRule_RESB();
		}
	}
	// $ANTLR end "RESB"

	partial void EnterRule_RESW();
	partial void LeaveRule_RESW();

	// $ANTLR start "RESW"
	[GrammarRule("RESW")]
	private void mRESW()
	{
		EnterRule_RESW();
		EnterRule("RESW", 7);
		TraceIn("RESW", 7);
		try
		{
			int _type = RESW;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:24:7: ( 'RESW' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:24:9: 'RESW'
			{
			DebugLocation(24, 9);
			Match("RESW"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("RESW", 7);
			LeaveRule("RESW", 7);
			LeaveRule_RESW();
		}
	}
	// $ANTLR end "RESW"

	partial void EnterRule_BASE();
	partial void LeaveRule_BASE();

	// $ANTLR start "BASE"
	[GrammarRule("BASE")]
	private void mBASE()
	{
		EnterRule_BASE();
		EnterRule("BASE", 8);
		TraceIn("BASE", 8);
		try
		{
			int _type = BASE;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:25:7: ( 'BASE' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:25:9: 'BASE'
			{
			DebugLocation(25, 9);
			Match("BASE"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("BASE", 8);
			LeaveRule("BASE", 8);
			LeaveRule_BASE();
		}
	}
	// $ANTLR end "BASE"

	partial void EnterRule_EQU();
	partial void LeaveRule_EQU();

	// $ANTLR start "EQU"
	[GrammarRule("EQU")]
	private void mEQU()
	{
		EnterRule_EQU();
		EnterRule("EQU", 9);
		TraceIn("EQU", 9);
		try
		{
			int _type = EQU;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:26:7: ( 'EQU' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:26:9: 'EQU'
			{
			DebugLocation(26, 9);
			Match("EQU"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("EQU", 9);
			LeaveRule("EQU", 9);
			LeaveRule_EQU();
		}
	}
	// $ANTLR end "EQU"

	partial void EnterRule_ORG();
	partial void LeaveRule_ORG();

	// $ANTLR start "ORG"
	[GrammarRule("ORG")]
	private void mORG()
	{
		EnterRule_ORG();
		EnterRule("ORG", 10);
		TraceIn("ORG", 10);
		try
		{
			int _type = ORG;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:27:7: ( 'ORG' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:27:9: 'ORG'
			{
			DebugLocation(27, 9);
			Match("ORG"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ORG", 10);
			LeaveRule("ORG", 10);
			LeaveRule_ORG();
		}
	}
	// $ANTLR end "ORG"

	partial void EnterRule_USE();
	partial void LeaveRule_USE();

	// $ANTLR start "USE"
	[GrammarRule("USE")]
	private void mUSE()
	{
		EnterRule_USE();
		EnterRule("USE", 11);
		TraceIn("USE", 11);
		try
		{
			int _type = USE;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:28:7: ( 'USE' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:28:9: 'USE'
			{
			DebugLocation(28, 9);
			Match("USE"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("USE", 11);
			LeaveRule("USE", 11);
			LeaveRule_USE();
		}
	}
	// $ANTLR end "USE"

	partial void EnterRule_FINL();
	partial void LeaveRule_FINL();

	// $ANTLR start "FINL"
	[GrammarRule("FINL")]
	private void mFINL()
	{
		EnterRule_FINL();
		EnterRule("FINL", 12);
		TraceIn("FINL", 12);
		try
		{
			int _type = FINL;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:32:5: ( ( ';' )* ( ( '\\r' )? '\\n' | '\\r' ) )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:32:7: ( ';' )* ( ( '\\r' )? '\\n' | '\\r' )
			{
			DebugLocation(32, 7);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:32:7: ( ';' )*
			try { DebugEnterSubRule(1);
			while (true)
			{
				int alt1=2;
				try { DebugEnterDecision(1, false);
				int LA1_1 = input.LA(1);

				if ((LA1_1==';'))
				{
					alt1 = 1;
				}


				} finally { DebugExitDecision(1); }
				switch ( alt1 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:32:9: ';'
					{
					DebugLocation(32, 9);
					Match(';'); 

					}
					break;

				default:
					goto loop1;
				}
			}

			loop1:
				;

			} finally { DebugExitSubRule(1); }

			DebugLocation(32, 16);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:32:16: ( ( '\\r' )? '\\n' | '\\r' )
			int alt3=2;
			try { DebugEnterSubRule(3);
			try { DebugEnterDecision(3, false);
			int LA3_1 = input.LA(1);

			if ((LA3_1=='\r'))
			{
				int LA3_2 = input.LA(2);

				if ((LA3_2=='\n'))
				{
					alt3 = 1;
				}
				else
				{
					alt3 = 2;
				}
			}
			else if ((LA3_1=='\n'))
			{
				alt3 = 1;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 3, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(3); }
			switch (alt3)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:32:18: ( '\\r' )? '\\n'
				{
				DebugLocation(32, 18);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:32:18: ( '\\r' )?
				int alt2=2;
				try { DebugEnterSubRule(2);
				try { DebugEnterDecision(2, false);
				int LA2_1 = input.LA(1);

				if ((LA2_1=='\r'))
				{
					alt2 = 1;
				}
				} finally { DebugExitDecision(2); }
				switch (alt2)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:32:18: '\\r'
					{
					DebugLocation(32, 18);
					Match('\r'); 

					}
					break;

				}
				} finally { DebugExitSubRule(2); }

				DebugLocation(32, 24);
				Match('\n'); 

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:32:31: '\\r'
				{
				DebugLocation(32, 31);
				Match('\r'); 

				}
				break;

			}
			} finally { DebugExitSubRule(3); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("FINL", 12);
			LeaveRule("FINL", 12);
			LeaveRule_FINL();
		}
	}
	// $ANTLR end "FINL"

	partial void EnterRule_REG();
	partial void LeaveRule_REG();

	// $ANTLR start "REG"
	[GrammarRule("REG")]
	private void mREG()
	{
		EnterRule_REG();
		EnterRule("REG", 13);
		TraceIn("REG", 13);
		try
		{
			int _type = REG;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:40:5: ( 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'X' | 'L' | 'S' | 'T' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:
			{
			DebugLocation(40, 5);
			if ((input.LA(1)>='A' && input.LA(1)<='F')||input.LA(1)=='L'||(input.LA(1)>='S' && input.LA(1)<='T')||input.LA(1)=='X')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("REG", 13);
			LeaveRule("REG", 13);
			LeaveRule_REG();
		}
	}
	// $ANTLR end "REG"

	partial void EnterRule_INDICE();
	partial void LeaveRule_INDICE();

	// $ANTLR start "INDICE"
	[GrammarRule("INDICE")]
	private void mINDICE()
	{
		EnterRule_INDICE();
		EnterRule("INDICE", 14);
		TraceIn("INDICE", 14);
		try
		{
			int _type = INDICE;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:54:5: ( 'IX' | 'IY' | 'IZ' )
			int alt4=3;
			try { DebugEnterDecision(4, false);
			int LA4_1 = input.LA(1);

			if ((LA4_1=='I'))
			{
				switch (input.LA(2))
				{
				case 'X':
					{
					alt4 = 1;
					}
					break;
				case 'Y':
					{
					alt4 = 2;
					}
					break;
				case 'Z':
					{
					alt4 = 3;
					}
					break;
				default:
					{
						NoViableAltException nvae = new NoViableAltException("", 4, 1, input, 2);
						DebugRecognitionException(nvae);
						throw nvae;
					}
				}

			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 4, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(4); }
			switch (alt4)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:54:7: 'IX'
				{
				DebugLocation(54, 7);
				Match("IX"); 


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:54:14: 'IY'
				{
				DebugLocation(54, 14);
				Match("IY"); 


				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:54:21: 'IZ'
				{
				DebugLocation(54, 21);
				Match("IZ"); 


				}
				break;

			}
			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("INDICE", 14);
			LeaveRule("INDICE", 14);
			LeaveRule_INDICE();
		}
	}
	// $ANTLR end "INDICE"

	partial void EnterRule_PLUS();
	partial void LeaveRule_PLUS();

	// $ANTLR start "PLUS"
	[GrammarRule("PLUS")]
	private void mPLUS()
	{
		EnterRule_PLUS();
		EnterRule("PLUS", 15);
		TraceIn("PLUS", 15);
		try
		{
			int _type = PLUS;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:60:8: ( '+' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:60:10: '+'
			{
			DebugLocation(60, 10);
			Match('+'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("PLUS", 15);
			LeaveRule("PLUS", 15);
			LeaveRule_PLUS();
		}
	}
	// $ANTLR end "PLUS"

	partial void EnterRule_MINUS();
	partial void LeaveRule_MINUS();

	// $ANTLR start "MINUS"
	[GrammarRule("MINUS")]
	private void mMINUS()
	{
		EnterRule_MINUS();
		EnterRule("MINUS", 16);
		TraceIn("MINUS", 16);
		try
		{
			int _type = MINUS;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:61:8: ( '-' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:61:10: '-'
			{
			DebugLocation(61, 10);
			Match('-'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("MINUS", 16);
			LeaveRule("MINUS", 16);
			LeaveRule_MINUS();
		}
	}
	// $ANTLR end "MINUS"

	partial void EnterRule_STAR();
	partial void LeaveRule_STAR();

	// $ANTLR start "STAR"
	[GrammarRule("STAR")]
	private void mSTAR()
	{
		EnterRule_STAR();
		EnterRule("STAR", 17);
		TraceIn("STAR", 17);
		try
		{
			int _type = STAR;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:62:8: ( '*' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:62:10: '*'
			{
			DebugLocation(62, 10);
			Match('*'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("STAR", 17);
			LeaveRule("STAR", 17);
			LeaveRule_STAR();
		}
	}
	// $ANTLR end "STAR"

	partial void EnterRule_DIV();
	partial void LeaveRule_DIV();

	// $ANTLR start "DIV"
	[GrammarRule("DIV")]
	private void mDIV()
	{
		EnterRule_DIV();
		EnterRule("DIV", 18);
		TraceIn("DIV", 18);
		try
		{
			int _type = DIV;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:63:8: ( '/' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:63:10: '/'
			{
			DebugLocation(63, 10);
			Match('/'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("DIV", 18);
			LeaveRule("DIV", 18);
			LeaveRule_DIV();
		}
	}
	// $ANTLR end "DIV"

	partial void EnterRule_LPAREN();
	partial void LeaveRule_LPAREN();

	// $ANTLR start "LPAREN"
	[GrammarRule("LPAREN")]
	private void mLPAREN()
	{
		EnterRule_LPAREN();
		EnterRule("LPAREN", 19);
		TraceIn("LPAREN", 19);
		try
		{
			int _type = LPAREN;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:64:8: ( '(' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:64:10: '('
			{
			DebugLocation(64, 10);
			Match('('); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("LPAREN", 19);
			LeaveRule("LPAREN", 19);
			LeaveRule_LPAREN();
		}
	}
	// $ANTLR end "LPAREN"

	partial void EnterRule_RPAREN();
	partial void LeaveRule_RPAREN();

	// $ANTLR start "RPAREN"
	[GrammarRule("RPAREN")]
	private void mRPAREN()
	{
		EnterRule_RPAREN();
		EnterRule("RPAREN", 20);
		TraceIn("RPAREN", 20);
		try
		{
			int _type = RPAREN;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:65:8: ( ')' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:65:10: ')'
			{
			DebugLocation(65, 10);
			Match(')'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("RPAREN", 20);
			LeaveRule("RPAREN", 20);
			LeaveRule_RPAREN();
		}
	}
	// $ANTLR end "RPAREN"

	partial void EnterRule_AT();
	partial void LeaveRule_AT();

	// $ANTLR start "AT"
	[GrammarRule("AT")]
	private void mAT()
	{
		EnterRule_AT();
		EnterRule("AT", 21);
		TraceIn("AT", 21);
		try
		{
			int _type = AT;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:68:5: ( '@' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:68:7: '@'
			{
			DebugLocation(68, 7);
			Match('@'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("AT", 21);
			LeaveRule("AT", 21);
			LeaveRule_AT();
		}
	}
	// $ANTLR end "AT"

	partial void EnterRule_NUMERAL();
	partial void LeaveRule_NUMERAL();

	// $ANTLR start "NUMERAL"
	[GrammarRule("NUMERAL")]
	private void mNUMERAL()
	{
		EnterRule_NUMERAL();
		EnterRule("NUMERAL", 22);
		TraceIn("NUMERAL", 22);
		try
		{
			int _type = NUMERAL;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:72:5: ( '#' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:72:7: '#'
			{
			DebugLocation(72, 7);
			Match('#'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("NUMERAL", 22);
			LeaveRule("NUMERAL", 22);
			LeaveRule_NUMERAL();
		}
	}
	// $ANTLR end "NUMERAL"

	partial void EnterRule_F1_INSTR();
	partial void LeaveRule_F1_INSTR();

	// $ANTLR start "F1_INSTR"
	[GrammarRule("F1_INSTR")]
	private void mF1_INSTR()
	{
		EnterRule_F1_INSTR();
		EnterRule("F1_INSTR", 23);
		TraceIn("F1_INSTR", 23);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:79:5: ( 'FIX' | 'NORM' | 'FLOAT' | 'HIO' | 'SIO' | 'TIO' )
			int alt5=6;
			try { DebugEnterDecision(5, false);
			switch (input.LA(1))
			{
			case 'F':
				{
				int LA5_2 = input.LA(2);

				if ((LA5_2=='I'))
				{
					alt5 = 1;
				}
				else if ((LA5_2=='L'))
				{
					alt5 = 3;
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 5, 1, input, 2);
					DebugRecognitionException(nvae);
					throw nvae;
				}
				}
				break;
			case 'N':
				{
				alt5 = 2;
				}
				break;
			case 'H':
				{
				alt5 = 4;
				}
				break;
			case 'S':
				{
				alt5 = 5;
				}
				break;
			case 'T':
				{
				alt5 = 6;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 5, 0, input, 1);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(5); }
			switch (alt5)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:79:7: 'FIX'
				{
				DebugLocation(79, 7);
				Match("FIX"); 


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:80:7: 'NORM'
				{
				DebugLocation(80, 7);
				Match("NORM"); 


				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:81:7: 'FLOAT'
				{
				DebugLocation(81, 7);
				Match("FLOAT"); 


				}
				break;
			case 4:
				DebugEnterAlt(4);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:82:7: 'HIO'
				{
				DebugLocation(82, 7);
				Match("HIO"); 


				}
				break;
			case 5:
				DebugEnterAlt(5);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:83:7: 'SIO'
				{
				DebugLocation(83, 7);
				Match("SIO"); 


				}
				break;
			case 6:
				DebugEnterAlt(6);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:84:7: 'TIO'
				{
				DebugLocation(84, 7);
				Match("TIO"); 


				}
				break;

			}
		}
		finally
		{
			TraceOut("F1_INSTR", 23);
			LeaveRule("F1_INSTR", 23);
			LeaveRule_F1_INSTR();
		}
	}
	// $ANTLR end "F1_INSTR"

	partial void EnterRule_F2_INSTR();
	partial void LeaveRule_F2_INSTR();

	// $ANTLR start "F2_INSTR"
	[GrammarRule("F2_INSTR")]
	private void mF2_INSTR()
	{
		EnterRule_F2_INSTR();
		EnterRule("F2_INSTR", 24);
		TraceIn("F2_INSTR", 24);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:88:5: ( 'ADDR' | 'SUBR' | 'COMPR' | 'MULR' | 'DIVR' | 'RMO' | 'SHIFTL' | 'SHIFTR' | 'SVC' | 'CLEAR' | 'TIXR' )
			int alt6=11;
			try { DebugEnterDecision(6, false);
			switch (input.LA(1))
			{
			case 'A':
				{
				alt6 = 1;
				}
				break;
			case 'S':
				{
				switch (input.LA(2))
				{
				case 'U':
					{
					alt6 = 2;
					}
					break;
				case 'H':
					{
					int LA6_3 = input.LA(3);

					if ((LA6_3=='I'))
					{
						int LA6_4 = input.LA(4);

						if ((LA6_4=='F'))
						{
							int LA6_5 = input.LA(5);

							if ((LA6_5=='T'))
							{
								int LA6_6 = input.LA(6);

								if ((LA6_6=='L'))
								{
									alt6 = 7;
								}
								else if ((LA6_6=='R'))
								{
									alt6 = 8;
								}
								else
								{
									NoViableAltException nvae = new NoViableAltException("", 6, 15, input, 6);
									DebugRecognitionException(nvae);
									throw nvae;
								}
							}
							else
							{
								NoViableAltException nvae = new NoViableAltException("", 6, 14, input, 5);
								DebugRecognitionException(nvae);
								throw nvae;
							}
						}
						else
						{
							NoViableAltException nvae = new NoViableAltException("", 6, 13, input, 4);
							DebugRecognitionException(nvae);
							throw nvae;
						}
					}
					else
					{
						NoViableAltException nvae = new NoViableAltException("", 6, 9, input, 3);
						DebugRecognitionException(nvae);
						throw nvae;
					}
					}
					break;
				case 'V':
					{
					alt6 = 9;
					}
					break;
				default:
					{
						NoViableAltException nvae = new NoViableAltException("", 6, 2, input, 2);
						DebugRecognitionException(nvae);
						throw nvae;
					}
				}

				}
				break;
			case 'C':
				{
				int LA6_2 = input.LA(2);

				if ((LA6_2=='O'))
				{
					alt6 = 3;
				}
				else if ((LA6_2=='L'))
				{
					alt6 = 10;
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 6, 3, input, 2);
					DebugRecognitionException(nvae);
					throw nvae;
				}
				}
				break;
			case 'M':
				{
				alt6 = 4;
				}
				break;
			case 'D':
				{
				alt6 = 5;
				}
				break;
			case 'R':
				{
				alt6 = 6;
				}
				break;
			case 'T':
				{
				alt6 = 11;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 6, 0, input, 1);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(6); }
			switch (alt6)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:88:7: 'ADDR'
				{
				DebugLocation(88, 7);
				Match("ADDR"); 


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:89:7: 'SUBR'
				{
				DebugLocation(89, 7);
				Match("SUBR"); 


				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:90:7: 'COMPR'
				{
				DebugLocation(90, 7);
				Match("COMPR"); 


				}
				break;
			case 4:
				DebugEnterAlt(4);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:91:7: 'MULR'
				{
				DebugLocation(91, 7);
				Match("MULR"); 


				}
				break;
			case 5:
				DebugEnterAlt(5);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:92:7: 'DIVR'
				{
				DebugLocation(92, 7);
				Match("DIVR"); 


				}
				break;
			case 6:
				DebugEnterAlt(6);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:93:7: 'RMO'
				{
				DebugLocation(93, 7);
				Match("RMO"); 


				}
				break;
			case 7:
				DebugEnterAlt(7);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:94:7: 'SHIFTL'
				{
				DebugLocation(94, 7);
				Match("SHIFTL"); 


				}
				break;
			case 8:
				DebugEnterAlt(8);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:95:7: 'SHIFTR'
				{
				DebugLocation(95, 7);
				Match("SHIFTR"); 


				}
				break;
			case 9:
				DebugEnterAlt(9);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:96:7: 'SVC'
				{
				DebugLocation(96, 7);
				Match("SVC"); 


				}
				break;
			case 10:
				DebugEnterAlt(10);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:97:7: 'CLEAR'
				{
				DebugLocation(97, 7);
				Match("CLEAR"); 


				}
				break;
			case 11:
				DebugEnterAlt(11);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:98:7: 'TIXR'
				{
				DebugLocation(98, 7);
				Match("TIXR"); 


				}
				break;

			}
		}
		finally
		{
			TraceOut("F2_INSTR", 24);
			LeaveRule("F2_INSTR", 24);
			LeaveRule_F2_INSTR();
		}
	}
	// $ANTLR end "F2_INSTR"

	partial void EnterRule_F34_INSTR();
	partial void LeaveRule_F34_INSTR();

	// $ANTLR start "F34_INSTR"
	[GrammarRule("F34_INSTR")]
	private void mF34_INSTR()
	{
		EnterRule_F34_INSTR();
		EnterRule("F34_INSTR", 25);
		TraceIn("F34_INSTR", 25);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:102:5: ( 'ADD' | 'ADDF' | 'AND' | 'COMP' | 'COMPF' | 'DIV' | 'DIVF' | 'J' | 'JEQ' | 'JGT' | 'JLT' | 'JSUB' | 'LDA' | 'LDB' | 'LDCH' | 'LDF' | 'LDL' | 'LDS' | 'LDT' | 'LDX' | 'MUL' | 'MULF' | 'MULR' | 'OR' | 'RD' | 'RSUB' | 'SSK' | 'STA' | 'STB' | 'STCH' | 'STF' | 'STI' | 'STL' | 'STS' | 'STSW' | 'STT' | 'STX' | 'SUB' | 'SUBF' | 'TIX' | 'WD' )
			int alt7=41;
			try { DebugEnterDecision(7, false);
			try
			{
				alt7 = dfa7.Predict(input);
			}
			catch (NoViableAltException nvae)
			{
				DebugRecognitionException(nvae);
				throw;
			}
			} finally { DebugExitDecision(7); }
			switch (alt7)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:102:7: 'ADD'
				{
				DebugLocation(102, 7);
				Match("ADD"); 


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:103:7: 'ADDF'
				{
				DebugLocation(103, 7);
				Match("ADDF"); 


				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:104:7: 'AND'
				{
				DebugLocation(104, 7);
				Match("AND"); 


				}
				break;
			case 4:
				DebugEnterAlt(4);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:105:7: 'COMP'
				{
				DebugLocation(105, 7);
				Match("COMP"); 


				}
				break;
			case 5:
				DebugEnterAlt(5);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:106:7: 'COMPF'
				{
				DebugLocation(106, 7);
				Match("COMPF"); 


				}
				break;
			case 6:
				DebugEnterAlt(6);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:107:7: 'DIV'
				{
				DebugLocation(107, 7);
				Match("DIV"); 


				}
				break;
			case 7:
				DebugEnterAlt(7);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:108:7: 'DIVF'
				{
				DebugLocation(108, 7);
				Match("DIVF"); 


				}
				break;
			case 8:
				DebugEnterAlt(8);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:109:7: 'J'
				{
				DebugLocation(109, 7);
				Match('J'); 

				}
				break;
			case 9:
				DebugEnterAlt(9);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:110:7: 'JEQ'
				{
				DebugLocation(110, 7);
				Match("JEQ"); 


				}
				break;
			case 10:
				DebugEnterAlt(10);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:111:7: 'JGT'
				{
				DebugLocation(111, 7);
				Match("JGT"); 


				}
				break;
			case 11:
				DebugEnterAlt(11);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:112:7: 'JLT'
				{
				DebugLocation(112, 7);
				Match("JLT"); 


				}
				break;
			case 12:
				DebugEnterAlt(12);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:113:7: 'JSUB'
				{
				DebugLocation(113, 7);
				Match("JSUB"); 


				}
				break;
			case 13:
				DebugEnterAlt(13);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:114:7: 'LDA'
				{
				DebugLocation(114, 7);
				Match("LDA"); 


				}
				break;
			case 14:
				DebugEnterAlt(14);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:115:7: 'LDB'
				{
				DebugLocation(115, 7);
				Match("LDB"); 


				}
				break;
			case 15:
				DebugEnterAlt(15);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:116:7: 'LDCH'
				{
				DebugLocation(116, 7);
				Match("LDCH"); 


				}
				break;
			case 16:
				DebugEnterAlt(16);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:117:7: 'LDF'
				{
				DebugLocation(117, 7);
				Match("LDF"); 


				}
				break;
			case 17:
				DebugEnterAlt(17);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:118:7: 'LDL'
				{
				DebugLocation(118, 7);
				Match("LDL"); 


				}
				break;
			case 18:
				DebugEnterAlt(18);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:119:7: 'LDS'
				{
				DebugLocation(119, 7);
				Match("LDS"); 


				}
				break;
			case 19:
				DebugEnterAlt(19);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:120:7: 'LDT'
				{
				DebugLocation(120, 7);
				Match("LDT"); 


				}
				break;
			case 20:
				DebugEnterAlt(20);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:121:7: 'LDX'
				{
				DebugLocation(121, 7);
				Match("LDX"); 


				}
				break;
			case 21:
				DebugEnterAlt(21);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:122:7: 'MUL'
				{
				DebugLocation(122, 7);
				Match("MUL"); 


				}
				break;
			case 22:
				DebugEnterAlt(22);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:123:7: 'MULF'
				{
				DebugLocation(123, 7);
				Match("MULF"); 


				}
				break;
			case 23:
				DebugEnterAlt(23);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:124:7: 'MULR'
				{
				DebugLocation(124, 7);
				Match("MULR"); 


				}
				break;
			case 24:
				DebugEnterAlt(24);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:125:7: 'OR'
				{
				DebugLocation(125, 7);
				Match("OR"); 


				}
				break;
			case 25:
				DebugEnterAlt(25);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:126:7: 'RD'
				{
				DebugLocation(126, 7);
				Match("RD"); 


				}
				break;
			case 26:
				DebugEnterAlt(26);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:127:7: 'RSUB'
				{
				DebugLocation(127, 7);
				Match("RSUB"); 


				}
				break;
			case 27:
				DebugEnterAlt(27);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:128:7: 'SSK'
				{
				DebugLocation(128, 7);
				Match("SSK"); 


				}
				break;
			case 28:
				DebugEnterAlt(28);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:129:7: 'STA'
				{
				DebugLocation(129, 7);
				Match("STA"); 


				}
				break;
			case 29:
				DebugEnterAlt(29);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:130:7: 'STB'
				{
				DebugLocation(130, 7);
				Match("STB"); 


				}
				break;
			case 30:
				DebugEnterAlt(30);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:131:7: 'STCH'
				{
				DebugLocation(131, 7);
				Match("STCH"); 


				}
				break;
			case 31:
				DebugEnterAlt(31);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:132:7: 'STF'
				{
				DebugLocation(132, 7);
				Match("STF"); 


				}
				break;
			case 32:
				DebugEnterAlt(32);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:133:7: 'STI'
				{
				DebugLocation(133, 7);
				Match("STI"); 


				}
				break;
			case 33:
				DebugEnterAlt(33);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:134:7: 'STL'
				{
				DebugLocation(134, 7);
				Match("STL"); 


				}
				break;
			case 34:
				DebugEnterAlt(34);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:135:7: 'STS'
				{
				DebugLocation(135, 7);
				Match("STS"); 


				}
				break;
			case 35:
				DebugEnterAlt(35);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:136:7: 'STSW'
				{
				DebugLocation(136, 7);
				Match("STSW"); 


				}
				break;
			case 36:
				DebugEnterAlt(36);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:137:7: 'STT'
				{
				DebugLocation(137, 7);
				Match("STT"); 


				}
				break;
			case 37:
				DebugEnterAlt(37);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:138:7: 'STX'
				{
				DebugLocation(138, 7);
				Match("STX"); 


				}
				break;
			case 38:
				DebugEnterAlt(38);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:139:7: 'SUB'
				{
				DebugLocation(139, 7);
				Match("SUB"); 


				}
				break;
			case 39:
				DebugEnterAlt(39);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:140:7: 'SUBF'
				{
				DebugLocation(140, 7);
				Match("SUBF"); 


				}
				break;
			case 40:
				DebugEnterAlt(40);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:141:7: 'TIX'
				{
				DebugLocation(141, 7);
				Match("TIX"); 


				}
				break;
			case 41:
				DebugEnterAlt(41);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:142:7: 'WD'
				{
				DebugLocation(142, 7);
				Match("WD"); 


				}
				break;

			}
		}
		finally
		{
			TraceOut("F34_INSTR", 25);
			LeaveRule("F34_INSTR", 25);
			LeaveRule_F34_INSTR();
		}
	}
	// $ANTLR end "F34_INSTR"

	partial void EnterRule_F1CODOP();
	partial void LeaveRule_F1CODOP();

	// $ANTLR start "F1CODOP"
	[GrammarRule("F1CODOP")]
	private void mF1CODOP()
	{
		EnterRule_F1CODOP();
		EnterRule("F1CODOP", 26);
		TraceIn("F1CODOP", 26);
		try
		{
			int _type = F1CODOP;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:145:10: ( F1_INSTR )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:145:12: F1_INSTR
			{
			DebugLocation(145, 12);
			mF1_INSTR(); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("F1CODOP", 26);
			LeaveRule("F1CODOP", 26);
			LeaveRule_F1CODOP();
		}
	}
	// $ANTLR end "F1CODOP"

	partial void EnterRule_F2CODOP();
	partial void LeaveRule_F2CODOP();

	// $ANTLR start "F2CODOP"
	[GrammarRule("F2CODOP")]
	private void mF2CODOP()
	{
		EnterRule_F2CODOP();
		EnterRule("F2CODOP", 27);
		TraceIn("F2CODOP", 27);
		try
		{
			int _type = F2CODOP;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:146:10: ( F2_INSTR )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:146:12: F2_INSTR
			{
			DebugLocation(146, 12);
			mF2_INSTR(); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("F2CODOP", 27);
			LeaveRule("F2CODOP", 27);
			LeaveRule_F2CODOP();
		}
	}
	// $ANTLR end "F2CODOP"

	partial void EnterRule_F34CODOP();
	partial void LeaveRule_F34CODOP();

	// $ANTLR start "F34CODOP"
	[GrammarRule("F34CODOP")]
	private void mF34CODOP()
	{
		EnterRule_F34CODOP();
		EnterRule("F34CODOP", 28);
		TraceIn("F34CODOP", 28);
		try
		{
			int _type = F34CODOP;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:147:10: ( F34_INSTR )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:147:12: F34_INSTR
			{
			DebugLocation(147, 12);
			mF34_INSTR(); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("F34CODOP", 28);
			LeaveRule("F34CODOP", 28);
			LeaveRule_F34CODOP();
		}
	}
	// $ANTLR end "F34CODOP"

	partial void EnterRule_NUM();
	partial void LeaveRule_NUM();

	// $ANTLR start "NUM"
	[GrammarRule("NUM")]
	private void mNUM()
	{
		EnterRule_NUM();
		EnterRule("NUM", 29);
		TraceIn("NUM", 29);
		try
		{
			int _type = NUM;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:153:5: ( ( '0' .. '9' )+ )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:153:7: ( '0' .. '9' )+
			{
			DebugLocation(153, 7);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:153:7: ( '0' .. '9' )+
			int cnt8=0;
			try { DebugEnterSubRule(8);
			while (true)
			{
				int alt8=2;
				try { DebugEnterDecision(8, false);
				int LA8_1 = input.LA(1);

				if (((LA8_1>='0' && LA8_1<='9')))
				{
					alt8 = 1;
				}


				} finally { DebugExitDecision(8); }
				switch (alt8)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:
					{
					DebugLocation(153, 7);
					input.Consume();


					}
					break;

				default:
					if (cnt8 >= 1)
						goto loop8;

					EarlyExitException eee8 = new EarlyExitException( 8, input );
					DebugRecognitionException(eee8);
					throw eee8;
				}
				cnt8++;
			}
			loop8:
				;

			} finally { DebugExitSubRule(8); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("NUM", 29);
			LeaveRule("NUM", 29);
			LeaveRule_NUM();
		}
	}
	// $ANTLR end "NUM"

	partial void EnterRule_CONSTHEX();
	partial void LeaveRule_CONSTHEX();

	// $ANTLR start "CONSTHEX"
	[GrammarRule("CONSTHEX")]
	private void mCONSTHEX()
	{
		EnterRule_CONSTHEX();
		EnterRule("CONSTHEX", 30);
		TraceIn("CONSTHEX", 30);
		try
		{
			int _type = CONSTHEX;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:157:5: ( '0x' ( '0' .. '9' | 'a' .. 'f' | 'A' .. 'F' )+ )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:157:7: '0x' ( '0' .. '9' | 'a' .. 'f' | 'A' .. 'F' )+
			{
			DebugLocation(157, 7);
			Match("0x"); 

			DebugLocation(157, 12);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:157:12: ( '0' .. '9' | 'a' .. 'f' | 'A' .. 'F' )+
			int cnt9=0;
			try { DebugEnterSubRule(9);
			while (true)
			{
				int alt9=2;
				try { DebugEnterDecision(9, false);
				int LA9_1 = input.LA(1);

				if (((LA9_1>='0' && LA9_1<='9')||(LA9_1>='A' && LA9_1<='F')||(LA9_1>='a' && LA9_1<='f')))
				{
					alt9 = 1;
				}


				} finally { DebugExitDecision(9); }
				switch (alt9)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:
					{
					DebugLocation(157, 12);
					input.Consume();


					}
					break;

				default:
					if (cnt9 >= 1)
						goto loop9;

					EarlyExitException eee9 = new EarlyExitException( 9, input );
					DebugRecognitionException(eee9);
					throw eee9;
				}
				cnt9++;
			}
			loop9:
				;

			} finally { DebugExitSubRule(9); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("CONSTHEX", 30);
			LeaveRule("CONSTHEX", 30);
			LeaveRule_CONSTHEX();
		}
	}
	// $ANTLR end "CONSTHEX"

	partial void EnterRule_HEXSUF();
	partial void LeaveRule_HEXSUF();

	// $ANTLR start "HEXSUF"
	[GrammarRule("HEXSUF")]
	private void mHEXSUF()
	{
		EnterRule_HEXSUF();
		EnterRule("HEXSUF", 31);
		TraceIn("HEXSUF", 31);
		try
		{
			int _type = HEXSUF;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:161:5: ( ( '0' .. '9' | 'a' .. 'f' | 'A' .. 'F' )+ ( 'h' | 'H' ) )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:161:7: ( '0' .. '9' | 'a' .. 'f' | 'A' .. 'F' )+ ( 'h' | 'H' )
			{
			DebugLocation(161, 7);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:161:7: ( '0' .. '9' | 'a' .. 'f' | 'A' .. 'F' )+
			int cnt10=0;
			try { DebugEnterSubRule(10);
			while (true)
			{
				int alt10=2;
				try { DebugEnterDecision(10, false);
				int LA10_1 = input.LA(1);

				if (((LA10_1>='0' && LA10_1<='9')||(LA10_1>='A' && LA10_1<='F')||(LA10_1>='a' && LA10_1<='f')))
				{
					alt10 = 1;
				}


				} finally { DebugExitDecision(10); }
				switch (alt10)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:
					{
					DebugLocation(161, 7);
					input.Consume();


					}
					break;

				default:
					if (cnt10 >= 1)
						goto loop10;

					EarlyExitException eee10 = new EarlyExitException( 10, input );
					DebugRecognitionException(eee10);
					throw eee10;
				}
				cnt10++;
			}
			loop10:
				;

			} finally { DebugExitSubRule(10); }

			DebugLocation(161, 42);
			if (input.LA(1)=='H'||input.LA(1)=='h')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("HEXSUF", 31);
			LeaveRule("HEXSUF", 31);
			LeaveRule_HEXSUF();
		}
	}
	// $ANTLR end "HEXSUF"

	partial void EnterRule_CONSTCAD();
	partial void LeaveRule_CONSTCAD();

	// $ANTLR start "CONSTCAD"
	[GrammarRule("CONSTCAD")]
	private void mCONSTCAD()
	{
		EnterRule_CONSTCAD();
		EnterRule("CONSTCAD", 32);
		TraceIn("CONSTCAD", 32);
		try
		{
			int _type = CONSTCAD;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:165:5: ( '\"' ( '\\\\' . |~ ( '\\\"' | '\\\\' ) )* '\"' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:165:7: '\"' ( '\\\\' . |~ ( '\\\"' | '\\\\' ) )* '\"'
			{
			DebugLocation(165, 7);
			Match('\"'); 
			DebugLocation(165, 11);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:165:11: ( '\\\\' . |~ ( '\\\"' | '\\\\' ) )*
			try { DebugEnterSubRule(11);
			while (true)
			{
				int alt11=3;
				try { DebugEnterDecision(11, false);
				int LA11_1 = input.LA(1);

				if ((LA11_1=='\\'))
				{
					alt11 = 1;
				}
				else if (((LA11_1>='\u0000' && LA11_1<='!')||(LA11_1>='#' && LA11_1<='[')||(LA11_1>=']' && LA11_1<='\uFFFF')))
				{
					alt11 = 2;
				}


				} finally { DebugExitDecision(11); }
				switch ( alt11 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:165:13: '\\\\' .
					{
					DebugLocation(165, 13);
					Match('\\'); 
					DebugLocation(165, 18);
					MatchAny(); 

					}
					break;
				case 2:
					DebugEnterAlt(2);
					// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:165:22: ~ ( '\\\"' | '\\\\' )
					{
					DebugLocation(165, 22);
					input.Consume();


					}
					break;

				default:
					goto loop11;
				}
			}

			loop11:
				;

			} finally { DebugExitSubRule(11); }

			DebugLocation(165, 38);
			Match('\"'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("CONSTCAD", 32);
			LeaveRule("CONSTCAD", 32);
			LeaveRule_CONSTCAD();
		}
	}
	// $ANTLR end "CONSTCAD"

	partial void EnterRule_ID();
	partial void LeaveRule_ID();

	// $ANTLR start "ID"
	[GrammarRule("ID")]
	private void mID()
	{
		EnterRule_ID();
		EnterRule("ID", 33);
		TraceIn("ID", 33);
		try
		{
			int _type = ID;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:169:5: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )* )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:169:7: ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*
			{
			DebugLocation(169, 7);
			if ((input.LA(1)>='A' && input.LA(1)<='Z')||input.LA(1)=='_'||(input.LA(1)>='a' && input.LA(1)<='z'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}

			DebugLocation(170, 7);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:170:7: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*
			try { DebugEnterSubRule(12);
			while (true)
			{
				int alt12=2;
				try { DebugEnterDecision(12, false);
				int LA12_1 = input.LA(1);

				if (((LA12_1>='0' && LA12_1<='9')||(LA12_1>='A' && LA12_1<='Z')||LA12_1=='_'||(LA12_1>='a' && LA12_1<='z')))
				{
					alt12 = 1;
				}


				} finally { DebugExitDecision(12); }
				switch ( alt12 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:
					{
					DebugLocation(170, 7);
					input.Consume();


					}
					break;

				default:
					goto loop12;
				}
			}

			loop12:
				;

			} finally { DebugExitSubRule(12); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ID", 33);
			LeaveRule("ID", 33);
			LeaveRule_ID();
		}
	}
	// $ANTLR end "ID"

	partial void EnterRule_CHCONST();
	partial void LeaveRule_CHCONST();

	// $ANTLR start "CHCONST"
	[GrammarRule("CHCONST")]
	private void mCHCONST()
	{
		EnterRule_CHCONST();
		EnterRule("CHCONST", 34);
		TraceIn("CHCONST", 34);
		try
		{
			int _type = CHCONST;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:174:5: ( 'C' '\\'' (~ ( '\\'' | '\\r' | '\\n' ) )* '\\'' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:174:7: 'C' '\\'' (~ ( '\\'' | '\\r' | '\\n' ) )* '\\''
			{
			DebugLocation(174, 7);
			Match('C'); 
			DebugLocation(174, 11);
			Match('\''); 
			DebugLocation(174, 16);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:174:16: (~ ( '\\'' | '\\r' | '\\n' ) )*
			try { DebugEnterSubRule(13);
			while (true)
			{
				int alt13=2;
				try { DebugEnterDecision(13, false);
				int LA13_1 = input.LA(1);

				if (((LA13_1>='\u0000' && LA13_1<='\t')||(LA13_1>='\u000B' && LA13_1<='\f')||(LA13_1>='\u000E' && LA13_1<='&')||(LA13_1>='(' && LA13_1<='\uFFFF')))
				{
					alt13 = 1;
				}


				} finally { DebugExitDecision(13); }
				switch ( alt13 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:
					{
					DebugLocation(174, 16);
					input.Consume();


					}
					break;

				default:
					goto loop13;
				}
			}

			loop13:
				;

			} finally { DebugExitSubRule(13); }

			DebugLocation(174, 43);
			Match('\''); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("CHCONST", 34);
			LeaveRule("CHCONST", 34);
			LeaveRule_CHCONST();
		}
	}
	// $ANTLR end "CHCONST"

	partial void EnterRule_HEXCONST();
	partial void LeaveRule_HEXCONST();

	// $ANTLR start "HEXCONST"
	[GrammarRule("HEXCONST")]
	private void mHEXCONST()
	{
		EnterRule_HEXCONST();
		EnterRule("HEXCONST", 35);
		TraceIn("HEXCONST", 35);
		try
		{
			int _type = HEXCONST;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:178:5: ( 'X' '\\'' ( ( '0' .. '9' ) | ( 'a' .. 'f' ) | ( 'A' .. 'F' ) )+ '\\'' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:178:7: 'X' '\\'' ( ( '0' .. '9' ) | ( 'a' .. 'f' ) | ( 'A' .. 'F' ) )+ '\\''
			{
			DebugLocation(178, 7);
			Match('X'); 
			DebugLocation(178, 11);
			Match('\''); 
			DebugLocation(178, 16);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:178:16: ( ( '0' .. '9' ) | ( 'a' .. 'f' ) | ( 'A' .. 'F' ) )+
			int cnt14=0;
			try { DebugEnterSubRule(14);
			while (true)
			{
				int alt14=2;
				try { DebugEnterDecision(14, false);
				int LA14_1 = input.LA(1);

				if (((LA14_1>='0' && LA14_1<='9')||(LA14_1>='A' && LA14_1<='F')||(LA14_1>='a' && LA14_1<='f')))
				{
					alt14 = 1;
				}


				} finally { DebugExitDecision(14); }
				switch (alt14)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:
					{
					DebugLocation(178, 16);
					input.Consume();


					}
					break;

				default:
					if (cnt14 >= 1)
						goto loop14;

					EarlyExitException eee14 = new EarlyExitException( 14, input );
					DebugRecognitionException(eee14);
					throw eee14;
				}
				cnt14++;
			}
			loop14:
				;

			} finally { DebugExitSubRule(14); }

			DebugLocation(178, 58);
			Match('\''); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("HEXCONST", 35);
			LeaveRule("HEXCONST", 35);
			LeaveRule_HEXCONST();
		}
	}
	// $ANTLR end "HEXCONST"

	partial void EnterRule_WS();
	partial void LeaveRule_WS();

	// $ANTLR start "WS"
	[GrammarRule("WS")]
	private void mWS()
	{
		EnterRule_WS();
		EnterRule("WS", 36);
		TraceIn("WS", 36);
		try
		{
			int _type = WS;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:183:5: ( ( ' ' | '\\t' )+ )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:183:7: ( ' ' | '\\t' )+
			{
			DebugLocation(183, 7);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:183:7: ( ' ' | '\\t' )+
			int cnt15=0;
			try { DebugEnterSubRule(15);
			while (true)
			{
				int alt15=2;
				try { DebugEnterDecision(15, false);
				int LA15_1 = input.LA(1);

				if ((LA15_1=='\t'||LA15_1==' '))
				{
					alt15 = 1;
				}


				} finally { DebugExitDecision(15); }
				switch (alt15)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:
					{
					DebugLocation(183, 7);
					input.Consume();


					}
					break;

				default:
					if (cnt15 >= 1)
						goto loop15;

					EarlyExitException eee15 = new EarlyExitException( 15, input );
					DebugRecognitionException(eee15);
					throw eee15;
				}
				cnt15++;
			}
			loop15:
				;

			} finally { DebugExitSubRule(15); }

			DebugLocation(183, 21);
			 _channel = Hidden; 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("WS", 36);
			LeaveRule("WS", 36);
			LeaveRule_WS();
		}
	}
	// $ANTLR end "WS"

	public override void mTokens()
	{
		// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:8: ( T__41 | START | END | BYTE | WORD | RESB | RESW | BASE | EQU | ORG | USE | FINL | REG | INDICE | PLUS | MINUS | STAR | DIV | LPAREN | RPAREN | AT | NUMERAL | F1CODOP | F2CODOP | F34CODOP | NUM | CONSTHEX | HEXSUF | CONSTCAD | ID | CHCONST | HEXCONST | WS )
		int alt16=33;
		try { DebugEnterDecision(16, false);
		try
		{
			alt16 = dfa16.Predict(input);
		}
		catch (NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
			throw;
		}
		} finally { DebugExitDecision(16); }
		switch (alt16)
		{
		case 1:
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:10: T__41
			{
			DebugLocation(1, 10);
			mT__41(); 

			}
			break;
		case 2:
			DebugEnterAlt(2);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:16: START
			{
			DebugLocation(1, 16);
			mSTART(); 

			}
			break;
		case 3:
			DebugEnterAlt(3);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:22: END
			{
			DebugLocation(1, 22);
			mEND(); 

			}
			break;
		case 4:
			DebugEnterAlt(4);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:26: BYTE
			{
			DebugLocation(1, 26);
			mBYTE(); 

			}
			break;
		case 5:
			DebugEnterAlt(5);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:31: WORD
			{
			DebugLocation(1, 31);
			mWORD(); 

			}
			break;
		case 6:
			DebugEnterAlt(6);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:36: RESB
			{
			DebugLocation(1, 36);
			mRESB(); 

			}
			break;
		case 7:
			DebugEnterAlt(7);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:41: RESW
			{
			DebugLocation(1, 41);
			mRESW(); 

			}
			break;
		case 8:
			DebugEnterAlt(8);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:46: BASE
			{
			DebugLocation(1, 46);
			mBASE(); 

			}
			break;
		case 9:
			DebugEnterAlt(9);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:51: EQU
			{
			DebugLocation(1, 51);
			mEQU(); 

			}
			break;
		case 10:
			DebugEnterAlt(10);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:55: ORG
			{
			DebugLocation(1, 55);
			mORG(); 

			}
			break;
		case 11:
			DebugEnterAlt(11);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:59: USE
			{
			DebugLocation(1, 59);
			mUSE(); 

			}
			break;
		case 12:
			DebugEnterAlt(12);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:63: FINL
			{
			DebugLocation(1, 63);
			mFINL(); 

			}
			break;
		case 13:
			DebugEnterAlt(13);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:68: REG
			{
			DebugLocation(1, 68);
			mREG(); 

			}
			break;
		case 14:
			DebugEnterAlt(14);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:72: INDICE
			{
			DebugLocation(1, 72);
			mINDICE(); 

			}
			break;
		case 15:
			DebugEnterAlt(15);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:79: PLUS
			{
			DebugLocation(1, 79);
			mPLUS(); 

			}
			break;
		case 16:
			DebugEnterAlt(16);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:84: MINUS
			{
			DebugLocation(1, 84);
			mMINUS(); 

			}
			break;
		case 17:
			DebugEnterAlt(17);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:90: STAR
			{
			DebugLocation(1, 90);
			mSTAR(); 

			}
			break;
		case 18:
			DebugEnterAlt(18);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:95: DIV
			{
			DebugLocation(1, 95);
			mDIV(); 

			}
			break;
		case 19:
			DebugEnterAlt(19);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:99: LPAREN
			{
			DebugLocation(1, 99);
			mLPAREN(); 

			}
			break;
		case 20:
			DebugEnterAlt(20);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:106: RPAREN
			{
			DebugLocation(1, 106);
			mRPAREN(); 

			}
			break;
		case 21:
			DebugEnterAlt(21);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:113: AT
			{
			DebugLocation(1, 113);
			mAT(); 

			}
			break;
		case 22:
			DebugEnterAlt(22);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:116: NUMERAL
			{
			DebugLocation(1, 116);
			mNUMERAL(); 

			}
			break;
		case 23:
			DebugEnterAlt(23);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:124: F1CODOP
			{
			DebugLocation(1, 124);
			mF1CODOP(); 

			}
			break;
		case 24:
			DebugEnterAlt(24);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:132: F2CODOP
			{
			DebugLocation(1, 132);
			mF2CODOP(); 

			}
			break;
		case 25:
			DebugEnterAlt(25);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:140: F34CODOP
			{
			DebugLocation(1, 140);
			mF34CODOP(); 

			}
			break;
		case 26:
			DebugEnterAlt(26);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:149: NUM
			{
			DebugLocation(1, 149);
			mNUM(); 

			}
			break;
		case 27:
			DebugEnterAlt(27);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:153: CONSTHEX
			{
			DebugLocation(1, 153);
			mCONSTHEX(); 

			}
			break;
		case 28:
			DebugEnterAlt(28);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:162: HEXSUF
			{
			DebugLocation(1, 162);
			mHEXSUF(); 

			}
			break;
		case 29:
			DebugEnterAlt(29);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:169: CONSTCAD
			{
			DebugLocation(1, 169);
			mCONSTCAD(); 

			}
			break;
		case 30:
			DebugEnterAlt(30);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:178: ID
			{
			DebugLocation(1, 178);
			mID(); 

			}
			break;
		case 31:
			DebugEnterAlt(31);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:181: CHCONST
			{
			DebugLocation(1, 181);
			mCHCONST(); 

			}
			break;
		case 32:
			DebugEnterAlt(32);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:189: HEXCONST
			{
			DebugLocation(1, 189);
			mHEXCONST(); 

			}
			break;
		case 33:
			DebugEnterAlt(33);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:198: WS
			{
			DebugLocation(1, 198);
			mWS(); 

			}
			break;

		}

	}


	#region DFA
	DFA7 dfa7;
	DFA16 dfa16;

	protected override void InitDFAs()
	{
		base.InitDFAs();
		dfa7 = new DFA7(this);
		dfa16 = new DFA16(this);
	}

	private class DFA7 : DFA
	{
		private const string DFA7_eotS =
			"\x4\xFFFF\x1\x14\x17\xFFFF\x1\x33\x1\xFFFF\x1\x36\x8\xFFFF\x1\x39\x6"+
			"\xFFFF\x1\x3B\x2\xFFFF\x1\x3D\x2\xFFFF\x1\x3F\xB\xFFFF";
		private const string DFA7_eofS =
			"\x40\xFFFF";
		private const string DFA7_minS =
			"\x1\x41\x1\x44\x1\x4F\x1\x49\x1\x45\x1\x44\x1\x55\x1\xFFFF\x1\x44\x1"+
			"\x53\x2\xFFFF\x1\x44\x1\xFFFF\x1\x4D\x1\x56\x5\xFFFF\x1\x41\x1\x4C\x3"+
			"\xFFFF\x1\x41\x1\x42\x1\x46\x1\x50\x1\x46\x8\xFFFF\x1\x46\x6\xFFFF\x1"+
			"\x57\x2\xFFFF\x1\x46\x2\xFFFF\x1\x46\xB\xFFFF";
		private const string DFA7_maxS =
			"\x1\x57\x1\x4E\x1\x4F\x1\x49\x1\x53\x1\x44\x1\x55\x1\xFFFF\x1\x53\x1"+
			"\x55\x2\xFFFF\x1\x44\x1\xFFFF\x1\x4D\x1\x56\x5\xFFFF\x1\x58\x1\x4C\x3"+
			"\xFFFF\x1\x58\x1\x42\x1\x46\x1\x50\x1\x46\x8\xFFFF\x1\x52\x6\xFFFF\x1"+
			"\x57\x2\xFFFF\x1\x46\x2\xFFFF\x1\x46\xB\xFFFF";
		private const string DFA7_acceptS =
			"\x7\xFFFF\x1\x18\x2\xFFFF\x1\x28\x1\x29\x1\xFFFF\x1\x3\x2\xFFFF\x1\x9"+
			"\x1\xA\x1\xB\x1\xC\x1\x8\x2\xFFFF\x1\x19\x1\x1A\x1\x1B\x5\xFFFF\x1\xD"+
			"\x1\xE\x1\xF\x1\x10\x1\x11\x1\x12\x1\x13\x1\x14\x1\xFFFF\x1\x1C\x1\x1D"+
			"\x1\x1E\x1\x1F\x1\x20\x1\x21\x1\xFFFF\x1\x24\x1\x25\x1\xFFFF\x1\x2\x1"+
			"\x1\x1\xFFFF\x1\x7\x1\x6\x1\x16\x1\x17\x1\x15\x1\x23\x1\x22\x1\x27\x1"+
			"\x26\x1\x5\x1\x4";
		private const string DFA7_specialS =
			"\x40\xFFFF}>";
		private static readonly string[] DFA7_transitionS =
			{
				"\x1\x1\x1\xFFFF\x1\x2\x1\x3\x5\xFFFF\x1\x4\x1\xFFFF\x1\x5\x1\x6\x1\xFFFF"+
				"\x1\x7\x2\xFFFF\x1\x8\x1\x9\x1\xA\x2\xFFFF\x1\xB",
				"\x1\xC\x9\xFFFF\x1\xD",
				"\x1\xE",
				"\x1\xF",
				"\x1\x10\x1\xFFFF\x1\x11\x4\xFFFF\x1\x12\x6\xFFFF\x1\x13",
				"\x1\x15",
				"\x1\x16",
				"",
				"\x1\x17\xE\xFFFF\x1\x18",
				"\x1\x19\x1\x1A\x1\x1B",
				"",
				"",
				"\x1\x1C",
				"",
				"\x1\x1D",
				"\x1\x1E",
				"",
				"",
				"",
				"",
				"",
				"\x1\x1F\x1\x20\x1\x21\x2\xFFFF\x1\x22\x5\xFFFF\x1\x23\x6\xFFFF\x1\x24"+
				"\x1\x25\x3\xFFFF\x1\x26",
				"\x1\x27",
				"",
				"",
				"",
				"\x1\x28\x1\x29\x1\x2A\x2\xFFFF\x1\x2B\x2\xFFFF\x1\x2C\x2\xFFFF\x1\x2D"+
				"\x6\xFFFF\x1\x2E\x1\x2F\x3\xFFFF\x1\x30",
				"\x1\x31",
				"\x1\x32",
				"\x1\x34",
				"\x1\x35",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"\x1\x37\xB\xFFFF\x1\x38",
				"",
				"",
				"",
				"",
				"",
				"",
				"\x1\x3A",
				"",
				"",
				"\x1\x3C",
				"",
				"",
				"\x1\x3E",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				""
			};

		private static readonly short[] DFA7_eot = DFA.UnpackEncodedString(DFA7_eotS);
		private static readonly short[] DFA7_eof = DFA.UnpackEncodedString(DFA7_eofS);
		private static readonly char[] DFA7_min = DFA.UnpackEncodedStringToUnsignedChars(DFA7_minS);
		private static readonly char[] DFA7_max = DFA.UnpackEncodedStringToUnsignedChars(DFA7_maxS);
		private static readonly short[] DFA7_accept = DFA.UnpackEncodedString(DFA7_acceptS);
		private static readonly short[] DFA7_special = DFA.UnpackEncodedString(DFA7_specialS);
		private static readonly short[][] DFA7_transition;

		static DFA7()
		{
			int numStates = DFA7_transitionS.Length;
			DFA7_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA7_transition[i] = DFA.UnpackEncodedString(DFA7_transitionS[i]);
			}
		}

		public DFA7( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 7;
			this.eot = DFA7_eot;
			this.eof = DFA7_eof;
			this.min = DFA7_min;
			this.max = DFA7_max;
			this.accept = DFA7_accept;
			this.special = DFA7_special;
			this.transition = DFA7_transition;
		}

		public override string Description { get { return "101:10: fragment F34_INSTR : ( 'ADD' | 'ADDF' | 'AND' | 'COMP' | 'COMPF' | 'DIV' | 'DIVF' | 'J' | 'JEQ' | 'JGT' | 'JLT' | 'JSUB' | 'LDA' | 'LDB' | 'LDCH' | 'LDF' | 'LDL' | 'LDS' | 'LDT' | 'LDX' | 'MUL' | 'MULF' | 'MULR' | 'OR' | 'RD' | 'RSUB' | 'SSK' | 'STA' | 'STB' | 'STCH' | 'STF' | 'STI' | 'STL' | 'STS' | 'STSW' | 'STT' | 'STX' | 'SUB' | 'SUBF' | 'TIX' | 'WD' );"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}

	private class DFA16 : DFA
	{
		private const string DFA16_eotS =
			"\x2\xFFFF\x3\x2A\x4\x22\x1\xFFFF\x1\x2A\x1\x22\x8\xFFFF\x1\x2A\x2\x22"+
			"\x3\x2A\x1\x22\x1\x2A\x1\x4D\x1\x2A\x2\x50\x1\x22\x3\xFFFF\x6\x22\x1"+
			"\xFFFF\x2\x22\x1\x51\x4\x22\x1\x4D\x2\x22\x1\x4D\x1\x22\x1\x4D\x3\x22"+
			"\x3\x6C\x7\x22\x1\xFFFF\x7\x22\x5\xFFFF\x2\x4D\x1\x22\x6\x4D\x1\x86\x1"+
			"\x4D\x1\x22\x1\x8A\x1\x4D\x1\x8B\x1\x8C\x4\x22\x1\x8A\x1\x22\x1\x93\x1"+
			"\x94\x1\x86\x1\x22\x1\xFFFF\x1\x86\x1\x4D\x1\x22\x1\x86\x2\x4D\x2\x22"+
			"\x4\x4D\x1\x22\x8\x4D\x2\x22\x2\x4D\x1\xFFFF\x1\x8A\x1\x4D\x1\x22\x3"+
			"\xFFFF\x1\xA4\x1\xA5\x1\xA6\x1\xA7\x1\xA8\x1\x4D\x2\xFFFF\x1\x22\x1\x8A"+
			"\x1\x86\x1\x8A\x2\x4D\x1\x22\x1\x8A\x1\x4D\x1\x8A\x3\x4D\x1\xAD\x1\x22"+
			"\x5\xFFFF\x1\x86\x1\x8A\x1\x4D\x1\x8A\x1\xFFFF\x2\x8A";
		private const string DFA16_eofS =
			"\xB0\xFFFF";
		private const string DFA16_minS =
			"\x1\x9\x1\xFFFF\x3\x30\x2\x44\x1\x52\x1\x53\x1\xFFFF\x1\x30\x1\x58\x8"+
			"\xFFFF\x1\x30\x1\x4F\x1\x49\x1\x30\x1\x27\x1\x30\x1\x55\x2\x30\x1\x27"+
			"\x3\x30\x3\xFFFF\x1\x41\x1\x4F\x1\x42\x1\x49\x1\x43\x1\x4B\x1\xFFFF\x1"+
			"\x44\x1\x55\x2\x30\x1\x54\x1\x30\x1\x52\x1\x30\x1\x53\x1\x4F\x1\x30\x1"+
			"\x55\x1\x30\x1\x45\x1\x58\x1\x4F\x3\x30\x1\x4F\x1\x52\x1\x4F\x1\x30\x1"+
			"\x44\x1\x4D\x1\x45\x1\xFFFF\x1\x56\x1\x4C\x1\x41\x1\x51\x2\x54\x1\x55"+
			"\x5\xFFFF\x2\x30\x1\x48\x8\x30\x1\x46\x4\x30\x2\x45\x1\x44\x1\x42\x1"+
			"\x30\x1\x42\x3\x30\x1\x41\x1\xFFFF\x2\x30\x1\x4D\x3\x30\x1\x50\x1\x41"+
			"\x4\x30\x1\x48\x8\x30\x1\x42\x1\x54\x2\x30\x1\xFFFF\x2\x30\x1\x54\x3"+
			"\xFFFF\x6\x30\x2\xFFFF\x1\x54\x5\x30\x1\x52\x7\x30\x1\x4C\x5\xFFFF\x4"+
			"\x30\x1\xFFFF\x2\x30";
		private const string DFA16_maxS =
			"\x1\x7A\x1\xFFFF\x3\x7A\x1\x4F\x1\x53\x1\x52\x1\x53\x1\xFFFF\x1\x7A\x1"+
			"\x5A\x8\xFFFF\x1\x7A\x1\x4F\x1\x49\x3\x7A\x1\x55\x3\x7A\x1\x78\x2\x68"+
			"\x3\xFFFF\x1\x58\x1\x4F\x1\x42\x1\x49\x1\x43\x1\x4B\x1\xFFFF\x1\x44\x1"+
			"\x55\x1\x7A\x1\x68\x1\x54\x1\x68\x1\x52\x1\x7A\x1\x53\x1\x4F\x1\x7A\x1"+
			"\x55\x1\x7A\x1\x45\x1\x58\x1\x4F\x3\x7A\x1\x58\x1\x52\x1\x4F\x1\x68\x1"+
			"\x44\x1\x4D\x1\x45\x1\xFFFF\x1\x56\x1\x4C\x1\x58\x1\x51\x2\x54\x1\x55"+
			"\x5\xFFFF\x2\x7A\x1\x48\x8\x7A\x1\x46\x4\x7A\x2\x45\x1\x44\x1\x57\x1"+
			"\x7A\x1\x42\x3\x7A\x1\x41\x1\xFFFF\x2\x7A\x1\x4D\x3\x7A\x1\x50\x1\x41"+
			"\x4\x7A\x1\x48\x8\x7A\x1\x42\x1\x54\x2\x7A\x1\xFFFF\x2\x7A\x1\x54\x3"+
			"\xFFFF\x6\x7A\x2\xFFFF\x1\x54\x5\x7A\x1\x52\x7\x7A\x1\x52\x5\xFFFF\x4"+
			"\x7A\x1\xFFFF\x2\x7A";
		private const string DFA16_acceptS =
			"\x1\xFFFF\x1\x1\x7\xFFFF\x1\xC\x2\xFFFF\x1\xF\x1\x10\x1\x11\x1\x12\x1"+
			"\x13\x1\x14\x1\x15\x1\x16\xD\xFFFF\x1\x1D\x1\x1E\x1\x21\x6\xFFFF\x1\xD"+
			"\x1A\xFFFF\x1\x1F\x7\xFFFF\x1\x19\x1\x20\x1\x1B\x1\x1A\x1\x1C\x1A\xFFFF"+
			"\x1\xE\x19\xFFFF\x1\x17\x3\xFFFF\x1\x18\x1\x3\x1\x9\x6\xFFFF\x1\xA\x1"+
			"\xB\xF\xFFFF\x1\x4\x1\x8\x1\x5\x1\x6\x1\x7\x4\xFFFF\x1\x2\x2\xFFFF";
		private const string DFA16_specialS =
			"\xB0\xFFFF}>";
		private static readonly string[] DFA16_transitionS =
			{
				"\x1\x23\x1\x9\x2\xFFFF\x1\x9\x12\xFFFF\x1\x23\x1\xFFFF\x1\x21\x1\x13"+
				"\x4\xFFFF\x1\x10\x1\x11\x1\xE\x1\xC\x1\x1\x1\xD\x1\xFFFF\x1\xF\x1\x1E"+
				"\x9\x1F\x1\xFFFF\x1\x9\x4\xFFFF\x1\x12\x1\x17\x1\x4\x1\x18\x1\x19\x1"+
				"\x3\x1\xA\x1\x22\x1\x16\x1\xB\x1\x1C\x1\x22\x1\x1B\x1\x1A\x1\x15\x1"+
				"\x7\x2\x22\x1\x6\x1\x2\x1\x14\x1\x8\x1\x22\x1\x5\x1\x1D\x2\x22\x4\xFFFF"+
				"\x1\x22\x1\xFFFF\x6\x20\x14\x22",
				"",
				"\xA\x22\x7\xFFFF\x7\x22\x1\x27\x1\x25\x9\x22\x1\x29\x1\x24\x1\x26\x1"+
				"\x28\x4\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x2E\x7\xFFFF\x6\x2E\x1\x22\x1\x2D\x5\x22\x1\x2B\x2\x22\x1\x2C\x9"+
				"\x22\x4\xFFFF\x1\x22\x1\xFFFF\x6\x2E\x1\x22\x1\x2D\x12\x22",
				"\xA\x2E\x7\xFFFF\x1\x30\x5\x2E\x1\x22\x1\x2D\x10\x22\x1\x2F\x1\x22"+
				"\x4\xFFFF\x1\x22\x1\xFFFF\x6\x2E\x1\x22\x1\x2D\x12\x22",
				"\x1\x32\xA\xFFFF\x1\x31",
				"\x1\x35\x1\x33\x7\xFFFF\x1\x34\x5\xFFFF\x1\x36",
				"\x1\x37",
				"\x1\x38",
				"",
				"\xA\x2E\x7\xFFFF\x6\x2E\x1\x22\x1\x2D\x1\x39\x2\x22\x1\x3A\xE\x22\x4"+
				"\xFFFF\x1\x22\x1\xFFFF\x6\x2E\x1\x22\x1\x2D\x12\x22",
				"\x1\x3B\x1\x3C\x1\x3D",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"\xA\x22\x7\xFFFF\x8\x22\x1\x3E\x11\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A"+
				"\x22",
				"\x1\x3F",
				"\x1\x40",
				"\xA\x2E\x7\xFFFF\x3\x2E\x1\x41\x2\x2E\x1\x22\x1\x2D\x5\x22\x1\x42\xC"+
				"\x22\x4\xFFFF\x1\x22\x1\xFFFF\x6\x2E\x1\x22\x1\x2D\x12\x22",
				"\x1\x45\x8\xFFFF\xA\x2E\x7\xFFFF\x6\x2E\x1\x22\x1\x2D\x3\x22\x1\x44"+
				"\x2\x22\x1\x43\xB\x22\x4\xFFFF\x1\x22\x1\xFFFF\x6\x2E\x1\x22\x1\x2D"+
				"\x12\x22",
				"\xA\x2E\x7\xFFFF\x6\x2E\x1\x22\x1\x2D\x1\x46\x11\x22\x4\xFFFF\x1\x22"+
				"\x1\xFFFF\x6\x2E\x1\x22\x1\x2D\x12\x22",
				"\x1\x47",
				"\xA\x22\x7\xFFFF\x3\x22\x1\x48\x16\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A"+
				"\x22",
				"\xA\x22\x7\xFFFF\x4\x22\x1\x49\x1\x22\x1\x4A\x4\x22\x1\x4B\x6\x22\x1"+
				"\x4C\x7\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\x1\x4E\x8\xFFFF\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A"+
				"\x22",
				"\xA\x1F\x7\xFFFF\x6\x51\x1\xFFFF\x1\x51\x18\xFFFF\x6\x51\x1\xFFFF\x1"+
				"\x51\xF\xFFFF\x1\x4F",
				"\xA\x1F\x7\xFFFF\x6\x51\x1\xFFFF\x1\x51\x18\xFFFF\x6\x51\x1\xFFFF\x1"+
				"\x51",
				"\xA\x2E\x7\xFFFF\x6\x2E\x1\xFFFF\x1\x2D\x18\xFFFF\x6\x2E\x1\xFFFF\x1"+
				"\x2D",
				"",
				"",
				"",
				"\x1\x52\x1\x53\x1\x54\x2\xFFFF\x1\x55\x2\xFFFF\x1\x56\x2\xFFFF\x1\x57"+
				"\x6\xFFFF\x1\x58\x1\x59\x3\xFFFF\x1\x5A",
				"\x1\x5B",
				"\x1\x5C",
				"\x1\x5D",
				"\x1\x5E",
				"\x1\x5F",
				"",
				"\x1\x60",
				"\x1\x61",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x2E\x7\xFFFF\x6\x2E\x1\xFFFF\x1\x2D\x18\xFFFF\x6\x2E\x1\xFFFF\x1"+
				"\x2D",
				"\x1\x62",
				"\xA\x2E\x7\xFFFF\x6\x2E\x1\xFFFF\x1\x2D\xA\xFFFF\x1\x63\xD\xFFFF\x6"+
				"\x2E\x1\xFFFF\x1\x2D",
				"\x1\x64",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\x1\x65",
				"\x1\x66",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\x1\x67",
				"\xA\x22\x7\xFFFF\x6\x22\x1\x68\x13\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A"+
				"\x22",
				"\x1\x69",
				"\x1\x6A",
				"\x1\x6B",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\x1\x6D\x8\xFFFF\x1\x6E",
				"\x1\x6F",
				"\x1\x70",
				"\xA\x2E\x7\xFFFF\x3\x2E\x1\x71\x2\x2E\x1\xFFFF\x1\x2D\x18\xFFFF\x6"+
				"\x2E\x1\xFFFF\x1\x2D",
				"\x1\x72",
				"\x1\x73",
				"\x1\x74",
				"",
				"\x1\x75",
				"\x1\x76",
				"\x1\x77\x1\x78\x1\x79\x2\xFFFF\x1\x7A\x5\xFFFF\x1\x7B\x6\xFFFF\x1\x7C"+
				"\x1\x7D\x3\xFFFF\x1\x7E",
				"\x1\x7F",
				"\x1\x80",
				"\x1\x81",
				"\x1\x82",
				"",
				"",
				"",
				"",
				"",
				"\xA\x22\x7\xFFFF\x11\x22\x1\x83\x8\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A"+
				"\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\x1\x84",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x16\x22\x1\x85\x3\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A"+
				"\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x5\x22\x1\x88\xB\x22\x1\x87\x8\x22\x4\xFFFF\x1\x22"+
				"\x1\xFFFF\x1A\x22",
				"\x1\x89",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\x1\x8D",
				"\x1\x8E",
				"\x1\x8F",
				"\x1\x90\x14\xFFFF\x1\x91",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\x1\x92",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\x1\x95",
				"",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x11\x22\x1\x96\x8\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A"+
				"\x22",
				"\x1\x97",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x2E\x7\xFFFF\x5\x2E\x1\x99\x1\x22\x1\x2D\x9\x22\x1\x98\x8\x22\x4"+
				"\xFFFF\x1\x22\x1\xFFFF\x6\x2E\x1\x22\x1\x2D\x12\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\x1\x9A",
				"\x1\x9B",
				"\xA\x22\x7\xFFFF\x5\x22\x1\x9D\xB\x22\x1\x9C\x8\x22\x4\xFFFF\x1\x22"+
				"\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x5\x22\x1\x9F\xB\x22\x1\x9E\x8\x22\x4\xFFFF\x1\x22"+
				"\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\x1\xA0",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\x1\xA1",
				"\x1\xA2",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\x1\xA3",
				"",
				"",
				"",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"",
				"",
				"\x1\xA9",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x2E\x7\xFFFF\x6\x2E\x1\x22\x1\x2D\x12\x22\x4\xFFFF\x1\x22\x1\xFFFF"+
				"\x6\x2E\x1\x22\x1\x2D\x12\x22",
				"\xA\x22\x7\xFFFF\x5\x22\x1\xAB\xB\x22\x1\xAA\x8\x22\x4\xFFFF\x1\x22"+
				"\x1\xFFFF\x1A\x22",
				"\x1\xAC",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\x1\xAE\x5\xFFFF\x1\xAF",
				"",
				"",
				"",
				"",
				"",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22",
				"\xA\x22\x7\xFFFF\x1A\x22\x4\xFFFF\x1\x22\x1\xFFFF\x1A\x22"
			};

		private static readonly short[] DFA16_eot = DFA.UnpackEncodedString(DFA16_eotS);
		private static readonly short[] DFA16_eof = DFA.UnpackEncodedString(DFA16_eofS);
		private static readonly char[] DFA16_min = DFA.UnpackEncodedStringToUnsignedChars(DFA16_minS);
		private static readonly char[] DFA16_max = DFA.UnpackEncodedStringToUnsignedChars(DFA16_maxS);
		private static readonly short[] DFA16_accept = DFA.UnpackEncodedString(DFA16_acceptS);
		private static readonly short[] DFA16_special = DFA.UnpackEncodedString(DFA16_specialS);
		private static readonly short[][] DFA16_transition;

		static DFA16()
		{
			int numStates = DFA16_transitionS.Length;
			DFA16_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA16_transition[i] = DFA.UnpackEncodedString(DFA16_transitionS[i]);
			}
		}

		public DFA16( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 16;
			this.eot = DFA16_eot;
			this.eof = DFA16_eof;
			this.min = DFA16_min;
			this.max = DFA16_max;
			this.accept = DFA16_accept;
			this.special = DFA16_special;
			this.transition = DFA16_transition;
		}

		public override string Description { get { return "1:1: Tokens : ( T__41 | START | END | BYTE | WORD | RESB | RESW | BASE | EQU | ORG | USE | FINL | REG | INDICE | PLUS | MINUS | STAR | DIV | LPAREN | RPAREN | AT | NUMERAL | F1CODOP | F2CODOP | F34CODOP | NUM | CONSTHEX | HEXSUF | CONSTCAD | ID | CHCONST | HEXCONST | WS );"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}


	#endregion

}
