//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.5.1 C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g 2025-04-21 15:00:12

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591
// CLS compliance checking will not be performed on 'type' because it is not visible from outside this assembly.
#pragma warning disable 3019


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;


using Antlr.Runtime.Tree;
using RewriteRuleITokenStream = Antlr.Runtime.Tree.RewriteRuleTokenStream;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.5.1")]
[System.CLSCompliant(false)]
public partial class Gram_SICXEParser : Antlr.Runtime.Parser
{
	internal static readonly string[] tokenNames = new string[] {
		"<invalid>", "<EOR>", "<DOWN>", "<UP>", "AT", "BASE", "BYTE", "CHCONST", "CONSTCAD", "CONSTHEX", "DIR", "DIV", "END", "EQU", "F1CODOP", "F1_INSTR", "F2CODOP", "F2_INSTR", "F34CODOP", "F34_INSTR", "FINL", "HEXCONST", "HEXSUF", "ID", "INDICE", "INSTR", "LPAREN", "MINUS", "NUM", "NUMERAL", "ORG", "PLUS", "REG", "RESB", "RESW", "RPAREN", "STAR", "START", "USE", "WORD", "WS", "','"
	};
	public const int EOF=-1;
	public const int T__41=41;
	public const int AT=4;
	public const int BASE=5;
	public const int BYTE=6;
	public const int CHCONST=7;
	public const int CONSTCAD=8;
	public const int CONSTHEX=9;
	public const int DIR=10;
	public const int DIV=11;
	public const int END=12;
	public const int EQU=13;
	public const int F1CODOP=14;
	public const int F1_INSTR=15;
	public const int F2CODOP=16;
	public const int F2_INSTR=17;
	public const int F34CODOP=18;
	public const int F34_INSTR=19;
	public const int FINL=20;
	public const int HEXCONST=21;
	public const int HEXSUF=22;
	public const int ID=23;
	public const int INDICE=24;
	public const int INSTR=25;
	public const int LPAREN=26;
	public const int MINUS=27;
	public const int NUM=28;
	public const int NUMERAL=29;
	public const int ORG=30;
	public const int PLUS=31;
	public const int REG=32;
	public const int RESB=33;
	public const int RESW=34;
	public const int RPAREN=35;
	public const int STAR=36;
	public const int START=37;
	public const int USE=38;
	public const int WORD=39;
	public const int WS=40;

	public Gram_SICXEParser(ITokenStream input)
		: this(input, new RecognizerSharedState())
	{
	}
	public Gram_SICXEParser(ITokenStream input, RecognizerSharedState state)
		: base(input, state)
	{
		ITreeAdaptor treeAdaptor = default(ITreeAdaptor);
		CreateTreeAdaptor(ref treeAdaptor);
		TreeAdaptor = treeAdaptor ?? new CommonTreeAdaptor();
		OnCreated();
	}
	// Implement this function in your helper file to use a custom tree adaptor
	partial void CreateTreeAdaptor(ref ITreeAdaptor adaptor);

	private ITreeAdaptor adaptor;

	public ITreeAdaptor TreeAdaptor
	{
		get
		{
			return adaptor;
		}

		set
		{
			this.adaptor = value;
		}
	}

	public override string[] TokenNames { get { return Gram_SICXEParser.tokenNames; } }
	public override string GrammarFileName { get { return "C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g"; } }


	partial void OnCreated();
	partial void EnterRule(string ruleName, int ruleIndex);
	partial void LeaveRule(string ruleName, int ruleIndex);

	#region Rules
	partial void EnterRule_programa();
	partial void LeaveRule_programa();
	// $ANTLR start "programa"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:189:8: public programa : inicio proposiciones fin ( FINL )? EOF ;
	[GrammarRule("programa")]
	public AstParserRuleReturnScope<object, IToken> programa()
	{
		EnterRule_programa();
		EnterRule("programa", 1);
		TraceIn("programa", 1);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken FINL4 = default(IToken);
		IToken EOF5 = default(IToken);
		AstParserRuleReturnScope<object, IToken> inicio1 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> proposiciones2 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> fin3 = default(AstParserRuleReturnScope<object, IToken>);

		object FINL4_tree = default(object);
		object EOF5_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "programa");
		DebugLocation(189, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:190:5: ( inicio proposiciones fin ( FINL )? EOF )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:190:7: inicio proposiciones fin ( FINL )? EOF
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(190, 7);
			PushFollow(Follow._inicio_in_programa1257);
			inicio1=inicio();
			PopFollow();

			adaptor.AddChild(root_0, inicio1.Tree);
			DebugLocation(190, 14);
			PushFollow(Follow._proposiciones_in_programa1259);
			proposiciones2=proposiciones();
			PopFollow();

			adaptor.AddChild(root_0, proposiciones2.Tree);
			DebugLocation(190, 28);
			PushFollow(Follow._fin_in_programa1261);
			fin3=fin();
			PopFollow();

			adaptor.AddChild(root_0, fin3.Tree);
			DebugLocation(190, 32);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:190:32: ( FINL )?
			int alt1=2;
			try { DebugEnterSubRule(1);
			try { DebugEnterDecision(1, false);
			int LA1_1 = input.LA(1);

			if ((LA1_1==FINL))
			{
				alt1 = 1;
			}
			} finally { DebugExitDecision(1); }
			switch (alt1)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:190:33: FINL
				{
				DebugLocation(190, 33);
				FINL4=(IToken)Match(input,FINL,Follow._FINL_in_programa1264); 
				FINL4_tree = (object)adaptor.Create(FINL4);
				adaptor.AddChild(root_0, FINL4_tree);

				}
				break;

			}
			} finally { DebugExitSubRule(1); }

			DebugLocation(190, 40);
			EOF5=(IToken)Match(input,EOF,Follow._EOF_in_programa1268); 
			EOF5_tree = (object)adaptor.Create(EOF5);
			adaptor.AddChild(root_0, EOF5_tree);

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("programa", 1);
			LeaveRule("programa", 1);
			LeaveRule_programa();
		}
		DebugLocation(191, 4);
		} finally { DebugExitRule(GrammarFileName, "programa"); }
		return retval;

	}
	// $ANTLR end "programa"

	partial void EnterRule_inicio();
	partial void LeaveRule_inicio();
	// $ANTLR start "inicio"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:193:1: inicio : ( raiz | proposicion );
	[GrammarRule("inicio")]
	private AstParserRuleReturnScope<object, IToken> inicio()
	{
		EnterRule_inicio();
		EnterRule("inicio", 2);
		TraceIn("inicio", 2);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		AstParserRuleReturnScope<object, IToken> raiz6 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> proposicion7 = default(AstParserRuleReturnScope<object, IToken>);

		try { DebugEnterRule(GrammarFileName, "inicio");
		DebugLocation(193, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:194:5: ( raiz | proposicion )
			int alt2=2;
			try { DebugEnterDecision(2, false);
			int LA2_1 = input.LA(1);

			if ((LA2_1==ID))
			{
				int LA2_2 = input.LA(2);

				if ((LA2_2==START))
				{
					alt2 = 1;
				}
				else if (((LA2_2>=BASE && LA2_2<=BYTE)||(LA2_2>=EQU && LA2_2<=F1CODOP)||LA2_2==F2CODOP||LA2_2==F34CODOP||(LA2_2>=ORG && LA2_2<=PLUS)||(LA2_2>=RESB && LA2_2<=RESW)||(LA2_2>=USE && LA2_2<=WORD)))
				{
					alt2 = 2;
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 2, 1, input, 2);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}
			else if (((LA2_1>=BASE && LA2_1<=BYTE)||(LA2_1>=EQU && LA2_1<=F1CODOP)||LA2_1==F2CODOP||LA2_1==F34CODOP||(LA2_1>=ORG && LA2_1<=PLUS)||(LA2_1>=RESB && LA2_1<=RESW)||(LA2_1>=USE && LA2_1<=WORD)))
			{
				alt2 = 2;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 2, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(2); }
			switch (alt2)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:194:7: raiz
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(194, 7);
				PushFollow(Follow._raiz_in_inicio1285);
				raiz6=raiz();
				PopFollow();

				adaptor.AddChild(root_0, raiz6.Tree);

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:195:7: proposicion
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(195, 7);
				PushFollow(Follow._proposicion_in_inicio1293);
				proposicion7=proposicion();
				PopFollow();

				adaptor.AddChild(root_0, proposicion7.Tree);

				}
				break;

			}
			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("inicio", 2);
			LeaveRule("inicio", 2);
			LeaveRule_inicio();
		}
		DebugLocation(196, 4);
		} finally { DebugExitRule(GrammarFileName, "inicio"); }
		return retval;

	}
	// $ANTLR end "inicio"

	partial void EnterRule_raiz();
	partial void LeaveRule_raiz();
	// $ANTLR start "raiz"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:199:1: raiz : et= etiqueta s= START v= ( NUM | HEXSUF )? FINL -> ^( DIR $et $s ( $v)? ) ;
	[GrammarRule("raiz")]
	private AstParserRuleReturnScope<object, IToken> raiz()
	{
		EnterRule_raiz();
		EnterRule("raiz", 3);
		TraceIn("raiz", 3);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken s = default(IToken);
		IToken v = default(IToken);
		IToken FINL8 = default(IToken);
		AstParserRuleReturnScope<object, IToken> et = default(AstParserRuleReturnScope<object, IToken>);

		object s_tree = default(object);
		object v_tree = default(object);
		object FINL8_tree = default(object);
		RewriteRuleITokenStream stream_FINL=new RewriteRuleITokenStream(adaptor,"token FINL");
		RewriteRuleITokenStream stream_NUM=new RewriteRuleITokenStream(adaptor,"token NUM");
		RewriteRuleITokenStream stream_START=new RewriteRuleITokenStream(adaptor,"token START");
		RewriteRuleITokenStream stream_HEXSUF=new RewriteRuleITokenStream(adaptor,"token HEXSUF");
		RewriteRuleSubtreeStream stream_etiqueta=new RewriteRuleSubtreeStream(adaptor,"rule etiqueta");
		try { DebugEnterRule(GrammarFileName, "raiz");
		DebugLocation(199, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:200:5: (et= etiqueta s= START v= ( NUM | HEXSUF )? FINL -> ^( DIR $et $s ( $v)? ) )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:200:7: et= etiqueta s= START v= ( NUM | HEXSUF )? FINL
			{
			DebugLocation(200, 9);
			PushFollow(Follow._etiqueta_in_raiz1313);
			et=etiqueta();
			PopFollow();

			stream_etiqueta.Add(et.Tree);
			DebugLocation(200, 20);
			s=(IToken)Match(input,START,Follow._START_in_raiz1317);  
			stream_START.Add(s);

			DebugLocation(200, 28);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:200:29: ( NUM | HEXSUF )?
			int alt3=3;
			try { DebugEnterSubRule(3);
			try { DebugEnterDecision(3, false);
			int LA3_1 = input.LA(1);

			if ((LA3_1==NUM))
			{
				alt3 = 1;
			}
			else if ((LA3_1==HEXSUF))
			{
				alt3 = 2;
			}
			} finally { DebugExitDecision(3); }
			switch (alt3)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:200:30: NUM
				{
				DebugLocation(200, 30);
				v=(IToken)Match(input,NUM,Follow._NUM_in_raiz1322);  
				stream_NUM.Add(v);


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:200:36: HEXSUF
				{
				DebugLocation(200, 36);
				v=(IToken)Match(input,HEXSUF,Follow._HEXSUF_in_raiz1326);  
				stream_HEXSUF.Add(v);


				}
				break;

			}
			} finally { DebugExitSubRule(3); }

			DebugLocation(200, 45);
			FINL8=(IToken)Match(input,FINL,Follow._FINL_in_raiz1330);  
			stream_FINL.Add(FINL8);



			{
			// AST REWRITE
			// elements: et, v, s
			// token labels: s, v
			// rule labels: retval, et
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleITokenStream stream_s=new RewriteRuleITokenStream(adaptor,"token s",s);
			RewriteRuleITokenStream stream_v=new RewriteRuleITokenStream(adaptor,"token v",v);
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);
			RewriteRuleSubtreeStream stream_et=new RewriteRuleSubtreeStream(adaptor,"rule et",et!=null?et.Tree:null);

			root_0 = (object)adaptor.Nil();
			// 201:7: -> ^( DIR $et $s ( $v)? )
			{
				DebugLocation(201, 10);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:201:10: ^( DIR $et $s ( $v)? )
				{
				object root_1 = (object)adaptor.Nil();
				DebugLocation(201, 12);
				root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(DIR, "DIR"), root_1);

				DebugLocation(201, 17);
				adaptor.AddChild(root_1, stream_et.NextTree());
				DebugLocation(201, 21);
				adaptor.AddChild(root_1, stream_s.NextNode());
				DebugLocation(201, 24);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:201:24: ( $v)?
				if (stream_v.HasNext)
				{
					DebugLocation(201, 24);
					adaptor.AddChild(root_1, stream_v.NextNode());

				}
				stream_v.Reset();

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("raiz", 3);
			LeaveRule("raiz", 3);
			LeaveRule_raiz();
		}
		DebugLocation(202, 4);
		} finally { DebugExitRule(GrammarFileName, "raiz"); }
		return retval;

	}
	// $ANTLR end "raiz"

	partial void EnterRule_fin();
	partial void LeaveRule_fin();
	// $ANTLR start "fin"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:205:1: fin : e= END ent= entrada ( FINL )? -> ^( INSTR $e ( $ent)? ) ;
	[GrammarRule("fin")]
	private AstParserRuleReturnScope<object, IToken> fin()
	{
		EnterRule_fin();
		EnterRule("fin", 4);
		TraceIn("fin", 4);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken e = default(IToken);
		IToken FINL9 = default(IToken);
		AstParserRuleReturnScope<object, IToken> ent = default(AstParserRuleReturnScope<object, IToken>);

		object e_tree = default(object);
		object FINL9_tree = default(object);
		RewriteRuleITokenStream stream_FINL=new RewriteRuleITokenStream(adaptor,"token FINL");
		RewriteRuleITokenStream stream_END=new RewriteRuleITokenStream(adaptor,"token END");
		RewriteRuleSubtreeStream stream_entrada=new RewriteRuleSubtreeStream(adaptor,"rule entrada");
		try { DebugEnterRule(GrammarFileName, "fin");
		DebugLocation(205, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:206:5: (e= END ent= entrada ( FINL )? -> ^( INSTR $e ( $ent)? ) )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:206:7: e= END ent= entrada ( FINL )?
			{
			DebugLocation(206, 8);
			e=(IToken)Match(input,END,Follow._END_in_fin1372);  
			stream_END.Add(e);

			DebugLocation(206, 16);
			PushFollow(Follow._entrada_in_fin1376);
			ent=entrada();
			PopFollow();

			stream_entrada.Add(ent.Tree);
			DebugLocation(206, 25);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:206:25: ( FINL )?
			int alt4=2;
			try { DebugEnterSubRule(4);
			try { DebugEnterDecision(4, false);
			int LA4_1 = input.LA(1);

			if ((LA4_1==FINL))
			{
				alt4 = 1;
			}
			} finally { DebugExitDecision(4); }
			switch (alt4)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:206:26: FINL
				{
				DebugLocation(206, 26);
				FINL9=(IToken)Match(input,FINL,Follow._FINL_in_fin1379);  
				stream_FINL.Add(FINL9);


				}
				break;

			}
			} finally { DebugExitSubRule(4); }



			{
			// AST REWRITE
			// elements: e, ent
			// token labels: e
			// rule labels: ent, retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleITokenStream stream_e=new RewriteRuleITokenStream(adaptor,"token e",e);
			RewriteRuleSubtreeStream stream_ent=new RewriteRuleSubtreeStream(adaptor,"rule ent",ent!=null?ent.Tree:null);
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (object)adaptor.Nil();
			// 207:7: -> ^( INSTR $e ( $ent)? )
			{
				DebugLocation(207, 10);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:207:10: ^( INSTR $e ( $ent)? )
				{
				object root_1 = (object)adaptor.Nil();
				DebugLocation(207, 12);
				root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(INSTR, "INSTR"), root_1);

				DebugLocation(207, 19);
				adaptor.AddChild(root_1, stream_e.NextNode());
				DebugLocation(207, 22);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:207:22: ( $ent)?
				if (stream_ent.HasNext)
				{
					DebugLocation(207, 22);
					adaptor.AddChild(root_1, stream_ent.NextTree());

				}
				stream_ent.Reset();

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("fin", 4);
			LeaveRule("fin", 4);
			LeaveRule_fin();
		}
		DebugLocation(208, 4);
		} finally { DebugExitRule(GrammarFileName, "fin"); }
		return retval;

	}
	// $ANTLR end "fin"

	partial void EnterRule_entrada();
	partial void LeaveRule_entrada();
	// $ANTLR start "entrada"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:210:1: entrada : ( ID )? ;
	[GrammarRule("entrada")]
	private AstParserRuleReturnScope<object, IToken> entrada()
	{
		EnterRule_entrada();
		EnterRule("entrada", 5);
		TraceIn("entrada", 5);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken ID10 = default(IToken);

		object ID10_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "entrada");
		DebugLocation(210, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:211:5: ( ( ID )? )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:211:7: ( ID )?
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(211, 7);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:211:7: ( ID )?
			int alt5=2;
			try { DebugEnterSubRule(5);
			try { DebugEnterDecision(5, false);
			int LA5_1 = input.LA(1);

			if ((LA5_1==ID))
			{
				alt5 = 1;
			}
			} finally { DebugExitDecision(5); }
			switch (alt5)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:211:7: ID
				{
				DebugLocation(211, 7);
				ID10=(IToken)Match(input,ID,Follow._ID_in_entrada1417); 
				ID10_tree = (object)adaptor.Create(ID10);
				adaptor.AddChild(root_0, ID10_tree);

				}
				break;

			}
			} finally { DebugExitSubRule(5); }


			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("entrada", 5);
			LeaveRule("entrada", 5);
			LeaveRule_entrada();
		}
		DebugLocation(212, 4);
		} finally { DebugExitRule(GrammarFileName, "entrada"); }
		return retval;

	}
	// $ANTLR end "entrada"

	partial void EnterRule_proposiciones();
	partial void LeaveRule_proposiciones();
	// $ANTLR start "proposiciones"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:215:1: proposiciones : ( proposicion )+ ;
	[GrammarRule("proposiciones")]
	private AstParserRuleReturnScope<object, IToken> proposiciones()
	{
		EnterRule_proposiciones();
		EnterRule("proposiciones", 6);
		TraceIn("proposiciones", 6);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		AstParserRuleReturnScope<object, IToken> proposicion11 = default(AstParserRuleReturnScope<object, IToken>);

		try { DebugEnterRule(GrammarFileName, "proposiciones");
		DebugLocation(215, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:216:5: ( ( proposicion )+ )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:216:7: ( proposicion )+
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(216, 7);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:216:7: ( proposicion )+
			int cnt6=0;
			try { DebugEnterSubRule(6);
			while (true)
			{
				int alt6=2;
				try { DebugEnterDecision(6, false);
				int LA6_1 = input.LA(1);

				if (((LA6_1>=BASE && LA6_1<=BYTE)||(LA6_1>=EQU && LA6_1<=F1CODOP)||LA6_1==F2CODOP||LA6_1==F34CODOP||LA6_1==ID||(LA6_1>=ORG && LA6_1<=PLUS)||(LA6_1>=RESB && LA6_1<=RESW)||(LA6_1>=USE && LA6_1<=WORD)))
				{
					alt6 = 1;
				}


				} finally { DebugExitDecision(6); }
				switch (alt6)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:216:8: proposicion
					{
					DebugLocation(216, 8);
					PushFollow(Follow._proposicion_in_proposiciones1437);
					proposicion11=proposicion();
					PopFollow();

					adaptor.AddChild(root_0, proposicion11.Tree);

					}
					break;

				default:
					if (cnt6 >= 1)
						goto loop6;

					EarlyExitException eee6 = new EarlyExitException( 6, input );
					DebugRecognitionException(eee6);
					throw eee6;
				}
				cnt6++;
			}
			loop6:
				;

			} finally { DebugExitSubRule(6); }


			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("proposiciones", 6);
			LeaveRule("proposiciones", 6);
			LeaveRule_proposiciones();
		}
		DebugLocation(217, 4);
		} finally { DebugExitRule(GrammarFileName, "proposiciones"); }
		return retval;

	}
	// $ANTLR end "proposiciones"

	partial void EnterRule_proposicion();
	partial void LeaveRule_proposicion();
	// $ANTLR start "proposicion"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:220:1: proposicion : ( instruccion | directiva );
	[GrammarRule("proposicion")]
	private AstParserRuleReturnScope<object, IToken> proposicion()
	{
		EnterRule_proposicion();
		EnterRule("proposicion", 7);
		TraceIn("proposicion", 7);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		AstParserRuleReturnScope<object, IToken> instruccion12 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> directiva13 = default(AstParserRuleReturnScope<object, IToken>);

		try { DebugEnterRule(GrammarFileName, "proposicion");
		DebugLocation(220, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:221:5: ( instruccion | directiva )
			int alt7=2;
			try { DebugEnterDecision(7, false);
			switch (input.LA(1))
			{
			case ID:
				{
				int LA7_2 = input.LA(2);

				if ((LA7_2==F1CODOP||LA7_2==F2CODOP||LA7_2==F34CODOP||LA7_2==PLUS))
				{
					alt7 = 1;
				}
				else if (((LA7_2>=BASE && LA7_2<=BYTE)||LA7_2==EQU||LA7_2==ORG||(LA7_2>=RESB && LA7_2<=RESW)||(LA7_2>=USE && LA7_2<=WORD)))
				{
					alt7 = 2;
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 7, 1, input, 2);
					DebugRecognitionException(nvae);
					throw nvae;
				}
				}
				break;
			case F1CODOP:
			case F2CODOP:
			case F34CODOP:
			case PLUS:
				{
				alt7 = 1;
				}
				break;
			case BASE:
			case BYTE:
			case EQU:
			case ORG:
			case RESB:
			case RESW:
			case USE:
			case WORD:
				{
				alt7 = 2;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 7, 0, input, 1);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(7); }
			switch (alt7)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:221:7: instruccion
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(221, 7);
				PushFollow(Follow._instruccion_in_proposicion1457);
				instruccion12=instruccion();
				PopFollow();

				adaptor.AddChild(root_0, instruccion12.Tree);

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:222:7: directiva
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(222, 7);
				PushFollow(Follow._directiva_in_proposicion1465);
				directiva13=directiva();
				PopFollow();

				adaptor.AddChild(root_0, directiva13.Tree);

				}
				break;

			}
			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("proposicion", 7);
			LeaveRule("proposicion", 7);
			LeaveRule_proposicion();
		}
		DebugLocation(223, 4);
		} finally { DebugExitRule(GrammarFileName, "proposicion"); }
		return retval;

	}
	// $ANTLR end "proposicion"

	partial void EnterRule_instruccion();
	partial void LeaveRule_instruccion();
	// $ANTLR start "instruccion"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:228:1: instruccion : ( etiqueta )? opinstruccion FINL -> ^( INSTR ( etiqueta )? opinstruccion ) ;
	[GrammarRule("instruccion")]
	private AstParserRuleReturnScope<object, IToken> instruccion()
	{
		EnterRule_instruccion();
		EnterRule("instruccion", 8);
		TraceIn("instruccion", 8);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken FINL16 = default(IToken);
		AstParserRuleReturnScope<object, IToken> etiqueta14 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> opinstruccion15 = default(AstParserRuleReturnScope<object, IToken>);

		object FINL16_tree = default(object);
		RewriteRuleITokenStream stream_FINL=new RewriteRuleITokenStream(adaptor,"token FINL");
		RewriteRuleSubtreeStream stream_etiqueta=new RewriteRuleSubtreeStream(adaptor,"rule etiqueta");
		RewriteRuleSubtreeStream stream_opinstruccion=new RewriteRuleSubtreeStream(adaptor,"rule opinstruccion");
		try { DebugEnterRule(GrammarFileName, "instruccion");
		DebugLocation(228, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:229:5: ( ( etiqueta )? opinstruccion FINL -> ^( INSTR ( etiqueta )? opinstruccion ) )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:229:7: ( etiqueta )? opinstruccion FINL
			{
			DebugLocation(229, 7);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:229:7: ( etiqueta )?
			int alt8=2;
			try { DebugEnterSubRule(8);
			try { DebugEnterDecision(8, false);
			int LA8_1 = input.LA(1);

			if ((LA8_1==ID))
			{
				alt8 = 1;
			}
			} finally { DebugExitDecision(8); }
			switch (alt8)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:229:7: etiqueta
				{
				DebugLocation(229, 7);
				PushFollow(Follow._etiqueta_in_instruccion1485);
				etiqueta14=etiqueta();
				PopFollow();

				stream_etiqueta.Add(etiqueta14.Tree);

				}
				break;

			}
			} finally { DebugExitSubRule(8); }

			DebugLocation(229, 17);
			PushFollow(Follow._opinstruccion_in_instruccion1488);
			opinstruccion15=opinstruccion();
			PopFollow();

			stream_opinstruccion.Add(opinstruccion15.Tree);
			DebugLocation(229, 31);
			FINL16=(IToken)Match(input,FINL,Follow._FINL_in_instruccion1490);  
			stream_FINL.Add(FINL16);



			{
			// AST REWRITE
			// elements: etiqueta, opinstruccion
			// token labels: 
			// rule labels: retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (object)adaptor.Nil();
			// 230:7: -> ^( INSTR ( etiqueta )? opinstruccion )
			{
				DebugLocation(230, 10);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:230:10: ^( INSTR ( etiqueta )? opinstruccion )
				{
				object root_1 = (object)adaptor.Nil();
				DebugLocation(230, 12);
				root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(INSTR, "INSTR"), root_1);

				DebugLocation(230, 18);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:230:18: ( etiqueta )?
				if (stream_etiqueta.HasNext)
				{
					DebugLocation(230, 19);
					adaptor.AddChild(root_1, stream_etiqueta.NextTree());

				}
				stream_etiqueta.Reset();
				DebugLocation(230, 30);
				adaptor.AddChild(root_1, stream_opinstruccion.NextTree());

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("instruccion", 8);
			LeaveRule("instruccion", 8);
			LeaveRule_instruccion();
		}
		DebugLocation(231, 4);
		} finally { DebugExitRule(GrammarFileName, "instruccion"); }
		return retval;

	}
	// $ANTLR end "instruccion"

	partial void EnterRule_opinstruccion();
	partial void LeaveRule_opinstruccion();
	// $ANTLR start "opinstruccion"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:233:1: opinstruccion : formato ;
	[GrammarRule("opinstruccion")]
	private AstParserRuleReturnScope<object, IToken> opinstruccion()
	{
		EnterRule_opinstruccion();
		EnterRule("opinstruccion", 9);
		TraceIn("opinstruccion", 9);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		AstParserRuleReturnScope<object, IToken> formato17 = default(AstParserRuleReturnScope<object, IToken>);

		try { DebugEnterRule(GrammarFileName, "opinstruccion");
		DebugLocation(233, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:234:5: ( formato )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:234:7: formato
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(234, 7);
			PushFollow(Follow._formato_in_opinstruccion1526);
			formato17=formato();
			PopFollow();

			adaptor.AddChild(root_0, formato17.Tree);

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("opinstruccion", 9);
			LeaveRule("opinstruccion", 9);
			LeaveRule_opinstruccion();
		}
		DebugLocation(235, 4);
		} finally { DebugExitRule(GrammarFileName, "opinstruccion"); }
		return retval;

	}
	// $ANTLR end "opinstruccion"

	partial void EnterRule_formato();
	partial void LeaveRule_formato();
	// $ANTLR start "formato"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:237:1: formato : ( f1 | f2 | f3 | f4 | indexado );
	[GrammarRule("formato")]
	private AstParserRuleReturnScope<object, IToken> formato()
	{
		EnterRule_formato();
		EnterRule("formato", 10);
		TraceIn("formato", 10);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		AstParserRuleReturnScope<object, IToken> f118 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> f219 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> f320 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> f421 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> indexado22 = default(AstParserRuleReturnScope<object, IToken>);

		try { DebugEnterRule(GrammarFileName, "formato");
		DebugLocation(237, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:238:5: ( f1 | f2 | f3 | f4 | indexado )
			int alt9=5;
			try { DebugEnterDecision(9, false);
			switch (input.LA(1))
			{
			case F1CODOP:
				{
				alt9 = 1;
				}
				break;
			case F2CODOP:
				{
				alt9 = 2;
				}
				break;
			case F34CODOP:
				{
				int LA9_2 = input.LA(2);

				if ((LA9_2==AT||(LA9_2>=CHCONST && LA9_2<=CONSTHEX)||(LA9_2>=FINL && LA9_2<=ID)||LA9_2==LPAREN||(LA9_2>=NUM && LA9_2<=NUMERAL)||LA9_2==STAR||LA9_2==41))
				{
					alt9 = 3;
				}
				else if ((LA9_2==INDICE))
				{
					alt9 = 5;
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 9, 3, input, 2);
					DebugRecognitionException(nvae);
					throw nvae;
				}
				}
				break;
			case PLUS:
				{
				alt9 = 4;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 9, 0, input, 1);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(9); }
			switch (alt9)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:238:7: f1
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(238, 7);
				PushFollow(Follow._f1_in_formato1543);
				f118=f1();
				PopFollow();

				adaptor.AddChild(root_0, f118.Tree);

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:239:7: f2
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(239, 7);
				PushFollow(Follow._f2_in_formato1551);
				f219=f2();
				PopFollow();

				adaptor.AddChild(root_0, f219.Tree);

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:240:7: f3
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(240, 7);
				PushFollow(Follow._f3_in_formato1559);
				f320=f3();
				PopFollow();

				adaptor.AddChild(root_0, f320.Tree);

				}
				break;
			case 4:
				DebugEnterAlt(4);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:241:7: f4
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(241, 7);
				PushFollow(Follow._f4_in_formato1567);
				f421=f4();
				PopFollow();

				adaptor.AddChild(root_0, f421.Tree);

				}
				break;
			case 5:
				DebugEnterAlt(5);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:242:7: indexado
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(242, 7);
				PushFollow(Follow._indexado_in_formato1575);
				indexado22=indexado();
				PopFollow();

				adaptor.AddChild(root_0, indexado22.Tree);

				}
				break;

			}
			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("formato", 10);
			LeaveRule("formato", 10);
			LeaveRule_formato();
		}
		DebugLocation(243, 4);
		} finally { DebugExitRule(GrammarFileName, "formato"); }
		return retval;

	}
	// $ANTLR end "formato"

	partial void EnterRule_f1();
	partial void LeaveRule_f1();
	// $ANTLR start "f1"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:246:1: f1 : F1CODOP ;
	[GrammarRule("f1")]
	private AstParserRuleReturnScope<object, IToken> f1()
	{
		EnterRule_f1();
		EnterRule("f1", 11);
		TraceIn("f1", 11);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken F1CODOP23 = default(IToken);

		object F1CODOP23_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "f1");
		DebugLocation(246, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:247:5: ( F1CODOP )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:247:7: F1CODOP
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(247, 7);
			F1CODOP23=(IToken)Match(input,F1CODOP,Follow._F1CODOP_in_f11593); 
			F1CODOP23_tree = (object)adaptor.Create(F1CODOP23);
			adaptor.AddChild(root_0, F1CODOP23_tree);

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("f1", 11);
			LeaveRule("f1", 11);
			LeaveRule_f1();
		}
		DebugLocation(248, 4);
		} finally { DebugExitRule(GrammarFileName, "f1"); }
		return retval;

	}
	// $ANTLR end "f1"

	partial void EnterRule_f2();
	partial void LeaveRule_f2();
	// $ANTLR start "f2"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:251:1: f2 : ( F2CODOP REG | F2CODOP REG ',' REG | F2CODOP REG ',' NUM );
	[GrammarRule("f2")]
	private AstParserRuleReturnScope<object, IToken> f2()
	{
		EnterRule_f2();
		EnterRule("f2", 12);
		TraceIn("f2", 12);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken F2CODOP24 = default(IToken);
		IToken REG25 = default(IToken);
		IToken F2CODOP26 = default(IToken);
		IToken REG27 = default(IToken);
		IToken char_literal28 = default(IToken);
		IToken REG29 = default(IToken);
		IToken F2CODOP30 = default(IToken);
		IToken REG31 = default(IToken);
		IToken char_literal32 = default(IToken);
		IToken NUM33 = default(IToken);

		object F2CODOP24_tree = default(object);
		object REG25_tree = default(object);
		object F2CODOP26_tree = default(object);
		object REG27_tree = default(object);
		object char_literal28_tree = default(object);
		object REG29_tree = default(object);
		object F2CODOP30_tree = default(object);
		object REG31_tree = default(object);
		object char_literal32_tree = default(object);
		object NUM33_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "f2");
		DebugLocation(251, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:252:5: ( F2CODOP REG | F2CODOP REG ',' REG | F2CODOP REG ',' NUM )
			int alt10=3;
			try { DebugEnterDecision(10, false);
			int LA10_1 = input.LA(1);

			if ((LA10_1==F2CODOP))
			{
				int LA10_2 = input.LA(2);

				if ((LA10_2==REG))
				{
					int LA10_3 = input.LA(3);

					if ((LA10_3==41))
					{
						int LA10_4 = input.LA(4);

						if ((LA10_4==REG))
						{
							alt10 = 2;
						}
						else if ((LA10_4==NUM))
						{
							alt10 = 3;
						}
						else
						{
							NoViableAltException nvae = new NoViableAltException("", 10, 3, input, 4);
							DebugRecognitionException(nvae);
							throw nvae;
						}
					}
					else if ((LA10_3==FINL))
					{
						alt10 = 1;
					}
					else
					{
						NoViableAltException nvae = new NoViableAltException("", 10, 2, input, 3);
						DebugRecognitionException(nvae);
						throw nvae;
					}
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 10, 1, input, 2);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 10, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(10); }
			switch (alt10)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:252:7: F2CODOP REG
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(252, 7);
				F2CODOP24=(IToken)Match(input,F2CODOP,Follow._F2CODOP_in_f21611); 
				F2CODOP24_tree = (object)adaptor.Create(F2CODOP24);
				adaptor.AddChild(root_0, F2CODOP24_tree);
				DebugLocation(252, 15);
				REG25=(IToken)Match(input,REG,Follow._REG_in_f21613); 
				REG25_tree = (object)adaptor.Create(REG25);
				adaptor.AddChild(root_0, REG25_tree);

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:253:7: F2CODOP REG ',' REG
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(253, 7);
				F2CODOP26=(IToken)Match(input,F2CODOP,Follow._F2CODOP_in_f21621); 
				F2CODOP26_tree = (object)adaptor.Create(F2CODOP26);
				adaptor.AddChild(root_0, F2CODOP26_tree);
				DebugLocation(253, 15);
				REG27=(IToken)Match(input,REG,Follow._REG_in_f21623); 
				REG27_tree = (object)adaptor.Create(REG27);
				adaptor.AddChild(root_0, REG27_tree);
				DebugLocation(253, 19);
				char_literal28=(IToken)Match(input,41,Follow._41_in_f21625); 
				char_literal28_tree = (object)adaptor.Create(char_literal28);
				adaptor.AddChild(root_0, char_literal28_tree);
				DebugLocation(253, 23);
				REG29=(IToken)Match(input,REG,Follow._REG_in_f21627); 
				REG29_tree = (object)adaptor.Create(REG29);
				adaptor.AddChild(root_0, REG29_tree);

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:254:7: F2CODOP REG ',' NUM
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(254, 7);
				F2CODOP30=(IToken)Match(input,F2CODOP,Follow._F2CODOP_in_f21635); 
				F2CODOP30_tree = (object)adaptor.Create(F2CODOP30);
				adaptor.AddChild(root_0, F2CODOP30_tree);
				DebugLocation(254, 15);
				REG31=(IToken)Match(input,REG,Follow._REG_in_f21637); 
				REG31_tree = (object)adaptor.Create(REG31);
				adaptor.AddChild(root_0, REG31_tree);
				DebugLocation(254, 19);
				char_literal32=(IToken)Match(input,41,Follow._41_in_f21639); 
				char_literal32_tree = (object)adaptor.Create(char_literal32);
				adaptor.AddChild(root_0, char_literal32_tree);
				DebugLocation(254, 23);
				NUM33=(IToken)Match(input,NUM,Follow._NUM_in_f21641); 
				NUM33_tree = (object)adaptor.Create(NUM33);
				adaptor.AddChild(root_0, NUM33_tree);

				}
				break;

			}
			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("f2", 12);
			LeaveRule("f2", 12);
			LeaveRule_f2();
		}
		DebugLocation(255, 4);
		} finally { DebugExitRule(GrammarFileName, "f2"); }
		return retval;

	}
	// $ANTLR end "f2"

	partial void EnterRule_f3();
	partial void LeaveRule_f3();
	// $ANTLR start "f3"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:258:1: f3 : ( simple3 | indirecto3 | inmediato3 );
	[GrammarRule("f3")]
	private AstParserRuleReturnScope<object, IToken> f3()
	{
		EnterRule_f3();
		EnterRule("f3", 13);
		TraceIn("f3", 13);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		AstParserRuleReturnScope<object, IToken> simple334 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> indirecto335 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> inmediato336 = default(AstParserRuleReturnScope<object, IToken>);

		try { DebugEnterRule(GrammarFileName, "f3");
		DebugLocation(258, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:259:5: ( simple3 | indirecto3 | inmediato3 )
			int alt11=3;
			try { DebugEnterDecision(11, false);
			int LA11_1 = input.LA(1);

			if ((LA11_1==F34CODOP))
			{
				switch (input.LA(2))
				{
				case AT:
					{
					alt11 = 2;
					}
					break;
				case NUMERAL:
					{
					alt11 = 3;
					}
					break;
				case CHCONST:
				case CONSTCAD:
				case CONSTHEX:
				case FINL:
				case HEXCONST:
				case HEXSUF:
				case ID:
				case LPAREN:
				case NUM:
				case STAR:
				case 41:
					{
					alt11 = 1;
					}
					break;
				default:
					{
						NoViableAltException nvae = new NoViableAltException("", 11, 1, input, 2);
						DebugRecognitionException(nvae);
						throw nvae;
					}
				}

			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 11, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(11); }
			switch (alt11)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:259:7: simple3
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(259, 7);
				PushFollow(Follow._simple3_in_f31659);
				simple334=simple3();
				PopFollow();

				adaptor.AddChild(root_0, simple334.Tree);

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:260:7: indirecto3
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(260, 7);
				PushFollow(Follow._indirecto3_in_f31667);
				indirecto335=indirecto3();
				PopFollow();

				adaptor.AddChild(root_0, indirecto335.Tree);

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:261:7: inmediato3
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(261, 7);
				PushFollow(Follow._inmediato3_in_f31675);
				inmediato336=inmediato3();
				PopFollow();

				adaptor.AddChild(root_0, inmediato336.Tree);

				}
				break;

			}
			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("f3", 13);
			LeaveRule("f3", 13);
			LeaveRule_f3();
		}
		DebugLocation(262, 4);
		} finally { DebugExitRule(GrammarFileName, "f3"); }
		return retval;

	}
	// $ANTLR end "f3"

	partial void EnterRule_f4();
	partial void LeaveRule_f4();
	// $ANTLR start "f4"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:265:1: f4 : PLUS f3 ;
	[GrammarRule("f4")]
	private AstParserRuleReturnScope<object, IToken> f4()
	{
		EnterRule_f4();
		EnterRule("f4", 14);
		TraceIn("f4", 14);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken PLUS37 = default(IToken);
		AstParserRuleReturnScope<object, IToken> f338 = default(AstParserRuleReturnScope<object, IToken>);

		object PLUS37_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "f4");
		DebugLocation(265, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:266:5: ( PLUS f3 )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:266:7: PLUS f3
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(266, 7);
			PLUS37=(IToken)Match(input,PLUS,Follow._PLUS_in_f41693); 
			PLUS37_tree = (object)adaptor.Create(PLUS37);
			adaptor.AddChild(root_0, PLUS37_tree);
			DebugLocation(266, 12);
			PushFollow(Follow._f3_in_f41695);
			f338=f3();
			PopFollow();

			adaptor.AddChild(root_0, f338.Tree);

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("f4", 14);
			LeaveRule("f4", 14);
			LeaveRule_f4();
		}
		DebugLocation(267, 4);
		} finally { DebugExitRule(GrammarFileName, "f4"); }
		return retval;

	}
	// $ANTLR end "f4"

	partial void EnterRule_indexado();
	partial void LeaveRule_indexado();
	// $ANTLR start "indexado"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:270:1: indexado : F34CODOP INDICE ;
	[GrammarRule("indexado")]
	private AstParserRuleReturnScope<object, IToken> indexado()
	{
		EnterRule_indexado();
		EnterRule("indexado", 15);
		TraceIn("indexado", 15);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken F34CODOP39 = default(IToken);
		IToken INDICE40 = default(IToken);

		object F34CODOP39_tree = default(object);
		object INDICE40_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "indexado");
		DebugLocation(270, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:271:5: ( F34CODOP INDICE )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:271:7: F34CODOP INDICE
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(271, 7);
			F34CODOP39=(IToken)Match(input,F34CODOP,Follow._F34CODOP_in_indexado1713); 
			F34CODOP39_tree = (object)adaptor.Create(F34CODOP39);
			adaptor.AddChild(root_0, F34CODOP39_tree);
			DebugLocation(271, 16);
			INDICE40=(IToken)Match(input,INDICE,Follow._INDICE_in_indexado1715); 
			INDICE40_tree = (object)adaptor.Create(INDICE40);
			adaptor.AddChild(root_0, INDICE40_tree);

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("indexado", 15);
			LeaveRule("indexado", 15);
			LeaveRule_indexado();
		}
		DebugLocation(272, 4);
		} finally { DebugExitRule(GrammarFileName, "indexado"); }
		return retval;

	}
	// $ANTLR end "indexado"

	partial void EnterRule_simple3();
	partial void LeaveRule_simple3();
	// $ANTLR start "simple3"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:275:1: simple3 : F34CODOP ( expresion )? ( ',' REG )? ;
	[GrammarRule("simple3")]
	private AstParserRuleReturnScope<object, IToken> simple3()
	{
		EnterRule_simple3();
		EnterRule("simple3", 16);
		TraceIn("simple3", 16);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken F34CODOP41 = default(IToken);
		IToken char_literal43 = default(IToken);
		IToken REG44 = default(IToken);
		AstParserRuleReturnScope<object, IToken> expresion42 = default(AstParserRuleReturnScope<object, IToken>);

		object F34CODOP41_tree = default(object);
		object char_literal43_tree = default(object);
		object REG44_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "simple3");
		DebugLocation(275, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:276:5: ( F34CODOP ( expresion )? ( ',' REG )? )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:276:7: F34CODOP ( expresion )? ( ',' REG )?
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(276, 7);
			F34CODOP41=(IToken)Match(input,F34CODOP,Follow._F34CODOP_in_simple31733); 
			F34CODOP41_tree = (object)adaptor.Create(F34CODOP41);
			adaptor.AddChild(root_0, F34CODOP41_tree);
			DebugLocation(276, 16);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:276:16: ( expresion )?
			int alt12=2;
			try { DebugEnterSubRule(12);
			try { DebugEnterDecision(12, false);
			int LA12_1 = input.LA(1);

			if (((LA12_1>=CHCONST && LA12_1<=CONSTHEX)||(LA12_1>=HEXCONST && LA12_1<=ID)||LA12_1==LPAREN||LA12_1==NUM||LA12_1==STAR))
			{
				alt12 = 1;
			}
			} finally { DebugExitDecision(12); }
			switch (alt12)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:276:17: expresion
				{
				DebugLocation(276, 17);
				PushFollow(Follow._expresion_in_simple31736);
				expresion42=expresion();
				PopFollow();

				adaptor.AddChild(root_0, expresion42.Tree);

				}
				break;

			}
			} finally { DebugExitSubRule(12); }

			DebugLocation(276, 29);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:276:29: ( ',' REG )?
			int alt13=2;
			try { DebugEnterSubRule(13);
			try { DebugEnterDecision(13, false);
			int LA13_1 = input.LA(1);

			if ((LA13_1==41))
			{
				alt13 = 1;
			}
			} finally { DebugExitDecision(13); }
			switch (alt13)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:276:30: ',' REG
				{
				DebugLocation(276, 30);
				char_literal43=(IToken)Match(input,41,Follow._41_in_simple31741); 
				char_literal43_tree = (object)adaptor.Create(char_literal43);
				adaptor.AddChild(root_0, char_literal43_tree);
				DebugLocation(276, 34);
				REG44=(IToken)Match(input,REG,Follow._REG_in_simple31743); 
				REG44_tree = (object)adaptor.Create(REG44);
				adaptor.AddChild(root_0, REG44_tree);

				}
				break;

			}
			} finally { DebugExitSubRule(13); }


			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("simple3", 16);
			LeaveRule("simple3", 16);
			LeaveRule_simple3();
		}
		DebugLocation(277, 4);
		} finally { DebugExitRule(GrammarFileName, "simple3"); }
		return retval;

	}
	// $ANTLR end "simple3"

	partial void EnterRule_indirecto3();
	partial void LeaveRule_indirecto3();
	// $ANTLR start "indirecto3"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:280:1: indirecto3 : F34CODOP AT expresion ;
	[GrammarRule("indirecto3")]
	private AstParserRuleReturnScope<object, IToken> indirecto3()
	{
		EnterRule_indirecto3();
		EnterRule("indirecto3", 17);
		TraceIn("indirecto3", 17);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken F34CODOP45 = default(IToken);
		IToken AT46 = default(IToken);
		AstParserRuleReturnScope<object, IToken> expresion47 = default(AstParserRuleReturnScope<object, IToken>);

		object F34CODOP45_tree = default(object);
		object AT46_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "indirecto3");
		DebugLocation(280, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:281:5: ( F34CODOP AT expresion )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:281:7: F34CODOP AT expresion
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(281, 7);
			F34CODOP45=(IToken)Match(input,F34CODOP,Follow._F34CODOP_in_indirecto31764); 
			F34CODOP45_tree = (object)adaptor.Create(F34CODOP45);
			adaptor.AddChild(root_0, F34CODOP45_tree);
			DebugLocation(281, 16);
			AT46=(IToken)Match(input,AT,Follow._AT_in_indirecto31766); 
			AT46_tree = (object)adaptor.Create(AT46);
			adaptor.AddChild(root_0, AT46_tree);
			DebugLocation(281, 19);
			PushFollow(Follow._expresion_in_indirecto31768);
			expresion47=expresion();
			PopFollow();

			adaptor.AddChild(root_0, expresion47.Tree);

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("indirecto3", 17);
			LeaveRule("indirecto3", 17);
			LeaveRule_indirecto3();
		}
		DebugLocation(282, 4);
		} finally { DebugExitRule(GrammarFileName, "indirecto3"); }
		return retval;

	}
	// $ANTLR end "indirecto3"

	partial void EnterRule_inmediato3();
	partial void LeaveRule_inmediato3();
	// $ANTLR start "inmediato3"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:285:1: inmediato3 : F34CODOP NUMERAL expresion ;
	[GrammarRule("inmediato3")]
	private AstParserRuleReturnScope<object, IToken> inmediato3()
	{
		EnterRule_inmediato3();
		EnterRule("inmediato3", 18);
		TraceIn("inmediato3", 18);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken F34CODOP48 = default(IToken);
		IToken NUMERAL49 = default(IToken);
		AstParserRuleReturnScope<object, IToken> expresion50 = default(AstParserRuleReturnScope<object, IToken>);

		object F34CODOP48_tree = default(object);
		object NUMERAL49_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "inmediato3");
		DebugLocation(285, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:286:5: ( F34CODOP NUMERAL expresion )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:286:7: F34CODOP NUMERAL expresion
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(286, 7);
			F34CODOP48=(IToken)Match(input,F34CODOP,Follow._F34CODOP_in_inmediato31786); 
			F34CODOP48_tree = (object)adaptor.Create(F34CODOP48);
			adaptor.AddChild(root_0, F34CODOP48_tree);
			DebugLocation(286, 16);
			NUMERAL49=(IToken)Match(input,NUMERAL,Follow._NUMERAL_in_inmediato31788); 
			NUMERAL49_tree = (object)adaptor.Create(NUMERAL49);
			adaptor.AddChild(root_0, NUMERAL49_tree);
			DebugLocation(286, 24);
			PushFollow(Follow._expresion_in_inmediato31790);
			expresion50=expresion();
			PopFollow();

			adaptor.AddChild(root_0, expresion50.Tree);

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("inmediato3", 18);
			LeaveRule("inmediato3", 18);
			LeaveRule_inmediato3();
		}
		DebugLocation(287, 4);
		} finally { DebugExitRule(GrammarFileName, "inmediato3"); }
		return retval;

	}
	// $ANTLR end "inmediato3"

	partial void EnterRule_directiva();
	partial void LeaveRule_directiva();
	// $ANTLR start "directiva"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:292:1: directiva : ( etiqueta )? tipodirectiva ( opdirectiva )? FINL -> ^( DIR ( etiqueta )? tipodirectiva ( opdirectiva )? ) ;
	[GrammarRule("directiva")]
	private AstParserRuleReturnScope<object, IToken> directiva()
	{
		EnterRule_directiva();
		EnterRule("directiva", 19);
		TraceIn("directiva", 19);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken FINL54 = default(IToken);
		AstParserRuleReturnScope<object, IToken> etiqueta51 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> tipodirectiva52 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> opdirectiva53 = default(AstParserRuleReturnScope<object, IToken>);

		object FINL54_tree = default(object);
		RewriteRuleITokenStream stream_FINL=new RewriteRuleITokenStream(adaptor,"token FINL");
		RewriteRuleSubtreeStream stream_etiqueta=new RewriteRuleSubtreeStream(adaptor,"rule etiqueta");
		RewriteRuleSubtreeStream stream_opdirectiva=new RewriteRuleSubtreeStream(adaptor,"rule opdirectiva");
		RewriteRuleSubtreeStream stream_tipodirectiva=new RewriteRuleSubtreeStream(adaptor,"rule tipodirectiva");
		try { DebugEnterRule(GrammarFileName, "directiva");
		DebugLocation(292, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:293:5: ( ( etiqueta )? tipodirectiva ( opdirectiva )? FINL -> ^( DIR ( etiqueta )? tipodirectiva ( opdirectiva )? ) )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:293:7: ( etiqueta )? tipodirectiva ( opdirectiva )? FINL
			{
			DebugLocation(293, 7);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:293:7: ( etiqueta )?
			int alt14=2;
			try { DebugEnterSubRule(14);
			try { DebugEnterDecision(14, false);
			int LA14_1 = input.LA(1);

			if ((LA14_1==ID))
			{
				alt14 = 1;
			}
			} finally { DebugExitDecision(14); }
			switch (alt14)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:293:7: etiqueta
				{
				DebugLocation(293, 7);
				PushFollow(Follow._etiqueta_in_directiva1810);
				etiqueta51=etiqueta();
				PopFollow();

				stream_etiqueta.Add(etiqueta51.Tree);

				}
				break;

			}
			} finally { DebugExitSubRule(14); }

			DebugLocation(293, 17);
			PushFollow(Follow._tipodirectiva_in_directiva1813);
			tipodirectiva52=tipodirectiva();
			PopFollow();

			stream_tipodirectiva.Add(tipodirectiva52.Tree);
			DebugLocation(293, 31);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:293:31: ( opdirectiva )?
			int alt15=2;
			try { DebugEnterSubRule(15);
			try { DebugEnterDecision(15, false);
			int LA15_1 = input.LA(1);

			if (((LA15_1>=CHCONST && LA15_1<=CONSTHEX)||(LA15_1>=HEXCONST && LA15_1<=ID)||LA15_1==LPAREN||LA15_1==NUM||LA15_1==STAR))
			{
				alt15 = 1;
			}
			} finally { DebugExitDecision(15); }
			switch (alt15)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:293:32: opdirectiva
				{
				DebugLocation(293, 32);
				PushFollow(Follow._opdirectiva_in_directiva1816);
				opdirectiva53=opdirectiva();
				PopFollow();

				stream_opdirectiva.Add(opdirectiva53.Tree);

				}
				break;

			}
			} finally { DebugExitSubRule(15); }

			DebugLocation(293, 46);
			FINL54=(IToken)Match(input,FINL,Follow._FINL_in_directiva1820);  
			stream_FINL.Add(FINL54);



			{
			// AST REWRITE
			// elements: etiqueta, opdirectiva, tipodirectiva
			// token labels: 
			// rule labels: retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (object)adaptor.Nil();
			// 294:7: -> ^( DIR ( etiqueta )? tipodirectiva ( opdirectiva )? )
			{
				DebugLocation(294, 10);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:294:10: ^( DIR ( etiqueta )? tipodirectiva ( opdirectiva )? )
				{
				object root_1 = (object)adaptor.Nil();
				DebugLocation(294, 12);
				root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(DIR, "DIR"), root_1);

				DebugLocation(294, 16);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:294:16: ( etiqueta )?
				if (stream_etiqueta.HasNext)
				{
					DebugLocation(294, 17);
					adaptor.AddChild(root_1, stream_etiqueta.NextTree());

				}
				stream_etiqueta.Reset();
				DebugLocation(294, 28);
				adaptor.AddChild(root_1, stream_tipodirectiva.NextTree());
				DebugLocation(294, 42);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:294:42: ( opdirectiva )?
				if (stream_opdirectiva.HasNext)
				{
					DebugLocation(294, 43);
					adaptor.AddChild(root_1, stream_opdirectiva.NextTree());

				}
				stream_opdirectiva.Reset();

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("directiva", 19);
			LeaveRule("directiva", 19);
			LeaveRule_directiva();
		}
		DebugLocation(295, 4);
		} finally { DebugExitRule(GrammarFileName, "directiva"); }
		return retval;

	}
	// $ANTLR end "directiva"

	partial void EnterRule_tipodirectiva();
	partial void LeaveRule_tipodirectiva();
	// $ANTLR start "tipodirectiva"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:297:1: tipodirectiva : ( BYTE | WORD | RESB | RESW | BASE | EQU | ORG | USE );
	[GrammarRule("tipodirectiva")]
	private AstParserRuleReturnScope<object, IToken> tipodirectiva()
	{
		EnterRule_tipodirectiva();
		EnterRule("tipodirectiva", 20);
		TraceIn("tipodirectiva", 20);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken set55 = default(IToken);

		object set55_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "tipodirectiva");
		DebugLocation(297, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:298:5: ( BYTE | WORD | RESB | RESW | BASE | EQU | ORG | USE )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(298, 5);

			set55=(IToken)input.LT(1);
			if ((input.LA(1)>=BASE && input.LA(1)<=BYTE)||input.LA(1)==EQU||input.LA(1)==ORG||(input.LA(1)>=RESB && input.LA(1)<=RESW)||(input.LA(1)>=USE && input.LA(1)<=WORD))
			{
				input.Consume();
				adaptor.AddChild(root_0, (object)adaptor.Create(set55));
				state.errorRecovery=false;
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				throw mse;
			}


			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("tipodirectiva", 20);
			LeaveRule("tipodirectiva", 20);
			LeaveRule_tipodirectiva();
		}
		DebugLocation(306, 4);
		} finally { DebugExitRule(GrammarFileName, "tipodirectiva"); }
		return retval;

	}
	// $ANTLR end "tipodirectiva"

	partial void EnterRule_opdirectiva();
	partial void LeaveRule_opdirectiva();
	// $ANTLR start "opdirectiva"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:309:1: opdirectiva : expresion ;
	[GrammarRule("opdirectiva")]
	private AstParserRuleReturnScope<object, IToken> opdirectiva()
	{
		EnterRule_opdirectiva();
		EnterRule("opdirectiva", 21);
		TraceIn("opdirectiva", 21);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		AstParserRuleReturnScope<object, IToken> expresion56 = default(AstParserRuleReturnScope<object, IToken>);

		try { DebugEnterRule(GrammarFileName, "opdirectiva");
		DebugLocation(309, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:310:5: ( expresion )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:310:7: expresion
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(310, 7);
			PushFollow(Follow._expresion_in_opdirectiva1939);
			expresion56=expresion();
			PopFollow();

			adaptor.AddChild(root_0, expresion56.Tree);

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("opdirectiva", 21);
			LeaveRule("opdirectiva", 21);
			LeaveRule_opdirectiva();
		}
		DebugLocation(311, 4);
		} finally { DebugExitRule(GrammarFileName, "opdirectiva"); }
		return retval;

	}
	// $ANTLR end "opdirectiva"

	partial void EnterRule_etiqueta();
	partial void LeaveRule_etiqueta();
	// $ANTLR start "etiqueta"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:314:1: etiqueta : ID ;
	[GrammarRule("etiqueta")]
	private AstParserRuleReturnScope<object, IToken> etiqueta()
	{
		EnterRule_etiqueta();
		EnterRule("etiqueta", 22);
		TraceIn("etiqueta", 22);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken ID57 = default(IToken);

		object ID57_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "etiqueta");
		DebugLocation(314, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:315:5: ( ID )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:315:7: ID
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(315, 7);
			ID57=(IToken)Match(input,ID,Follow._ID_in_etiqueta1957); 
			ID57_tree = (object)adaptor.Create(ID57);
			adaptor.AddChild(root_0, ID57_tree);

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("etiqueta", 22);
			LeaveRule("etiqueta", 22);
			LeaveRule_etiqueta();
		}
		DebugLocation(316, 4);
		} finally { DebugExitRule(GrammarFileName, "etiqueta"); }
		return retval;

	}
	// $ANTLR end "etiqueta"

	partial void EnterRule_expresion();
	partial void LeaveRule_expresion();
	// $ANTLR start "expresion"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:321:1: expresion : exprAddSub ;
	[GrammarRule("expresion")]
	private AstParserRuleReturnScope<object, IToken> expresion()
	{
		EnterRule_expresion();
		EnterRule("expresion", 23);
		TraceIn("expresion", 23);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		AstParserRuleReturnScope<object, IToken> exprAddSub58 = default(AstParserRuleReturnScope<object, IToken>);

		try { DebugEnterRule(GrammarFileName, "expresion");
		DebugLocation(321, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:322:5: ( exprAddSub )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:322:7: exprAddSub
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(322, 7);
			PushFollow(Follow._exprAddSub_in_expresion1977);
			exprAddSub58=exprAddSub();
			PopFollow();

			adaptor.AddChild(root_0, exprAddSub58.Tree);

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("expresion", 23);
			LeaveRule("expresion", 23);
			LeaveRule_expresion();
		}
		DebugLocation(323, 4);
		} finally { DebugExitRule(GrammarFileName, "expresion"); }
		return retval;

	}
	// $ANTLR end "expresion"

	partial void EnterRule_exprAddSub();
	partial void LeaveRule_exprAddSub();
	// $ANTLR start "exprAddSub"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:325:1: exprAddSub : exprMulDiv ( ( PLUS | MINUS ) exprMulDiv )* ;
	[GrammarRule("exprAddSub")]
	private AstParserRuleReturnScope<object, IToken> exprAddSub()
	{
		EnterRule_exprAddSub();
		EnterRule("exprAddSub", 24);
		TraceIn("exprAddSub", 24);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken set60 = default(IToken);
		AstParserRuleReturnScope<object, IToken> exprMulDiv59 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> exprMulDiv61 = default(AstParserRuleReturnScope<object, IToken>);

		object set60_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "exprAddSub");
		DebugLocation(325, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:326:5: ( exprMulDiv ( ( PLUS | MINUS ) exprMulDiv )* )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:326:7: exprMulDiv ( ( PLUS | MINUS ) exprMulDiv )*
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(326, 7);
			PushFollow(Follow._exprMulDiv_in_exprAddSub1994);
			exprMulDiv59=exprMulDiv();
			PopFollow();

			adaptor.AddChild(root_0, exprMulDiv59.Tree);
			DebugLocation(326, 18);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:326:18: ( ( PLUS | MINUS ) exprMulDiv )*
			try { DebugEnterSubRule(16);
			while (true)
			{
				int alt16=2;
				try { DebugEnterDecision(16, false);
				int LA16_1 = input.LA(1);

				if ((LA16_1==MINUS||LA16_1==PLUS))
				{
					alt16 = 1;
				}


				} finally { DebugExitDecision(16); }
				switch ( alt16 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:326:20: ( PLUS | MINUS ) exprMulDiv
					{
					DebugLocation(326, 20);

					set60=(IToken)input.LT(1);
					if (input.LA(1)==MINUS||input.LA(1)==PLUS)
					{
						input.Consume();
						adaptor.AddChild(root_0, (object)adaptor.Create(set60));
						state.errorRecovery=false;
					}
					else
					{
						MismatchedSetException mse = new MismatchedSetException(null,input);
						DebugRecognitionException(mse);
						throw mse;
					}

					DebugLocation(326, 35);
					PushFollow(Follow._exprMulDiv_in_exprAddSub2006);
					exprMulDiv61=exprMulDiv();
					PopFollow();

					adaptor.AddChild(root_0, exprMulDiv61.Tree);

					}
					break;

				default:
					goto loop16;
				}
			}

			loop16:
				;

			} finally { DebugExitSubRule(16); }


			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("exprAddSub", 24);
			LeaveRule("exprAddSub", 24);
			LeaveRule_exprAddSub();
		}
		DebugLocation(327, 4);
		} finally { DebugExitRule(GrammarFileName, "exprAddSub"); }
		return retval;

	}
	// $ANTLR end "exprAddSub"

	partial void EnterRule_exprMulDiv();
	partial void LeaveRule_exprMulDiv();
	// $ANTLR start "exprMulDiv"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:329:1: exprMulDiv : factor ( ( STAR | DIV ) factor )* ;
	[GrammarRule("exprMulDiv")]
	private AstParserRuleReturnScope<object, IToken> exprMulDiv()
	{
		EnterRule_exprMulDiv();
		EnterRule("exprMulDiv", 25);
		TraceIn("exprMulDiv", 25);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken set63 = default(IToken);
		AstParserRuleReturnScope<object, IToken> factor62 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> factor64 = default(AstParserRuleReturnScope<object, IToken>);

		object set63_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "exprMulDiv");
		DebugLocation(329, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:330:5: ( factor ( ( STAR | DIV ) factor )* )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:330:7: factor ( ( STAR | DIV ) factor )*
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(330, 7);
			PushFollow(Follow._factor_in_exprMulDiv2026);
			factor62=factor();
			PopFollow();

			adaptor.AddChild(root_0, factor62.Tree);
			DebugLocation(330, 14);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:330:14: ( ( STAR | DIV ) factor )*
			try { DebugEnterSubRule(17);
			while (true)
			{
				int alt17=2;
				try { DebugEnterDecision(17, false);
				int LA17_1 = input.LA(1);

				if ((LA17_1==DIV||LA17_1==STAR))
				{
					alt17 = 1;
				}


				} finally { DebugExitDecision(17); }
				switch ( alt17 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:330:16: ( STAR | DIV ) factor
					{
					DebugLocation(330, 16);

					set63=(IToken)input.LT(1);
					if (input.LA(1)==DIV||input.LA(1)==STAR)
					{
						input.Consume();
						adaptor.AddChild(root_0, (object)adaptor.Create(set63));
						state.errorRecovery=false;
					}
					else
					{
						MismatchedSetException mse = new MismatchedSetException(null,input);
						DebugRecognitionException(mse);
						throw mse;
					}

					DebugLocation(330, 29);
					PushFollow(Follow._factor_in_exprMulDiv2038);
					factor64=factor();
					PopFollow();

					adaptor.AddChild(root_0, factor64.Tree);

					}
					break;

				default:
					goto loop17;
				}
			}

			loop17:
				;

			} finally { DebugExitSubRule(17); }


			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("exprMulDiv", 25);
			LeaveRule("exprMulDiv", 25);
			LeaveRule_exprMulDiv();
		}
		DebugLocation(331, 4);
		} finally { DebugExitRule(GrammarFileName, "exprMulDiv"); }
		return retval;

	}
	// $ANTLR end "exprMulDiv"

	partial void EnterRule_factor();
	partial void LeaveRule_factor();
	// $ANTLR start "factor"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:333:1: factor : ( LPAREN expresion RPAREN | ID | NUM | HEXSUF | CONSTHEX | STAR | CHCONST | HEXCONST | CONSTCAD );
	[GrammarRule("factor")]
	private AstParserRuleReturnScope<object, IToken> factor()
	{
		EnterRule_factor();
		EnterRule("factor", 26);
		TraceIn("factor", 26);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken LPAREN65 = default(IToken);
		IToken RPAREN67 = default(IToken);
		IToken ID68 = default(IToken);
		IToken NUM69 = default(IToken);
		IToken HEXSUF70 = default(IToken);
		IToken CONSTHEX71 = default(IToken);
		IToken STAR72 = default(IToken);
		IToken CHCONST73 = default(IToken);
		IToken HEXCONST74 = default(IToken);
		IToken CONSTCAD75 = default(IToken);
		AstParserRuleReturnScope<object, IToken> expresion66 = default(AstParserRuleReturnScope<object, IToken>);

		object LPAREN65_tree = default(object);
		object RPAREN67_tree = default(object);
		object ID68_tree = default(object);
		object NUM69_tree = default(object);
		object HEXSUF70_tree = default(object);
		object CONSTHEX71_tree = default(object);
		object STAR72_tree = default(object);
		object CHCONST73_tree = default(object);
		object HEXCONST74_tree = default(object);
		object CONSTCAD75_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "factor");
		DebugLocation(333, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:335:5: ( LPAREN expresion RPAREN | ID | NUM | HEXSUF | CONSTHEX | STAR | CHCONST | HEXCONST | CONSTCAD )
			int alt18=9;
			try { DebugEnterDecision(18, false);
			switch (input.LA(1))
			{
			case LPAREN:
				{
				alt18 = 1;
				}
				break;
			case ID:
				{
				alt18 = 2;
				}
				break;
			case NUM:
				{
				alt18 = 3;
				}
				break;
			case HEXSUF:
				{
				alt18 = 4;
				}
				break;
			case CONSTHEX:
				{
				alt18 = 5;
				}
				break;
			case STAR:
				{
				alt18 = 6;
				}
				break;
			case CHCONST:
				{
				alt18 = 7;
				}
				break;
			case HEXCONST:
				{
				alt18 = 8;
				}
				break;
			case CONSTCAD:
				{
				alt18 = 9;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 18, 0, input, 1);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(18); }
			switch (alt18)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:335:7: LPAREN expresion RPAREN
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(335, 7);
				LPAREN65=(IToken)Match(input,LPAREN,Follow._LPAREN_in_factor2063); 
				LPAREN65_tree = (object)adaptor.Create(LPAREN65);
				adaptor.AddChild(root_0, LPAREN65_tree);
				DebugLocation(335, 14);
				PushFollow(Follow._expresion_in_factor2065);
				expresion66=expresion();
				PopFollow();

				adaptor.AddChild(root_0, expresion66.Tree);
				DebugLocation(335, 24);
				RPAREN67=(IToken)Match(input,RPAREN,Follow._RPAREN_in_factor2067); 
				RPAREN67_tree = (object)adaptor.Create(RPAREN67);
				adaptor.AddChild(root_0, RPAREN67_tree);

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:337:7: ID
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(337, 7);
				ID68=(IToken)Match(input,ID,Follow._ID_in_factor2080); 
				ID68_tree = (object)adaptor.Create(ID68);
				adaptor.AddChild(root_0, ID68_tree);

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:339:7: NUM
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(339, 7);
				NUM69=(IToken)Match(input,NUM,Follow._NUM_in_factor2093); 
				NUM69_tree = (object)adaptor.Create(NUM69);
				adaptor.AddChild(root_0, NUM69_tree);

				}
				break;
			case 4:
				DebugEnterAlt(4);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:341:7: HEXSUF
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(341, 7);
				HEXSUF70=(IToken)Match(input,HEXSUF,Follow._HEXSUF_in_factor2106); 
				HEXSUF70_tree = (object)adaptor.Create(HEXSUF70);
				adaptor.AddChild(root_0, HEXSUF70_tree);

				}
				break;
			case 5:
				DebugEnterAlt(5);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:343:7: CONSTHEX
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(343, 7);
				CONSTHEX71=(IToken)Match(input,CONSTHEX,Follow._CONSTHEX_in_factor2119); 
				CONSTHEX71_tree = (object)adaptor.Create(CONSTHEX71);
				adaptor.AddChild(root_0, CONSTHEX71_tree);

				}
				break;
			case 6:
				DebugEnterAlt(6);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:345:7: STAR
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(345, 7);
				STAR72=(IToken)Match(input,STAR,Follow._STAR_in_factor2132); 
				STAR72_tree = (object)adaptor.Create(STAR72);
				adaptor.AddChild(root_0, STAR72_tree);

				}
				break;
			case 7:
				DebugEnterAlt(7);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:347:7: CHCONST
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(347, 7);
				CHCONST73=(IToken)Match(input,CHCONST,Follow._CHCONST_in_factor2145); 
				CHCONST73_tree = (object)adaptor.Create(CHCONST73);
				adaptor.AddChild(root_0, CHCONST73_tree);

				}
				break;
			case 8:
				DebugEnterAlt(8);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:349:7: HEXCONST
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(349, 7);
				HEXCONST74=(IToken)Match(input,HEXCONST,Follow._HEXCONST_in_factor2158); 
				HEXCONST74_tree = (object)adaptor.Create(HEXCONST74);
				adaptor.AddChild(root_0, HEXCONST74_tree);

				}
				break;
			case 9:
				DebugEnterAlt(9);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:351:7: CONSTCAD
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(351, 7);
				CONSTCAD75=(IToken)Match(input,CONSTCAD,Follow._CONSTCAD_in_factor2171); 
				CONSTCAD75_tree = (object)adaptor.Create(CONSTCAD75);
				adaptor.AddChild(root_0, CONSTCAD75_tree);

				}
				break;

			}
			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("factor", 26);
			LeaveRule("factor", 26);
			LeaveRule_factor();
		}
		DebugLocation(352, 4);
		} finally { DebugExitRule(GrammarFileName, "factor"); }
		return retval;

	}
	// $ANTLR end "factor"
	#endregion Rules


	#region Follow sets
	private static class Follow
	{
		public static readonly BitSet _inicio_in_programa1257 = new BitSet(new ulong[]{0xC6C0856060UL});
		public static readonly BitSet _proposiciones_in_programa1259 = new BitSet(new ulong[]{0x1000UL});
		public static readonly BitSet _fin_in_programa1261 = new BitSet(new ulong[]{0x100000UL});
		public static readonly BitSet _FINL_in_programa1264 = new BitSet(new ulong[]{0x0UL});
		public static readonly BitSet _EOF_in_programa1268 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _raiz_in_inicio1285 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _proposicion_in_inicio1293 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _etiqueta_in_raiz1313 = new BitSet(new ulong[]{0x2000000000UL});
		public static readonly BitSet _START_in_raiz1317 = new BitSet(new ulong[]{0x10500000UL});
		public static readonly BitSet _NUM_in_raiz1322 = new BitSet(new ulong[]{0x100000UL});
		public static readonly BitSet _HEXSUF_in_raiz1326 = new BitSet(new ulong[]{0x100000UL});
		public static readonly BitSet _FINL_in_raiz1330 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _END_in_fin1372 = new BitSet(new ulong[]{0x900000UL});
		public static readonly BitSet _entrada_in_fin1376 = new BitSet(new ulong[]{0x100002UL});
		public static readonly BitSet _FINL_in_fin1379 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _ID_in_entrada1417 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _proposicion_in_proposiciones1437 = new BitSet(new ulong[]{0xC6C0856062UL});
		public static readonly BitSet _instruccion_in_proposicion1457 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _directiva_in_proposicion1465 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _etiqueta_in_instruccion1485 = new BitSet(new ulong[]{0x80054000UL});
		public static readonly BitSet _opinstruccion_in_instruccion1488 = new BitSet(new ulong[]{0x100000UL});
		public static readonly BitSet _FINL_in_instruccion1490 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _formato_in_opinstruccion1526 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _f1_in_formato1543 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _f2_in_formato1551 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _f3_in_formato1559 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _f4_in_formato1567 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _indexado_in_formato1575 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _F1CODOP_in_f11593 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _F2CODOP_in_f21611 = new BitSet(new ulong[]{0x100000000UL});
		public static readonly BitSet _REG_in_f21613 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _F2CODOP_in_f21621 = new BitSet(new ulong[]{0x100000000UL});
		public static readonly BitSet _REG_in_f21623 = new BitSet(new ulong[]{0x20000000000UL});
		public static readonly BitSet _41_in_f21625 = new BitSet(new ulong[]{0x100000000UL});
		public static readonly BitSet _REG_in_f21627 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _F2CODOP_in_f21635 = new BitSet(new ulong[]{0x100000000UL});
		public static readonly BitSet _REG_in_f21637 = new BitSet(new ulong[]{0x20000000000UL});
		public static readonly BitSet _41_in_f21639 = new BitSet(new ulong[]{0x10000000UL});
		public static readonly BitSet _NUM_in_f21641 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _simple3_in_f31659 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _indirecto3_in_f31667 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _inmediato3_in_f31675 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _PLUS_in_f41693 = new BitSet(new ulong[]{0x40000UL});
		public static readonly BitSet _f3_in_f41695 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _F34CODOP_in_indexado1713 = new BitSet(new ulong[]{0x1000000UL});
		public static readonly BitSet _INDICE_in_indexado1715 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _F34CODOP_in_simple31733 = new BitSet(new ulong[]{0x21014E00382UL});
		public static readonly BitSet _expresion_in_simple31736 = new BitSet(new ulong[]{0x20000000002UL});
		public static readonly BitSet _41_in_simple31741 = new BitSet(new ulong[]{0x100000000UL});
		public static readonly BitSet _REG_in_simple31743 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _F34CODOP_in_indirecto31764 = new BitSet(new ulong[]{0x10UL});
		public static readonly BitSet _AT_in_indirecto31766 = new BitSet(new ulong[]{0x1014E00380UL});
		public static readonly BitSet _expresion_in_indirecto31768 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _F34CODOP_in_inmediato31786 = new BitSet(new ulong[]{0x20000000UL});
		public static readonly BitSet _NUMERAL_in_inmediato31788 = new BitSet(new ulong[]{0x1014E00380UL});
		public static readonly BitSet _expresion_in_inmediato31790 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _etiqueta_in_directiva1810 = new BitSet(new ulong[]{0xC640002060UL});
		public static readonly BitSet _tipodirectiva_in_directiva1813 = new BitSet(new ulong[]{0x1014F00380UL});
		public static readonly BitSet _opdirectiva_in_directiva1816 = new BitSet(new ulong[]{0x100000UL});
		public static readonly BitSet _FINL_in_directiva1820 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _expresion_in_opdirectiva1939 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _ID_in_etiqueta1957 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _exprAddSub_in_expresion1977 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _exprMulDiv_in_exprAddSub1994 = new BitSet(new ulong[]{0x88000002UL});
		public static readonly BitSet _set_in_exprAddSub1998 = new BitSet(new ulong[]{0x1014E00380UL});
		public static readonly BitSet _exprMulDiv_in_exprAddSub2006 = new BitSet(new ulong[]{0x88000002UL});
		public static readonly BitSet _factor_in_exprMulDiv2026 = new BitSet(new ulong[]{0x1000000802UL});
		public static readonly BitSet _set_in_exprMulDiv2030 = new BitSet(new ulong[]{0x1014E00380UL});
		public static readonly BitSet _factor_in_exprMulDiv2038 = new BitSet(new ulong[]{0x1000000802UL});
		public static readonly BitSet _LPAREN_in_factor2063 = new BitSet(new ulong[]{0x1014E00380UL});
		public static readonly BitSet _expresion_in_factor2065 = new BitSet(new ulong[]{0x800000000UL});
		public static readonly BitSet _RPAREN_in_factor2067 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _ID_in_factor2080 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _NUM_in_factor2093 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _HEXSUF_in_factor2106 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _CONSTHEX_in_factor2119 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _STAR_in_factor2132 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _CHCONST_in_factor2145 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _HEXCONST_in_factor2158 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _CONSTCAD_in_factor2171 = new BitSet(new ulong[]{0x2UL});
	}
	#endregion Follow sets
}
