//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.5.1 C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g 2025-03-04 15:33:20

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591
// CLS compliance checking will not be performed on 'type' because it is not visible from outside this assembly.
#pragma warning disable 3019


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.5.1")]
[System.CLSCompliant(false)]
public partial class Gram_SICXELexer : Antlr.Runtime.Lexer
{
	public const int EOF=-1;
	public const int T__33=33;
	public const int AT=4;
	public const int BASE=5;
	public const int BYTE=6;
	public const int CHCONST=7;
	public const int CONSTCAD=8;
	public const int CONSTHEX=9;
	public const int DIR=10;
	public const int END=11;
	public const int F1CODOP=12;
	public const int F1_INSTR=13;
	public const int F2CODOP=14;
	public const int F2_INSTR=15;
	public const int F34CODOP=16;
	public const int F34_INSTR=17;
	public const int FINL=18;
	public const int HEXCONST=19;
	public const int HEXSUF=20;
	public const int ID=21;
	public const int INDICE=22;
	public const int INSTR=23;
	public const int NUM=24;
	public const int NUMERAL=25;
	public const int PLUS=26;
	public const int REG=27;
	public const int RESB=28;
	public const int RESW=29;
	public const int START=30;
	public const int WORD=31;
	public const int WS=32;

	// delegates
	// delegators

	public Gram_SICXELexer()
	{
		OnCreated();
	}

	public Gram_SICXELexer(ICharStream input )
		: this(input, new RecognizerSharedState())
	{
	}

	public Gram_SICXELexer(ICharStream input, RecognizerSharedState state)
		: base(input, state)
	{

		OnCreated();
	}
	public override string GrammarFileName { get { return "C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g"; } }


	partial void OnCreated();
	partial void EnterRule(string ruleName, int ruleIndex);
	partial void LeaveRule(string ruleName, int ruleIndex);

	partial void EnterRule_T__33();
	partial void LeaveRule_T__33();

	// $ANTLR start "T__33"
	[GrammarRule("T__33")]
	private void mT__33()
	{
		EnterRule_T__33();
		EnterRule("T__33", 1);
		TraceIn("T__33", 1);
		try
		{
			int _type = T__33;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:7:7: ( ',' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:7:9: ','
			{
			DebugLocation(7, 9);
			Match(','); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("T__33", 1);
			LeaveRule("T__33", 1);
			LeaveRule_T__33();
		}
	}
	// $ANTLR end "T__33"

	partial void EnterRule_START();
	partial void LeaveRule_START();

	// $ANTLR start "START"
	[GrammarRule("START")]
	private void mSTART()
	{
		EnterRule_START();
		EnterRule("START", 2);
		TraceIn("START", 2);
		try
		{
			int _type = START;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:153:7: ( 'START' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:153:9: 'START'
			{
			DebugLocation(153, 9);
			Match("START"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("START", 2);
			LeaveRule("START", 2);
			LeaveRule_START();
		}
	}
	// $ANTLR end "START"

	partial void EnterRule_END();
	partial void LeaveRule_END();

	// $ANTLR start "END"
	[GrammarRule("END")]
	private void mEND()
	{
		EnterRule_END();
		EnterRule("END", 3);
		TraceIn("END", 3);
		try
		{
			int _type = END;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:154:7: ( 'END' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:154:9: 'END'
			{
			DebugLocation(154, 9);
			Match("END"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("END", 3);
			LeaveRule("END", 3);
			LeaveRule_END();
		}
	}
	// $ANTLR end "END"

	partial void EnterRule_BYTE();
	partial void LeaveRule_BYTE();

	// $ANTLR start "BYTE"
	[GrammarRule("BYTE")]
	private void mBYTE()
	{
		EnterRule_BYTE();
		EnterRule("BYTE", 4);
		TraceIn("BYTE", 4);
		try
		{
			int _type = BYTE;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:155:7: ( 'BYTE' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:155:9: 'BYTE'
			{
			DebugLocation(155, 9);
			Match("BYTE"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("BYTE", 4);
			LeaveRule("BYTE", 4);
			LeaveRule_BYTE();
		}
	}
	// $ANTLR end "BYTE"

	partial void EnterRule_WORD();
	partial void LeaveRule_WORD();

	// $ANTLR start "WORD"
	[GrammarRule("WORD")]
	private void mWORD()
	{
		EnterRule_WORD();
		EnterRule("WORD", 5);
		TraceIn("WORD", 5);
		try
		{
			int _type = WORD;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:156:7: ( 'WORD' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:156:9: 'WORD'
			{
			DebugLocation(156, 9);
			Match("WORD"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("WORD", 5);
			LeaveRule("WORD", 5);
			LeaveRule_WORD();
		}
	}
	// $ANTLR end "WORD"

	partial void EnterRule_RESB();
	partial void LeaveRule_RESB();

	// $ANTLR start "RESB"
	[GrammarRule("RESB")]
	private void mRESB()
	{
		EnterRule_RESB();
		EnterRule("RESB", 6);
		TraceIn("RESB", 6);
		try
		{
			int _type = RESB;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:157:7: ( 'RESB' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:157:9: 'RESB'
			{
			DebugLocation(157, 9);
			Match("RESB"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("RESB", 6);
			LeaveRule("RESB", 6);
			LeaveRule_RESB();
		}
	}
	// $ANTLR end "RESB"

	partial void EnterRule_RESW();
	partial void LeaveRule_RESW();

	// $ANTLR start "RESW"
	[GrammarRule("RESW")]
	private void mRESW()
	{
		EnterRule_RESW();
		EnterRule("RESW", 7);
		TraceIn("RESW", 7);
		try
		{
			int _type = RESW;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:158:7: ( 'RESW' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:158:9: 'RESW'
			{
			DebugLocation(158, 9);
			Match("RESW"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("RESW", 7);
			LeaveRule("RESW", 7);
			LeaveRule_RESW();
		}
	}
	// $ANTLR end "RESW"

	partial void EnterRule_BASE();
	partial void LeaveRule_BASE();

	// $ANTLR start "BASE"
	[GrammarRule("BASE")]
	private void mBASE()
	{
		EnterRule_BASE();
		EnterRule("BASE", 8);
		TraceIn("BASE", 8);
		try
		{
			int _type = BASE;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:159:7: ( 'BASE' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:159:9: 'BASE'
			{
			DebugLocation(159, 9);
			Match("BASE"); 


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("BASE", 8);
			LeaveRule("BASE", 8);
			LeaveRule_BASE();
		}
	}
	// $ANTLR end "BASE"

	partial void EnterRule_FINL();
	partial void LeaveRule_FINL();

	// $ANTLR start "FINL"
	[GrammarRule("FINL")]
	private void mFINL()
	{
		EnterRule_FINL();
		EnterRule("FINL", 9);
		TraceIn("FINL", 9);
		try
		{
			int _type = FINL;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:163:5: ( ( ';' )* ( ( '\\r' )? '\\n' | '\\r' ) )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:163:7: ( ';' )* ( ( '\\r' )? '\\n' | '\\r' )
			{
			DebugLocation(163, 7);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:163:7: ( ';' )*
			try { DebugEnterSubRule(1);
			while (true)
			{
				int alt1=2;
				try { DebugEnterDecision(1, false);
				int LA1_1 = input.LA(1);

				if ((LA1_1==';'))
				{
					alt1 = 1;
				}


				} finally { DebugExitDecision(1); }
				switch ( alt1 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:163:9: ';'
					{
					DebugLocation(163, 9);
					Match(';'); 

					}
					break;

				default:
					goto loop1;
				}
			}

			loop1:
				;

			} finally { DebugExitSubRule(1); }

			DebugLocation(163, 16);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:163:16: ( ( '\\r' )? '\\n' | '\\r' )
			int alt3=2;
			try { DebugEnterSubRule(3);
			try { DebugEnterDecision(3, false);
			int LA3_1 = input.LA(1);

			if ((LA3_1=='\r'))
			{
				int LA3_2 = input.LA(2);

				if ((LA3_2=='\n'))
				{
					alt3 = 1;
				}
				else
				{
					alt3 = 2;
				}
			}
			else if ((LA3_1=='\n'))
			{
				alt3 = 1;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 3, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(3); }
			switch (alt3)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:163:18: ( '\\r' )? '\\n'
				{
				DebugLocation(163, 18);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:163:18: ( '\\r' )?
				int alt2=2;
				try { DebugEnterSubRule(2);
				try { DebugEnterDecision(2, false);
				int LA2_1 = input.LA(1);

				if ((LA2_1=='\r'))
				{
					alt2 = 1;
				}
				} finally { DebugExitDecision(2); }
				switch (alt2)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:163:18: '\\r'
					{
					DebugLocation(163, 18);
					Match('\r'); 

					}
					break;

				}
				} finally { DebugExitSubRule(2); }

				DebugLocation(163, 24);
				Match('\n'); 

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:163:31: '\\r'
				{
				DebugLocation(163, 31);
				Match('\r'); 

				}
				break;

			}
			} finally { DebugExitSubRule(3); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("FINL", 9);
			LeaveRule("FINL", 9);
			LeaveRule_FINL();
		}
	}
	// $ANTLR end "FINL"

	partial void EnterRule_REG();
	partial void LeaveRule_REG();

	// $ANTLR start "REG"
	[GrammarRule("REG")]
	private void mREG()
	{
		EnterRule_REG();
		EnterRule("REG", 10);
		TraceIn("REG", 10);
		try
		{
			int _type = REG;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:168:5: ( 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'X' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:
			{
			DebugLocation(168, 5);
			if ((input.LA(1)>='A' && input.LA(1)<='F')||input.LA(1)=='X')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("REG", 10);
			LeaveRule("REG", 10);
			LeaveRule_REG();
		}
	}
	// $ANTLR end "REG"

	partial void EnterRule_INDICE();
	partial void LeaveRule_INDICE();

	// $ANTLR start "INDICE"
	[GrammarRule("INDICE")]
	private void mINDICE()
	{
		EnterRule_INDICE();
		EnterRule("INDICE", 11);
		TraceIn("INDICE", 11);
		try
		{
			int _type = INDICE;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:173:5: ( 'IX' | 'IY' | 'IZ' )
			int alt4=3;
			try { DebugEnterDecision(4, false);
			int LA4_1 = input.LA(1);

			if ((LA4_1=='I'))
			{
				switch (input.LA(2))
				{
				case 'X':
					{
					alt4 = 1;
					}
					break;
				case 'Y':
					{
					alt4 = 2;
					}
					break;
				case 'Z':
					{
					alt4 = 3;
					}
					break;
				default:
					{
						NoViableAltException nvae = new NoViableAltException("", 4, 1, input, 2);
						DebugRecognitionException(nvae);
						throw nvae;
					}
				}

			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 4, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(4); }
			switch (alt4)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:173:7: 'IX'
				{
				DebugLocation(173, 7);
				Match("IX"); 


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:173:14: 'IY'
				{
				DebugLocation(173, 14);
				Match("IY"); 


				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:173:21: 'IZ'
				{
				DebugLocation(173, 21);
				Match("IZ"); 


				}
				break;

			}
			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("INDICE", 11);
			LeaveRule("INDICE", 11);
			LeaveRule_INDICE();
		}
	}
	// $ANTLR end "INDICE"

	partial void EnterRule_PLUS();
	partial void LeaveRule_PLUS();

	// $ANTLR start "PLUS"
	[GrammarRule("PLUS")]
	private void mPLUS()
	{
		EnterRule_PLUS();
		EnterRule("PLUS", 12);
		TraceIn("PLUS", 12);
		try
		{
			int _type = PLUS;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:178:5: ( '+' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:178:7: '+'
			{
			DebugLocation(178, 7);
			Match('+'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("PLUS", 12);
			LeaveRule("PLUS", 12);
			LeaveRule_PLUS();
		}
	}
	// $ANTLR end "PLUS"

	partial void EnterRule_AT();
	partial void LeaveRule_AT();

	// $ANTLR start "AT"
	[GrammarRule("AT")]
	private void mAT()
	{
		EnterRule_AT();
		EnterRule("AT", 13);
		TraceIn("AT", 13);
		try
		{
			int _type = AT;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:183:5: ( '@' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:183:7: '@'
			{
			DebugLocation(183, 7);
			Match('@'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("AT", 13);
			LeaveRule("AT", 13);
			LeaveRule_AT();
		}
	}
	// $ANTLR end "AT"

	partial void EnterRule_NUMERAL();
	partial void LeaveRule_NUMERAL();

	// $ANTLR start "NUMERAL"
	[GrammarRule("NUMERAL")]
	private void mNUMERAL()
	{
		EnterRule_NUMERAL();
		EnterRule("NUMERAL", 14);
		TraceIn("NUMERAL", 14);
		try
		{
			int _type = NUMERAL;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:187:5: ( '#' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:187:7: '#'
			{
			DebugLocation(187, 7);
			Match('#'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("NUMERAL", 14);
			LeaveRule("NUMERAL", 14);
			LeaveRule_NUMERAL();
		}
	}
	// $ANTLR end "NUMERAL"

	partial void EnterRule_F1_INSTR();
	partial void LeaveRule_F1_INSTR();

	// $ANTLR start "F1_INSTR"
	[GrammarRule("F1_INSTR")]
	private void mF1_INSTR()
	{
		EnterRule_F1_INSTR();
		EnterRule("F1_INSTR", 15);
		TraceIn("F1_INSTR", 15);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:192:5: ( 'FIX' | 'NORM' | 'FLOAT' | 'HIO' | 'SIO' | 'TIO' )
			int alt5=6;
			try { DebugEnterDecision(5, false);
			switch (input.LA(1))
			{
			case 'F':
				{
				int LA5_2 = input.LA(2);

				if ((LA5_2=='I'))
				{
					alt5 = 1;
				}
				else if ((LA5_2=='L'))
				{
					alt5 = 3;
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 5, 1, input, 2);
					DebugRecognitionException(nvae);
					throw nvae;
				}
				}
				break;
			case 'N':
				{
				alt5 = 2;
				}
				break;
			case 'H':
				{
				alt5 = 4;
				}
				break;
			case 'S':
				{
				alt5 = 5;
				}
				break;
			case 'T':
				{
				alt5 = 6;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 5, 0, input, 1);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(5); }
			switch (alt5)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:192:7: 'FIX'
				{
				DebugLocation(192, 7);
				Match("FIX"); 


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:193:7: 'NORM'
				{
				DebugLocation(193, 7);
				Match("NORM"); 


				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:194:7: 'FLOAT'
				{
				DebugLocation(194, 7);
				Match("FLOAT"); 


				}
				break;
			case 4:
				DebugEnterAlt(4);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:195:7: 'HIO'
				{
				DebugLocation(195, 7);
				Match("HIO"); 


				}
				break;
			case 5:
				DebugEnterAlt(5);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:196:7: 'SIO'
				{
				DebugLocation(196, 7);
				Match("SIO"); 


				}
				break;
			case 6:
				DebugEnterAlt(6);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:197:7: 'TIO'
				{
				DebugLocation(197, 7);
				Match("TIO"); 


				}
				break;

			}
		}
		finally
		{
			TraceOut("F1_INSTR", 15);
			LeaveRule("F1_INSTR", 15);
			LeaveRule_F1_INSTR();
		}
	}
	// $ANTLR end "F1_INSTR"

	partial void EnterRule_F2_INSTR();
	partial void LeaveRule_F2_INSTR();

	// $ANTLR start "F2_INSTR"
	[GrammarRule("F2_INSTR")]
	private void mF2_INSTR()
	{
		EnterRule_F2_INSTR();
		EnterRule("F2_INSTR", 16);
		TraceIn("F2_INSTR", 16);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:201:5: ( 'ADDR' | 'SUBR' | 'COMPR' | 'MULR' | 'DIVR' | 'RMO' | 'SHIFTL' | 'SHIFTR' | 'SVC' | 'CLEAR' | 'TIXR' )
			int alt6=11;
			try { DebugEnterDecision(6, false);
			switch (input.LA(1))
			{
			case 'A':
				{
				alt6 = 1;
				}
				break;
			case 'S':
				{
				switch (input.LA(2))
				{
				case 'U':
					{
					alt6 = 2;
					}
					break;
				case 'H':
					{
					int LA6_3 = input.LA(3);

					if ((LA6_3=='I'))
					{
						int LA6_4 = input.LA(4);

						if ((LA6_4=='F'))
						{
							int LA6_5 = input.LA(5);

							if ((LA6_5=='T'))
							{
								int LA6_6 = input.LA(6);

								if ((LA6_6=='L'))
								{
									alt6 = 7;
								}
								else if ((LA6_6=='R'))
								{
									alt6 = 8;
								}
								else
								{
									NoViableAltException nvae = new NoViableAltException("", 6, 15, input, 6);
									DebugRecognitionException(nvae);
									throw nvae;
								}
							}
							else
							{
								NoViableAltException nvae = new NoViableAltException("", 6, 14, input, 5);
								DebugRecognitionException(nvae);
								throw nvae;
							}
						}
						else
						{
							NoViableAltException nvae = new NoViableAltException("", 6, 13, input, 4);
							DebugRecognitionException(nvae);
							throw nvae;
						}
					}
					else
					{
						NoViableAltException nvae = new NoViableAltException("", 6, 9, input, 3);
						DebugRecognitionException(nvae);
						throw nvae;
					}
					}
					break;
				case 'V':
					{
					alt6 = 9;
					}
					break;
				default:
					{
						NoViableAltException nvae = new NoViableAltException("", 6, 2, input, 2);
						DebugRecognitionException(nvae);
						throw nvae;
					}
				}

				}
				break;
			case 'C':
				{
				int LA6_2 = input.LA(2);

				if ((LA6_2=='O'))
				{
					alt6 = 3;
				}
				else if ((LA6_2=='L'))
				{
					alt6 = 10;
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 6, 3, input, 2);
					DebugRecognitionException(nvae);
					throw nvae;
				}
				}
				break;
			case 'M':
				{
				alt6 = 4;
				}
				break;
			case 'D':
				{
				alt6 = 5;
				}
				break;
			case 'R':
				{
				alt6 = 6;
				}
				break;
			case 'T':
				{
				alt6 = 11;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 6, 0, input, 1);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(6); }
			switch (alt6)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:201:7: 'ADDR'
				{
				DebugLocation(201, 7);
				Match("ADDR"); 


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:202:7: 'SUBR'
				{
				DebugLocation(202, 7);
				Match("SUBR"); 


				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:203:7: 'COMPR'
				{
				DebugLocation(203, 7);
				Match("COMPR"); 


				}
				break;
			case 4:
				DebugEnterAlt(4);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:204:7: 'MULR'
				{
				DebugLocation(204, 7);
				Match("MULR"); 


				}
				break;
			case 5:
				DebugEnterAlt(5);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:205:7: 'DIVR'
				{
				DebugLocation(205, 7);
				Match("DIVR"); 


				}
				break;
			case 6:
				DebugEnterAlt(6);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:206:7: 'RMO'
				{
				DebugLocation(206, 7);
				Match("RMO"); 


				}
				break;
			case 7:
				DebugEnterAlt(7);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:207:7: 'SHIFTL'
				{
				DebugLocation(207, 7);
				Match("SHIFTL"); 


				}
				break;
			case 8:
				DebugEnterAlt(8);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:208:7: 'SHIFTR'
				{
				DebugLocation(208, 7);
				Match("SHIFTR"); 


				}
				break;
			case 9:
				DebugEnterAlt(9);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:209:7: 'SVC'
				{
				DebugLocation(209, 7);
				Match("SVC"); 


				}
				break;
			case 10:
				DebugEnterAlt(10);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:210:7: 'CLEAR'
				{
				DebugLocation(210, 7);
				Match("CLEAR"); 


				}
				break;
			case 11:
				DebugEnterAlt(11);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:211:7: 'TIXR'
				{
				DebugLocation(211, 7);
				Match("TIXR"); 


				}
				break;

			}
		}
		finally
		{
			TraceOut("F2_INSTR", 16);
			LeaveRule("F2_INSTR", 16);
			LeaveRule_F2_INSTR();
		}
	}
	// $ANTLR end "F2_INSTR"

	partial void EnterRule_F34_INSTR();
	partial void LeaveRule_F34_INSTR();

	// $ANTLR start "F34_INSTR"
	[GrammarRule("F34_INSTR")]
	private void mF34_INSTR()
	{
		EnterRule_F34_INSTR();
		EnterRule("F34_INSTR", 17);
		TraceIn("F34_INSTR", 17);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:215:5: ( 'ADD' | 'ADDF' | 'AND' | 'COMP' | 'COMPF' | 'DIV' | 'DIVF' | 'J' | 'JEQ' | 'JGT' | 'JLT' | 'JSUB' | 'LDA' | 'LDB' | 'LDCH' | 'LDF' | 'LDL' | 'LDS' | 'LDT' | 'LDX' | 'MUL' | 'MULF' | 'MULR' | 'OR' | 'RD' | 'RSUB' | 'SSK' | 'STA' | 'STB' | 'STCH' | 'STF' | 'STI' | 'STL' | 'STS' | 'STSW' | 'STT' | 'STX' | 'SUB' | 'SUBF' | 'TIX' | 'WD' )
			int alt7=41;
			try { DebugEnterDecision(7, false);
			try
			{
				alt7 = dfa7.Predict(input);
			}
			catch (NoViableAltException nvae)
			{
				DebugRecognitionException(nvae);
				throw;
			}
			} finally { DebugExitDecision(7); }
			switch (alt7)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:215:7: 'ADD'
				{
				DebugLocation(215, 7);
				Match("ADD"); 


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:216:7: 'ADDF'
				{
				DebugLocation(216, 7);
				Match("ADDF"); 


				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:217:7: 'AND'
				{
				DebugLocation(217, 7);
				Match("AND"); 


				}
				break;
			case 4:
				DebugEnterAlt(4);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:218:7: 'COMP'
				{
				DebugLocation(218, 7);
				Match("COMP"); 


				}
				break;
			case 5:
				DebugEnterAlt(5);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:219:7: 'COMPF'
				{
				DebugLocation(219, 7);
				Match("COMPF"); 


				}
				break;
			case 6:
				DebugEnterAlt(6);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:220:7: 'DIV'
				{
				DebugLocation(220, 7);
				Match("DIV"); 


				}
				break;
			case 7:
				DebugEnterAlt(7);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:221:7: 'DIVF'
				{
				DebugLocation(221, 7);
				Match("DIVF"); 


				}
				break;
			case 8:
				DebugEnterAlt(8);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:222:7: 'J'
				{
				DebugLocation(222, 7);
				Match('J'); 

				}
				break;
			case 9:
				DebugEnterAlt(9);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:223:7: 'JEQ'
				{
				DebugLocation(223, 7);
				Match("JEQ"); 


				}
				break;
			case 10:
				DebugEnterAlt(10);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:224:7: 'JGT'
				{
				DebugLocation(224, 7);
				Match("JGT"); 


				}
				break;
			case 11:
				DebugEnterAlt(11);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:225:7: 'JLT'
				{
				DebugLocation(225, 7);
				Match("JLT"); 


				}
				break;
			case 12:
				DebugEnterAlt(12);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:226:7: 'JSUB'
				{
				DebugLocation(226, 7);
				Match("JSUB"); 


				}
				break;
			case 13:
				DebugEnterAlt(13);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:227:7: 'LDA'
				{
				DebugLocation(227, 7);
				Match("LDA"); 


				}
				break;
			case 14:
				DebugEnterAlt(14);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:228:7: 'LDB'
				{
				DebugLocation(228, 7);
				Match("LDB"); 


				}
				break;
			case 15:
				DebugEnterAlt(15);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:229:7: 'LDCH'
				{
				DebugLocation(229, 7);
				Match("LDCH"); 


				}
				break;
			case 16:
				DebugEnterAlt(16);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:230:7: 'LDF'
				{
				DebugLocation(230, 7);
				Match("LDF"); 


				}
				break;
			case 17:
				DebugEnterAlt(17);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:231:7: 'LDL'
				{
				DebugLocation(231, 7);
				Match("LDL"); 


				}
				break;
			case 18:
				DebugEnterAlt(18);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:232:7: 'LDS'
				{
				DebugLocation(232, 7);
				Match("LDS"); 


				}
				break;
			case 19:
				DebugEnterAlt(19);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:233:7: 'LDT'
				{
				DebugLocation(233, 7);
				Match("LDT"); 


				}
				break;
			case 20:
				DebugEnterAlt(20);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:234:7: 'LDX'
				{
				DebugLocation(234, 7);
				Match("LDX"); 


				}
				break;
			case 21:
				DebugEnterAlt(21);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:235:7: 'MUL'
				{
				DebugLocation(235, 7);
				Match("MUL"); 


				}
				break;
			case 22:
				DebugEnterAlt(22);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:236:7: 'MULF'
				{
				DebugLocation(236, 7);
				Match("MULF"); 


				}
				break;
			case 23:
				DebugEnterAlt(23);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:237:7: 'MULR'
				{
				DebugLocation(237, 7);
				Match("MULR"); 


				}
				break;
			case 24:
				DebugEnterAlt(24);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:238:7: 'OR'
				{
				DebugLocation(238, 7);
				Match("OR"); 


				}
				break;
			case 25:
				DebugEnterAlt(25);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:239:7: 'RD'
				{
				DebugLocation(239, 7);
				Match("RD"); 


				}
				break;
			case 26:
				DebugEnterAlt(26);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:240:7: 'RSUB'
				{
				DebugLocation(240, 7);
				Match("RSUB"); 


				}
				break;
			case 27:
				DebugEnterAlt(27);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:241:7: 'SSK'
				{
				DebugLocation(241, 7);
				Match("SSK"); 


				}
				break;
			case 28:
				DebugEnterAlt(28);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:242:7: 'STA'
				{
				DebugLocation(242, 7);
				Match("STA"); 


				}
				break;
			case 29:
				DebugEnterAlt(29);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:243:7: 'STB'
				{
				DebugLocation(243, 7);
				Match("STB"); 


				}
				break;
			case 30:
				DebugEnterAlt(30);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:244:7: 'STCH'
				{
				DebugLocation(244, 7);
				Match("STCH"); 


				}
				break;
			case 31:
				DebugEnterAlt(31);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:245:7: 'STF'
				{
				DebugLocation(245, 7);
				Match("STF"); 


				}
				break;
			case 32:
				DebugEnterAlt(32);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:246:7: 'STI'
				{
				DebugLocation(246, 7);
				Match("STI"); 


				}
				break;
			case 33:
				DebugEnterAlt(33);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:247:7: 'STL'
				{
				DebugLocation(247, 7);
				Match("STL"); 


				}
				break;
			case 34:
				DebugEnterAlt(34);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:248:7: 'STS'
				{
				DebugLocation(248, 7);
				Match("STS"); 


				}
				break;
			case 35:
				DebugEnterAlt(35);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:249:7: 'STSW'
				{
				DebugLocation(249, 7);
				Match("STSW"); 


				}
				break;
			case 36:
				DebugEnterAlt(36);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:250:7: 'STT'
				{
				DebugLocation(250, 7);
				Match("STT"); 


				}
				break;
			case 37:
				DebugEnterAlt(37);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:251:7: 'STX'
				{
				DebugLocation(251, 7);
				Match("STX"); 


				}
				break;
			case 38:
				DebugEnterAlt(38);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:252:7: 'SUB'
				{
				DebugLocation(252, 7);
				Match("SUB"); 


				}
				break;
			case 39:
				DebugEnterAlt(39);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:253:7: 'SUBF'
				{
				DebugLocation(253, 7);
				Match("SUBF"); 


				}
				break;
			case 40:
				DebugEnterAlt(40);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:254:7: 'TIX'
				{
				DebugLocation(254, 7);
				Match("TIX"); 


				}
				break;
			case 41:
				DebugEnterAlt(41);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:255:7: 'WD'
				{
				DebugLocation(255, 7);
				Match("WD"); 


				}
				break;

			}
		}
		finally
		{
			TraceOut("F34_INSTR", 17);
			LeaveRule("F34_INSTR", 17);
			LeaveRule_F34_INSTR();
		}
	}
	// $ANTLR end "F34_INSTR"

	partial void EnterRule_F1CODOP();
	partial void LeaveRule_F1CODOP();

	// $ANTLR start "F1CODOP"
	[GrammarRule("F1CODOP")]
	private void mF1CODOP()
	{
		EnterRule_F1CODOP();
		EnterRule("F1CODOP", 18);
		TraceIn("F1CODOP", 18);
		try
		{
			int _type = F1CODOP;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:258:10: ( F1_INSTR )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:258:12: F1_INSTR
			{
			DebugLocation(258, 12);
			mF1_INSTR(); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("F1CODOP", 18);
			LeaveRule("F1CODOP", 18);
			LeaveRule_F1CODOP();
		}
	}
	// $ANTLR end "F1CODOP"

	partial void EnterRule_F2CODOP();
	partial void LeaveRule_F2CODOP();

	// $ANTLR start "F2CODOP"
	[GrammarRule("F2CODOP")]
	private void mF2CODOP()
	{
		EnterRule_F2CODOP();
		EnterRule("F2CODOP", 19);
		TraceIn("F2CODOP", 19);
		try
		{
			int _type = F2CODOP;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:259:10: ( F2_INSTR )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:259:12: F2_INSTR
			{
			DebugLocation(259, 12);
			mF2_INSTR(); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("F2CODOP", 19);
			LeaveRule("F2CODOP", 19);
			LeaveRule_F2CODOP();
		}
	}
	// $ANTLR end "F2CODOP"

	partial void EnterRule_F34CODOP();
	partial void LeaveRule_F34CODOP();

	// $ANTLR start "F34CODOP"
	[GrammarRule("F34CODOP")]
	private void mF34CODOP()
	{
		EnterRule_F34CODOP();
		EnterRule("F34CODOP", 20);
		TraceIn("F34CODOP", 20);
		try
		{
			int _type = F34CODOP;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:260:10: ( F34_INSTR )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:260:12: F34_INSTR
			{
			DebugLocation(260, 12);
			mF34_INSTR(); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("F34CODOP", 20);
			LeaveRule("F34CODOP", 20);
			LeaveRule_F34CODOP();
		}
	}
	// $ANTLR end "F34CODOP"

	partial void EnterRule_NUM();
	partial void LeaveRule_NUM();

	// $ANTLR start "NUM"
	[GrammarRule("NUM")]
	private void mNUM()
	{
		EnterRule_NUM();
		EnterRule("NUM", 21);
		TraceIn("NUM", 21);
		try
		{
			int _type = NUM;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:264:5: ( ( '0' .. '9' )+ )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:264:7: ( '0' .. '9' )+
			{
			DebugLocation(264, 7);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:264:7: ( '0' .. '9' )+
			int cnt8=0;
			try { DebugEnterSubRule(8);
			while (true)
			{
				int alt8=2;
				try { DebugEnterDecision(8, false);
				int LA8_1 = input.LA(1);

				if (((LA8_1>='0' && LA8_1<='9')))
				{
					alt8 = 1;
				}


				} finally { DebugExitDecision(8); }
				switch (alt8)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:
					{
					DebugLocation(264, 7);
					input.Consume();


					}
					break;

				default:
					if (cnt8 >= 1)
						goto loop8;

					EarlyExitException eee8 = new EarlyExitException( 8, input );
					DebugRecognitionException(eee8);
					throw eee8;
				}
				cnt8++;
			}
			loop8:
				;

			} finally { DebugExitSubRule(8); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("NUM", 21);
			LeaveRule("NUM", 21);
			LeaveRule_NUM();
		}
	}
	// $ANTLR end "NUM"

	partial void EnterRule_CONSTHEX();
	partial void LeaveRule_CONSTHEX();

	// $ANTLR start "CONSTHEX"
	[GrammarRule("CONSTHEX")]
	private void mCONSTHEX()
	{
		EnterRule_CONSTHEX();
		EnterRule("CONSTHEX", 22);
		TraceIn("CONSTHEX", 22);
		try
		{
			int _type = CONSTHEX;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:269:5: ( '0x' ( '0' .. '9' | 'a' .. 'f' | 'A' .. 'F' )+ )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:269:7: '0x' ( '0' .. '9' | 'a' .. 'f' | 'A' .. 'F' )+
			{
			DebugLocation(269, 7);
			Match("0x"); 

			DebugLocation(269, 12);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:269:12: ( '0' .. '9' | 'a' .. 'f' | 'A' .. 'F' )+
			int cnt9=0;
			try { DebugEnterSubRule(9);
			while (true)
			{
				int alt9=2;
				try { DebugEnterDecision(9, false);
				int LA9_1 = input.LA(1);

				if (((LA9_1>='0' && LA9_1<='9')||(LA9_1>='A' && LA9_1<='F')||(LA9_1>='a' && LA9_1<='f')))
				{
					alt9 = 1;
				}


				} finally { DebugExitDecision(9); }
				switch (alt9)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:
					{
					DebugLocation(269, 12);
					input.Consume();


					}
					break;

				default:
					if (cnt9 >= 1)
						goto loop9;

					EarlyExitException eee9 = new EarlyExitException( 9, input );
					DebugRecognitionException(eee9);
					throw eee9;
				}
				cnt9++;
			}
			loop9:
				;

			} finally { DebugExitSubRule(9); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("CONSTHEX", 22);
			LeaveRule("CONSTHEX", 22);
			LeaveRule_CONSTHEX();
		}
	}
	// $ANTLR end "CONSTHEX"

	partial void EnterRule_HEXSUF();
	partial void LeaveRule_HEXSUF();

	// $ANTLR start "HEXSUF"
	[GrammarRule("HEXSUF")]
	private void mHEXSUF()
	{
		EnterRule_HEXSUF();
		EnterRule("HEXSUF", 23);
		TraceIn("HEXSUF", 23);
		try
		{
			int _type = HEXSUF;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:274:5: ( ( '0' .. '9' | 'a' .. 'f' | 'A' .. 'F' )+ ( 'h' | 'H' ) )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:274:7: ( '0' .. '9' | 'a' .. 'f' | 'A' .. 'F' )+ ( 'h' | 'H' )
			{
			DebugLocation(274, 7);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:274:7: ( '0' .. '9' | 'a' .. 'f' | 'A' .. 'F' )+
			int cnt10=0;
			try { DebugEnterSubRule(10);
			while (true)
			{
				int alt10=2;
				try { DebugEnterDecision(10, false);
				int LA10_1 = input.LA(1);

				if (((LA10_1>='0' && LA10_1<='9')||(LA10_1>='A' && LA10_1<='F')||(LA10_1>='a' && LA10_1<='f')))
				{
					alt10 = 1;
				}


				} finally { DebugExitDecision(10); }
				switch (alt10)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:
					{
					DebugLocation(274, 7);
					input.Consume();


					}
					break;

				default:
					if (cnt10 >= 1)
						goto loop10;

					EarlyExitException eee10 = new EarlyExitException( 10, input );
					DebugRecognitionException(eee10);
					throw eee10;
				}
				cnt10++;
			}
			loop10:
				;

			} finally { DebugExitSubRule(10); }

			DebugLocation(274, 42);
			if (input.LA(1)=='H'||input.LA(1)=='h')
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("HEXSUF", 23);
			LeaveRule("HEXSUF", 23);
			LeaveRule_HEXSUF();
		}
	}
	// $ANTLR end "HEXSUF"

	partial void EnterRule_CONSTCAD();
	partial void LeaveRule_CONSTCAD();

	// $ANTLR start "CONSTCAD"
	[GrammarRule("CONSTCAD")]
	private void mCONSTCAD()
	{
		EnterRule_CONSTCAD();
		EnterRule("CONSTCAD", 24);
		TraceIn("CONSTCAD", 24);
		try
		{
			int _type = CONSTCAD;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:279:5: ( '\"' ( '\\\\' . |~ ( '\\\"' | '\\\\' ) )* '\"' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:279:7: '\"' ( '\\\\' . |~ ( '\\\"' | '\\\\' ) )* '\"'
			{
			DebugLocation(279, 7);
			Match('\"'); 
			DebugLocation(279, 11);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:279:11: ( '\\\\' . |~ ( '\\\"' | '\\\\' ) )*
			try { DebugEnterSubRule(11);
			while (true)
			{
				int alt11=3;
				try { DebugEnterDecision(11, false);
				int LA11_1 = input.LA(1);

				if ((LA11_1=='\\'))
				{
					alt11 = 1;
				}
				else if (((LA11_1>='\u0000' && LA11_1<='!')||(LA11_1>='#' && LA11_1<='[')||(LA11_1>=']' && LA11_1<='\uFFFF')))
				{
					alt11 = 2;
				}


				} finally { DebugExitDecision(11); }
				switch ( alt11 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:279:13: '\\\\' .
					{
					DebugLocation(279, 13);
					Match('\\'); 
					DebugLocation(279, 18);
					MatchAny(); 

					}
					break;
				case 2:
					DebugEnterAlt(2);
					// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:279:22: ~ ( '\\\"' | '\\\\' )
					{
					DebugLocation(279, 22);
					input.Consume();


					}
					break;

				default:
					goto loop11;
				}
			}

			loop11:
				;

			} finally { DebugExitSubRule(11); }

			DebugLocation(279, 38);
			Match('\"'); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("CONSTCAD", 24);
			LeaveRule("CONSTCAD", 24);
			LeaveRule_CONSTCAD();
		}
	}
	// $ANTLR end "CONSTCAD"

	partial void EnterRule_ID();
	partial void LeaveRule_ID();

	// $ANTLR start "ID"
	[GrammarRule("ID")]
	private void mID()
	{
		EnterRule_ID();
		EnterRule("ID", 25);
		TraceIn("ID", 25);
		try
		{
			int _type = ID;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:284:5: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )* )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:284:7: ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*
			{
			DebugLocation(284, 7);
			if ((input.LA(1)>='A' && input.LA(1)<='Z')||input.LA(1)=='_'||(input.LA(1)>='a' && input.LA(1)<='z'))
			{
				input.Consume();
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				Recover(mse);
				throw mse;
			}

			DebugLocation(285, 7);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:285:7: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*
			try { DebugEnterSubRule(12);
			while (true)
			{
				int alt12=2;
				try { DebugEnterDecision(12, false);
				int LA12_1 = input.LA(1);

				if (((LA12_1>='0' && LA12_1<='9')||(LA12_1>='A' && LA12_1<='Z')||LA12_1=='_'||(LA12_1>='a' && LA12_1<='z')))
				{
					alt12 = 1;
				}


				} finally { DebugExitDecision(12); }
				switch ( alt12 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:
					{
					DebugLocation(285, 7);
					input.Consume();


					}
					break;

				default:
					goto loop12;
				}
			}

			loop12:
				;

			} finally { DebugExitSubRule(12); }


			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("ID", 25);
			LeaveRule("ID", 25);
			LeaveRule_ID();
		}
	}
	// $ANTLR end "ID"

	partial void EnterRule_CHCONST();
	partial void LeaveRule_CHCONST();

	// $ANTLR start "CHCONST"
	[GrammarRule("CHCONST")]
	private void mCHCONST()
	{
		EnterRule_CHCONST();
		EnterRule("CHCONST", 26);
		TraceIn("CHCONST", 26);
		try
		{
			int _type = CHCONST;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:290:5: ( 'C' '\\'' (~ ( '\\'' | '\\r' | '\\n' ) )* '\\'' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:290:7: 'C' '\\'' (~ ( '\\'' | '\\r' | '\\n' ) )* '\\''
			{
			DebugLocation(290, 7);
			Match('C'); 
			DebugLocation(290, 11);
			Match('\''); 
			DebugLocation(290, 16);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:290:16: (~ ( '\\'' | '\\r' | '\\n' ) )*
			try { DebugEnterSubRule(13);
			while (true)
			{
				int alt13=2;
				try { DebugEnterDecision(13, false);
				int LA13_1 = input.LA(1);

				if (((LA13_1>='\u0000' && LA13_1<='\t')||(LA13_1>='\u000B' && LA13_1<='\f')||(LA13_1>='\u000E' && LA13_1<='&')||(LA13_1>='(' && LA13_1<='\uFFFF')))
				{
					alt13 = 1;
				}


				} finally { DebugExitDecision(13); }
				switch ( alt13 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:
					{
					DebugLocation(290, 16);
					input.Consume();


					}
					break;

				default:
					goto loop13;
				}
			}

			loop13:
				;

			} finally { DebugExitSubRule(13); }

			DebugLocation(290, 43);
			Match('\''); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("CHCONST", 26);
			LeaveRule("CHCONST", 26);
			LeaveRule_CHCONST();
		}
	}
	// $ANTLR end "CHCONST"

	partial void EnterRule_HEXCONST();
	partial void LeaveRule_HEXCONST();

	// $ANTLR start "HEXCONST"
	[GrammarRule("HEXCONST")]
	private void mHEXCONST()
	{
		EnterRule_HEXCONST();
		EnterRule("HEXCONST", 27);
		TraceIn("HEXCONST", 27);
		try
		{
			int _type = HEXCONST;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:295:5: ( 'X' '\\'' ( ( '0' .. '9' ) | ( 'a' .. 'f' ) | ( 'A' .. 'F' ) )+ '\\'' )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:295:7: 'X' '\\'' ( ( '0' .. '9' ) | ( 'a' .. 'f' ) | ( 'A' .. 'F' ) )+ '\\''
			{
			DebugLocation(295, 7);
			Match('X'); 
			DebugLocation(295, 11);
			Match('\''); 
			DebugLocation(295, 16);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:295:16: ( ( '0' .. '9' ) | ( 'a' .. 'f' ) | ( 'A' .. 'F' ) )+
			int cnt14=0;
			try { DebugEnterSubRule(14);
			while (true)
			{
				int alt14=2;
				try { DebugEnterDecision(14, false);
				int LA14_1 = input.LA(1);

				if (((LA14_1>='0' && LA14_1<='9')||(LA14_1>='A' && LA14_1<='F')||(LA14_1>='a' && LA14_1<='f')))
				{
					alt14 = 1;
				}


				} finally { DebugExitDecision(14); }
				switch (alt14)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:
					{
					DebugLocation(295, 16);
					input.Consume();


					}
					break;

				default:
					if (cnt14 >= 1)
						goto loop14;

					EarlyExitException eee14 = new EarlyExitException( 14, input );
					DebugRecognitionException(eee14);
					throw eee14;
				}
				cnt14++;
			}
			loop14:
				;

			} finally { DebugExitSubRule(14); }

			DebugLocation(295, 58);
			Match('\''); 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("HEXCONST", 27);
			LeaveRule("HEXCONST", 27);
			LeaveRule_HEXCONST();
		}
	}
	// $ANTLR end "HEXCONST"

	partial void EnterRule_WS();
	partial void LeaveRule_WS();

	// $ANTLR start "WS"
	[GrammarRule("WS")]
	private void mWS()
	{
		EnterRule_WS();
		EnterRule("WS", 28);
		TraceIn("WS", 28);
		try
		{
			int _type = WS;
			int _channel = DefaultTokenChannel;
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:300:5: ( ( ' ' | '\\t' )+ )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:300:7: ( ' ' | '\\t' )+
			{
			DebugLocation(300, 7);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:300:7: ( ' ' | '\\t' )+
			int cnt15=0;
			try { DebugEnterSubRule(15);
			while (true)
			{
				int alt15=2;
				try { DebugEnterDecision(15, false);
				int LA15_1 = input.LA(1);

				if ((LA15_1=='\t'||LA15_1==' '))
				{
					alt15 = 1;
				}


				} finally { DebugExitDecision(15); }
				switch (alt15)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:
					{
					DebugLocation(300, 7);
					input.Consume();


					}
					break;

				default:
					if (cnt15 >= 1)
						goto loop15;

					EarlyExitException eee15 = new EarlyExitException( 15, input );
					DebugRecognitionException(eee15);
					throw eee15;
				}
				cnt15++;
			}
			loop15:
				;

			} finally { DebugExitSubRule(15); }

			DebugLocation(300, 21);
			 _channel = Hidden; 

			}

			state.type = _type;
			state.channel = _channel;
		}
		finally
		{
			TraceOut("WS", 28);
			LeaveRule("WS", 28);
			LeaveRule_WS();
		}
	}
	// $ANTLR end "WS"

	public override void mTokens()
	{
		// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:8: ( T__33 | START | END | BYTE | WORD | RESB | RESW | BASE | FINL | REG | INDICE | PLUS | AT | NUMERAL | F1CODOP | F2CODOP | F34CODOP | NUM | CONSTHEX | HEXSUF | CONSTCAD | ID | CHCONST | HEXCONST | WS )
		int alt16=25;
		try { DebugEnterDecision(16, false);
		try
		{
			alt16 = dfa16.Predict(input);
		}
		catch (NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
			throw;
		}
		} finally { DebugExitDecision(16); }
		switch (alt16)
		{
		case 1:
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:10: T__33
			{
			DebugLocation(1, 10);
			mT__33(); 

			}
			break;
		case 2:
			DebugEnterAlt(2);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:16: START
			{
			DebugLocation(1, 16);
			mSTART(); 

			}
			break;
		case 3:
			DebugEnterAlt(3);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:22: END
			{
			DebugLocation(1, 22);
			mEND(); 

			}
			break;
		case 4:
			DebugEnterAlt(4);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:26: BYTE
			{
			DebugLocation(1, 26);
			mBYTE(); 

			}
			break;
		case 5:
			DebugEnterAlt(5);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:31: WORD
			{
			DebugLocation(1, 31);
			mWORD(); 

			}
			break;
		case 6:
			DebugEnterAlt(6);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:36: RESB
			{
			DebugLocation(1, 36);
			mRESB(); 

			}
			break;
		case 7:
			DebugEnterAlt(7);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:41: RESW
			{
			DebugLocation(1, 41);
			mRESW(); 

			}
			break;
		case 8:
			DebugEnterAlt(8);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:46: BASE
			{
			DebugLocation(1, 46);
			mBASE(); 

			}
			break;
		case 9:
			DebugEnterAlt(9);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:51: FINL
			{
			DebugLocation(1, 51);
			mFINL(); 

			}
			break;
		case 10:
			DebugEnterAlt(10);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:56: REG
			{
			DebugLocation(1, 56);
			mREG(); 

			}
			break;
		case 11:
			DebugEnterAlt(11);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:60: INDICE
			{
			DebugLocation(1, 60);
			mINDICE(); 

			}
			break;
		case 12:
			DebugEnterAlt(12);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:67: PLUS
			{
			DebugLocation(1, 67);
			mPLUS(); 

			}
			break;
		case 13:
			DebugEnterAlt(13);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:72: AT
			{
			DebugLocation(1, 72);
			mAT(); 

			}
			break;
		case 14:
			DebugEnterAlt(14);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:75: NUMERAL
			{
			DebugLocation(1, 75);
			mNUMERAL(); 

			}
			break;
		case 15:
			DebugEnterAlt(15);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:83: F1CODOP
			{
			DebugLocation(1, 83);
			mF1CODOP(); 

			}
			break;
		case 16:
			DebugEnterAlt(16);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:91: F2CODOP
			{
			DebugLocation(1, 91);
			mF2CODOP(); 

			}
			break;
		case 17:
			DebugEnterAlt(17);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:99: F34CODOP
			{
			DebugLocation(1, 99);
			mF34CODOP(); 

			}
			break;
		case 18:
			DebugEnterAlt(18);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:108: NUM
			{
			DebugLocation(1, 108);
			mNUM(); 

			}
			break;
		case 19:
			DebugEnterAlt(19);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:112: CONSTHEX
			{
			DebugLocation(1, 112);
			mCONSTHEX(); 

			}
			break;
		case 20:
			DebugEnterAlt(20);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:121: HEXSUF
			{
			DebugLocation(1, 121);
			mHEXSUF(); 

			}
			break;
		case 21:
			DebugEnterAlt(21);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:128: CONSTCAD
			{
			DebugLocation(1, 128);
			mCONSTCAD(); 

			}
			break;
		case 22:
			DebugEnterAlt(22);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:137: ID
			{
			DebugLocation(1, 137);
			mID(); 

			}
			break;
		case 23:
			DebugEnterAlt(23);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:140: CHCONST
			{
			DebugLocation(1, 140);
			mCHCONST(); 

			}
			break;
		case 24:
			DebugEnterAlt(24);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:148: HEXCONST
			{
			DebugLocation(1, 148);
			mHEXCONST(); 

			}
			break;
		case 25:
			DebugEnterAlt(25);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:1:157: WS
			{
			DebugLocation(1, 157);
			mWS(); 

			}
			break;

		}

	}


	#region DFA
	DFA7 dfa7;
	DFA16 dfa16;

	protected override void InitDFAs()
	{
		base.InitDFAs();
		dfa7 = new DFA7(this);
		dfa16 = new DFA16(this);
	}

	private class DFA7 : DFA
	{
		private const string DFA7_eotS =
			"\x4\xFFFF\x1\x14\x17\xFFFF\x1\x33\x1\xFFFF\x1\x36\x8\xFFFF\x1\x39\x6"+
			"\xFFFF\x1\x3B\x2\xFFFF\x1\x3D\x2\xFFFF\x1\x3F\xB\xFFFF";
		private const string DFA7_eofS =
			"\x40\xFFFF";
		private const string DFA7_minS =
			"\x1\x41\x1\x44\x1\x4F\x1\x49\x1\x45\x1\x44\x1\x55\x1\xFFFF\x1\x44\x1"+
			"\x53\x2\xFFFF\x1\x44\x1\xFFFF\x1\x4D\x1\x56\x5\xFFFF\x1\x41\x1\x4C\x3"+
			"\xFFFF\x1\x41\x1\x42\x1\x46\x1\x50\x1\x46\x8\xFFFF\x1\x46\x6\xFFFF\x1"+
			"\x57\x2\xFFFF\x1\x46\x2\xFFFF\x1\x46\xB\xFFFF";
		private const string DFA7_maxS =
			"\x1\x57\x1\x4E\x1\x4F\x1\x49\x1\x53\x1\x44\x1\x55\x1\xFFFF\x1\x53\x1"+
			"\x55\x2\xFFFF\x1\x44\x1\xFFFF\x1\x4D\x1\x56\x5\xFFFF\x1\x58\x1\x4C\x3"+
			"\xFFFF\x1\x58\x1\x42\x1\x46\x1\x50\x1\x46\x8\xFFFF\x1\x52\x6\xFFFF\x1"+
			"\x57\x2\xFFFF\x1\x46\x2\xFFFF\x1\x46\xB\xFFFF";
		private const string DFA7_acceptS =
			"\x7\xFFFF\x1\x18\x2\xFFFF\x1\x28\x1\x29\x1\xFFFF\x1\x3\x2\xFFFF\x1\x9"+
			"\x1\xA\x1\xB\x1\xC\x1\x8\x2\xFFFF\x1\x19\x1\x1A\x1\x1B\x5\xFFFF\x1\xD"+
			"\x1\xE\x1\xF\x1\x10\x1\x11\x1\x12\x1\x13\x1\x14\x1\xFFFF\x1\x1C\x1\x1D"+
			"\x1\x1E\x1\x1F\x1\x20\x1\x21\x1\xFFFF\x1\x24\x1\x25\x1\xFFFF\x1\x2\x1"+
			"\x1\x1\xFFFF\x1\x7\x1\x6\x1\x16\x1\x17\x1\x15\x1\x23\x1\x22\x1\x27\x1"+
			"\x26\x1\x5\x1\x4";
		private const string DFA7_specialS =
			"\x40\xFFFF}>";
		private static readonly string[] DFA7_transitionS =
			{
				"\x1\x1\x1\xFFFF\x1\x2\x1\x3\x5\xFFFF\x1\x4\x1\xFFFF\x1\x5\x1\x6\x1\xFFFF"+
				"\x1\x7\x2\xFFFF\x1\x8\x1\x9\x1\xA\x2\xFFFF\x1\xB",
				"\x1\xC\x9\xFFFF\x1\xD",
				"\x1\xE",
				"\x1\xF",
				"\x1\x10\x1\xFFFF\x1\x11\x4\xFFFF\x1\x12\x6\xFFFF\x1\x13",
				"\x1\x15",
				"\x1\x16",
				"",
				"\x1\x17\xE\xFFFF\x1\x18",
				"\x1\x19\x1\x1A\x1\x1B",
				"",
				"",
				"\x1\x1C",
				"",
				"\x1\x1D",
				"\x1\x1E",
				"",
				"",
				"",
				"",
				"",
				"\x1\x1F\x1\x20\x1\x21\x2\xFFFF\x1\x22\x5\xFFFF\x1\x23\x6\xFFFF\x1\x24"+
				"\x1\x25\x3\xFFFF\x1\x26",
				"\x1\x27",
				"",
				"",
				"",
				"\x1\x28\x1\x29\x1\x2A\x2\xFFFF\x1\x2B\x2\xFFFF\x1\x2C\x2\xFFFF\x1\x2D"+
				"\x6\xFFFF\x1\x2E\x1\x2F\x3\xFFFF\x1\x30",
				"\x1\x31",
				"\x1\x32",
				"\x1\x34",
				"\x1\x35",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"\x1\x37\xB\xFFFF\x1\x38",
				"",
				"",
				"",
				"",
				"",
				"",
				"\x1\x3A",
				"",
				"",
				"\x1\x3C",
				"",
				"",
				"\x1\x3E",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				"",
				""
			};

		private static readonly short[] DFA7_eot = DFA.UnpackEncodedString(DFA7_eotS);
		private static readonly short[] DFA7_eof = DFA.UnpackEncodedString(DFA7_eofS);
		private static readonly char[] DFA7_min = DFA.UnpackEncodedStringToUnsignedChars(DFA7_minS);
		private static readonly char[] DFA7_max = DFA.UnpackEncodedStringToUnsignedChars(DFA7_maxS);
		private static readonly short[] DFA7_accept = DFA.UnpackEncodedString(DFA7_acceptS);
		private static readonly short[] DFA7_special = DFA.UnpackEncodedString(DFA7_specialS);
		private static readonly short[][] DFA7_transition;

		static DFA7()
		{
			int numStates = DFA7_transitionS.Length;
			DFA7_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA7_transition[i] = DFA.UnpackEncodedString(DFA7_transitionS[i]);
			}
		}

		public DFA7( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 7;
			this.eot = DFA7_eot;
			this.eof = DFA7_eof;
			this.min = DFA7_min;
			this.max = DFA7_max;
			this.accept = DFA7_accept;
			this.special = DFA7_special;
			this.transition = DFA7_transition;
		}

		public override string Description { get { return "214:10: fragment F34_INSTR : ( 'ADD' | 'ADDF' | 'AND' | 'COMP' | 'COMPF' | 'DIV' | 'DIVF' | 'J' | 'JEQ' | 'JGT' | 'JLT' | 'JSUB' | 'LDA' | 'LDB' | 'LDCH' | 'LDF' | 'LDL' | 'LDS' | 'LDT' | 'LDX' | 'MUL' | 'MULF' | 'MULR' | 'OR' | 'RD' | 'RSUB' | 'SSK' | 'STA' | 'STB' | 'STCH' | 'STF' | 'STI' | 'STL' | 'STS' | 'STSW' | 'STT' | 'STX' | 'SUB' | 'SUBF' | 'TIX' | 'WD' );"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}

	private class DFA16 : DFA
	{
		private const string DFA16_eotS =
			"\x2\xFFFF\x1\x1C\x2\x25\x2\x1C\x1\xFFFF\x1\x25\x1\x1C\x3\xFFFF\x1\x25"+
			"\x3\x1C\x2\x25\x1\x1C\x1\x25\x1\x44\x2\x1C\x2\x48\x1\x1C\x3\xFFFF\x7"+
			"\x1C\x1\xFFFF\x1\x49\x4\x1C\x1\x44\x2\x1C\x1\x44\x3\x1C\x3\x61\x7\x1C"+
			"\x1\xFFFF\x2\x1C\x1\xFFFF\x4\x1C\x1\xFFFF\x1\x1C\x1\x44\x3\xFFFF\x2\x44"+
			"\x1\x1C\x6\x44\x1\x7B\x1\x44\x1\x1C\x1\x7F\x1\x44\x1\x80\x4\x1C\x1\x7F"+
			"\x1\x1C\x1\x7B\x1\x1C\x1\xFFFF\x2\x44\x1\x1C\x2\x7B\x1\x44\x2\x1C\x5"+
			"\x44\x1\x1C\x2\x44\x1\x1C\x5\x44\x1\x1C\x2\x44\x1\xFFFF\x1\x7F\x1\x44"+
			"\x1\x1C\x2\xFFFF\x1\x96\x1\x97\x1\x98\x1\x99\x1\x9A\x1\x44\x1\x1C\x1"+
			"\x7F\x1\x44\x1\x7B\x1\x7F\x1\x44\x1\x1C\x1\x7F\x1\x44\x1\x7F\x3\x44\x1"+
			"\x9F\x1\x1C\x5\xFFFF\x1\x7B\x1\x7F\x1\x44\x1\x7F\x1\xFFFF\x2\x7F";
		private const string DFA16_eofS =
			"\xA2\xFFFF";
		private const string DFA16_minS =
			"\x1\x9\x1\xFFFF\x1\x48\x2\x30\x2\x44\x1\xFFFF\x1\x30\x1\x58\x3\xFFFF"+
			"\x1\x30\x1\x4F\x2\x49\x1\x27\x1\x30\x1\x55\x1\x27\x1\x30\x1\x44\x1\x52"+
			"\x3\x30\x3\xFFFF\x1\x41\x1\x4F\x1\x42\x1\x49\x1\x43\x1\x4B\x1\x44\x1"+
			"\xFFFF\x2\x30\x1\x54\x1\x30\x1\x52\x1\x30\x1\x53\x1\x4F\x1\x30\x1\x55"+
			"\x1\x58\x1\x4F\x4\x30\x1\x44\x1\x52\x2\x4F\x1\x4D\x1\x45\x1\xFFFF\x1"+
			"\x56\x1\x4C\x1\xFFFF\x1\x51\x2\x54\x1\x55\x1\xFFFF\x1\x41\x1\x30\x3\xFFFF"+
			"\x2\x30\x1\x48\x8\x30\x1\x46\x3\x30\x2\x45\x1\x44\x1\x42\x1\x30\x1\x42"+
			"\x1\x30\x1\x41\x1\xFFFF\x2\x30\x1\x4D\x3\x30\x1\x50\x1\x41\x5\x30\x1"+
			"\x42\x2\x30\x1\x48\x5\x30\x1\x54\x2\x30\x1\xFFFF\x2\x30\x1\x54\x2\xFFFF"+
			"\x6\x30\x1\x54\x5\x30\x1\x52\x7\x30\x1\x4C\x5\xFFFF\x4\x30\x1\xFFFF\x2"+
			"\x30";
		private const string DFA16_maxS =
			"\x1\x7A\x1\xFFFF\x1\x56\x2\x7A\x1\x4F\x1\x53\x1\xFFFF\x1\x7A\x1\x5A\x3"+
			"\xFFFF\x1\x7A\x1\x4F\x2\x49\x2\x7A\x1\x55\x2\x7A\x1\x44\x1\x52\x1\x78"+
			"\x2\x68\x3\xFFFF\x1\x58\x1\x4F\x1\x42\x1\x49\x1\x43\x1\x4B\x1\x44\x1"+
			"\xFFFF\x1\x7A\x1\x68\x1\x54\x1\x68\x1\x52\x1\x7A\x1\x53\x1\x4F\x1\x7A"+
			"\x1\x55\x1\x58\x1\x4F\x3\x7A\x1\x68\x1\x44\x1\x52\x1\x4F\x1\x58\x1\x4D"+
			"\x1\x45\x1\xFFFF\x1\x56\x1\x4C\x1\xFFFF\x1\x51\x2\x54\x1\x55\x1\xFFFF"+
			"\x1\x58\x1\x7A\x3\xFFFF\x2\x7A\x1\x48\x8\x7A\x1\x46\x3\x7A\x2\x45\x1"+
			"\x44\x1\x57\x1\x7A\x1\x42\x1\x7A\x1\x41\x1\xFFFF\x2\x7A\x1\x4D\x3\x7A"+
			"\x1\x50\x1\x41\x5\x7A\x1\x42\x2\x7A\x1\x48\x5\x7A\x1\x54\x2\x7A\x1\xFFFF"+
			"\x2\x7A\x1\x54\x2\xFFFF\x6\x7A\x1\x54\x5\x7A\x1\x52\x7\x7A\x1\x52\x5"+
			"\xFFFF\x4\x7A\x1\xFFFF\x2\x7A";
		private const string DFA16_acceptS =
			"\x1\xFFFF\x1\x1\x5\xFFFF\x1\x9\x2\xFFFF\x1\xC\x1\xD\x1\xE\xE\xFFFF\x1"+
			"\x15\x1\x16\x1\x19\x7\xFFFF\x1\xA\x16\xFFFF\x1\x17\x2\xFFFF\x1\x18\x4"+
			"\xFFFF\x1\x11\x2\xFFFF\x1\x13\x1\x12\x1\x14\x17\xFFFF\x1\xB\x19\xFFFF"+
			"\x1\xF\x3\xFFFF\x1\x10\x1\x3\x15\xFFFF\x1\x4\x1\x8\x1\x5\x1\x6\x1\x7"+
			"\x4\xFFFF\x1\x2\x2\xFFFF";
		private const string DFA16_specialS =
			"\xA2\xFFFF}>";
		private static readonly string[] DFA16_transitionS =
			{
				"\x1\x1D\x1\x7\x2\xFFFF\x1\x7\x12\xFFFF\x1\x1D\x1\xFFFF\x1\x1B\x1\xC"+
				"\x7\xFFFF\x1\xA\x1\x1\x3\xFFFF\x1\x18\x9\x19\x1\xFFFF\x1\x7\x4\xFFFF"+
				"\x1\xB\x1\xD\x1\x4\x1\x11\x1\x12\x1\x3\x1\x8\x1\x1C\x1\xF\x1\x9\x1\x15"+
				"\x1\x1C\x1\x16\x1\x13\x1\xE\x1\x17\x2\x1C\x1\x6\x1\x2\x1\x10\x2\x1C"+
				"\x1\x5\x1\x14\x2\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x6\x1A\x14\x1C",
				"",
				"\x1\x21\x1\x1F\x9\xFFFF\x1\x23\x1\x1E\x1\x20\x1\x22",
				"\xA\x27\x7\xFFFF\x6\x27\x1\x1C\x1\x26\x5\x1C\x1\x24\xC\x1C\x4\xFFFF"+
				"\x1\x1C\x1\xFFFF\x6\x27\x1\x1C\x1\x26\x12\x1C",
				"\xA\x27\x7\xFFFF\x1\x29\x5\x27\x1\x1C\x1\x26\x10\x1C\x1\x28\x1\x1C"+
				"\x4\xFFFF\x1\x1C\x1\xFFFF\x6\x27\x1\x1C\x1\x26\x12\x1C",
				"\x1\x2B\xA\xFFFF\x1\x2A",
				"\x1\x2E\x1\x2C\x7\xFFFF\x1\x2D\x5\xFFFF\x1\x2F",
				"",
				"\xA\x27\x7\xFFFF\x6\x27\x1\x1C\x1\x26\x1\x30\x2\x1C\x1\x31\xE\x1C\x4"+
				"\xFFFF\x1\x1C\x1\xFFFF\x6\x27\x1\x1C\x1\x26\x12\x1C",
				"\x1\x32\x1\x33\x1\x34",
				"",
				"",
				"",
				"\xA\x27\x7\xFFFF\x3\x27\x1\x35\x2\x27\x1\x1C\x1\x26\x5\x1C\x1\x36\xC"+
				"\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x6\x27\x1\x1C\x1\x26\x12\x1C",
				"\x1\x37",
				"\x1\x38",
				"\x1\x39",
				"\x1\x3C\x8\xFFFF\xA\x27\x7\xFFFF\x6\x27\x1\x1C\x1\x26\x3\x1C\x1\x3B"+
				"\x2\x1C\x1\x3A\xB\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x6\x27\x1\x1C\x1\x26"+
				"\x12\x1C",
				"\xA\x27\x7\xFFFF\x6\x27\x1\x1C\x1\x26\x1\x3D\x11\x1C\x4\xFFFF\x1\x1C"+
				"\x1\xFFFF\x6\x27\x1\x1C\x1\x26\x12\x1C",
				"\x1\x3E",
				"\x1\x3F\x8\xFFFF\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A"+
				"\x1C",
				"\xA\x1C\x7\xFFFF\x4\x1C\x1\x40\x1\x1C\x1\x41\x4\x1C\x1\x42\x6\x1C\x1"+
				"\x43\x7\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\x1\x45",
				"\x1\x46",
				"\xA\x19\x7\xFFFF\x6\x49\x1\xFFFF\x1\x49\x18\xFFFF\x6\x49\x1\xFFFF\x1"+
				"\x49\xF\xFFFF\x1\x47",
				"\xA\x19\x7\xFFFF\x6\x49\x1\xFFFF\x1\x49\x18\xFFFF\x6\x49\x1\xFFFF\x1"+
				"\x49",
				"\xA\x27\x7\xFFFF\x6\x27\x1\xFFFF\x1\x26\x18\xFFFF\x6\x27\x1\xFFFF\x1"+
				"\x26",
				"",
				"",
				"",
				"\x1\x4A\x1\x4B\x1\x4C\x2\xFFFF\x1\x4D\x2\xFFFF\x1\x4E\x2\xFFFF\x1\x4F"+
				"\x6\xFFFF\x1\x50\x1\x51\x3\xFFFF\x1\x52",
				"\x1\x53",
				"\x1\x54",
				"\x1\x55",
				"\x1\x56",
				"\x1\x57",
				"\x1\x58",
				"",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x27\x7\xFFFF\x6\x27\x1\xFFFF\x1\x26\x18\xFFFF\x6\x27\x1\xFFFF\x1"+
				"\x26",
				"\x1\x59",
				"\xA\x27\x7\xFFFF\x6\x27\x1\xFFFF\x1\x26\xA\xFFFF\x1\x5A\xD\xFFFF\x6"+
				"\x27\x1\xFFFF\x1\x26",
				"\x1\x5B",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\x1\x5C",
				"\x1\x5D",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\x1\x5E",
				"\x1\x5F",
				"\x1\x60",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x27\x7\xFFFF\x3\x27\x1\x62\x2\x27\x1\xFFFF\x1\x26\x18\xFFFF\x6"+
				"\x27\x1\xFFFF\x1\x26",
				"\x1\x63",
				"\x1\x64",
				"\x1\x65",
				"\x1\x66\x8\xFFFF\x1\x67",
				"\x1\x68",
				"\x1\x69",
				"",
				"\x1\x6A",
				"\x1\x6B",
				"",
				"\x1\x6C",
				"\x1\x6D",
				"\x1\x6E",
				"\x1\x6F",
				"",
				"\x1\x70\x1\x71\x1\x72\x2\xFFFF\x1\x73\x5\xFFFF\x1\x74\x6\xFFFF\x1\x75"+
				"\x1\x76\x3\xFFFF\x1\x77",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"",
				"",
				"",
				"\xA\x1C\x7\xFFFF\x11\x1C\x1\x78\x8\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A"+
				"\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\x1\x79",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x16\x1C\x1\x7A\x3\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A"+
				"\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x5\x1C\x1\x7D\xB\x1C\x1\x7C\x8\x1C\x4\xFFFF\x1\x1C"+
				"\x1\xFFFF\x1A\x1C",
				"\x1\x7E",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\x1\x81",
				"\x1\x82",
				"\x1\x83",
				"\x1\x84\x14\xFFFF\x1\x85",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\x1\x86",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\x1\x87",
				"",
				"\xA\x27\x7\xFFFF\x5\x27\x1\x89\x1\x1C\x1\x26\x9\x1C\x1\x88\x8\x1C\x4"+
				"\xFFFF\x1\x1C\x1\xFFFF\x6\x27\x1\x1C\x1\x26\x12\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\x1\x8A",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x11\x1C\x1\x8B\x8\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A"+
				"\x1C",
				"\x1\x8C",
				"\x1\x8D",
				"\xA\x1C\x7\xFFFF\x5\x1C\x1\x8F\xB\x1C\x1\x8E\x8\x1C\x4\xFFFF\x1\x1C"+
				"\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x5\x1C\x1\x91\xB\x1C\x1\x90\x8\x1C\x4\xFFFF\x1\x1C"+
				"\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\x1\x92",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\x1\x93",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\x1\x94",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\x1\x95",
				"",
				"",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\x1\x9B",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x27\x7\xFFFF\x6\x27\x1\x1C\x1\x26\x12\x1C\x4\xFFFF\x1\x1C\x1\xFFFF"+
				"\x6\x27\x1\x1C\x1\x26\x12\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x5\x1C\x1\x9D\xB\x1C\x1\x9C\x8\x1C\x4\xFFFF\x1\x1C"+
				"\x1\xFFFF\x1A\x1C",
				"\x1\x9E",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\x1\xA0\x5\xFFFF\x1\xA1",
				"",
				"",
				"",
				"",
				"",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C",
				"\xA\x1C\x7\xFFFF\x1A\x1C\x4\xFFFF\x1\x1C\x1\xFFFF\x1A\x1C"
			};

		private static readonly short[] DFA16_eot = DFA.UnpackEncodedString(DFA16_eotS);
		private static readonly short[] DFA16_eof = DFA.UnpackEncodedString(DFA16_eofS);
		private static readonly char[] DFA16_min = DFA.UnpackEncodedStringToUnsignedChars(DFA16_minS);
		private static readonly char[] DFA16_max = DFA.UnpackEncodedStringToUnsignedChars(DFA16_maxS);
		private static readonly short[] DFA16_accept = DFA.UnpackEncodedString(DFA16_acceptS);
		private static readonly short[] DFA16_special = DFA.UnpackEncodedString(DFA16_specialS);
		private static readonly short[][] DFA16_transition;

		static DFA16()
		{
			int numStates = DFA16_transitionS.Length;
			DFA16_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA16_transition[i] = DFA.UnpackEncodedString(DFA16_transitionS[i]);
			}
		}

		public DFA16( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 16;
			this.eot = DFA16_eot;
			this.eof = DFA16_eof;
			this.min = DFA16_min;
			this.max = DFA16_max;
			this.accept = DFA16_accept;
			this.special = DFA16_special;
			this.transition = DFA16_transition;
		}

		public override string Description { get { return "1:1: Tokens : ( T__33 | START | END | BYTE | WORD | RESB | RESW | BASE | FINL | REG | INDICE | PLUS | AT | NUMERAL | F1CODOP | F2CODOP | F34CODOP | NUM | CONSTHEX | HEXSUF | CONSTCAD | ID | CHCONST | HEXCONST | WS );"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}


	#endregion

}
