//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.5.1 C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g 2025-03-04 15:33:16

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591
// CLS compliance checking will not be performed on 'type' because it is not visible from outside this assembly.
#pragma warning disable 3019


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;


using Antlr.Runtime.Tree;
using RewriteRuleITokenStream = Antlr.Runtime.Tree.RewriteRuleTokenStream;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.5.1")]
[System.CLSCompliant(false)]
public partial class Gram_SICXEParser : Antlr.Runtime.Parser
{
	internal static readonly string[] tokenNames = new string[] {
		"<invalid>", "<EOR>", "<DOWN>", "<UP>", "AT", "BASE", "BYTE", "CHCONST", "CONSTCAD", "CONSTHEX", "DIR", "END", "F1CODOP", "F1_INSTR", "F2CODOP", "F2_INSTR", "F34CODOP", "F34_INSTR", "FINL", "HEXCONST", "HEXSUF", "ID", "INDICE", "INSTR", "NUM", "NUMERAL", "PLUS", "REG", "RESB", "RESW", "START", "WORD", "WS", "','"
	};
	public const int EOF=-1;
	public const int T__33=33;
	public const int AT=4;
	public const int BASE=5;
	public const int BYTE=6;
	public const int CHCONST=7;
	public const int CONSTCAD=8;
	public const int CONSTHEX=9;
	public const int DIR=10;
	public const int END=11;
	public const int F1CODOP=12;
	public const int F1_INSTR=13;
	public const int F2CODOP=14;
	public const int F2_INSTR=15;
	public const int F34CODOP=16;
	public const int F34_INSTR=17;
	public const int FINL=18;
	public const int HEXCONST=19;
	public const int HEXSUF=20;
	public const int ID=21;
	public const int INDICE=22;
	public const int INSTR=23;
	public const int NUM=24;
	public const int NUMERAL=25;
	public const int PLUS=26;
	public const int REG=27;
	public const int RESB=28;
	public const int RESW=29;
	public const int START=30;
	public const int WORD=31;
	public const int WS=32;

	public Gram_SICXEParser(ITokenStream input)
		: this(input, new RecognizerSharedState())
	{
	}
	public Gram_SICXEParser(ITokenStream input, RecognizerSharedState state)
		: base(input, state)
	{
		ITreeAdaptor treeAdaptor = default(ITreeAdaptor);
		CreateTreeAdaptor(ref treeAdaptor);
		TreeAdaptor = treeAdaptor ?? new CommonTreeAdaptor();
		OnCreated();
	}
	// Implement this function in your helper file to use a custom tree adaptor
	partial void CreateTreeAdaptor(ref ITreeAdaptor adaptor);

	private ITreeAdaptor adaptor;

	public ITreeAdaptor TreeAdaptor
	{
		get
		{
			return adaptor;
		}

		set
		{
			this.adaptor = value;
		}
	}

	public override string[] TokenNames { get { return Gram_SICXEParser.tokenNames; } }
	public override string GrammarFileName { get { return "C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g"; } }


	partial void OnCreated();
	partial void EnterRule(string ruleName, int ruleIndex);
	partial void LeaveRule(string ruleName, int ruleIndex);

	#region Rules
	partial void EnterRule_programa();
	partial void LeaveRule_programa();
	// $ANTLR start "programa"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:17:8: public programa : inicio proposiciones fin ( FINL )? EOF ;
	[GrammarRule("programa")]
	public AstParserRuleReturnScope<object, IToken> programa()
	{
		EnterRule_programa();
		EnterRule("programa", 1);
		TraceIn("programa", 1);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken FINL4 = default(IToken);
		IToken EOF5 = default(IToken);
		AstParserRuleReturnScope<object, IToken> inicio1 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> proposiciones2 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> fin3 = default(AstParserRuleReturnScope<object, IToken>);

		object FINL4_tree = default(object);
		object EOF5_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "programa");
		DebugLocation(17, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:19:5: ( inicio proposiciones fin ( FINL )? EOF )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:19:7: inicio proposiciones fin ( FINL )? EOF
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(19, 7);
			PushFollow(Follow._inicio_in_programa73);
			inicio1=inicio();
			PopFollow();

			adaptor.AddChild(root_0, inicio1.Tree);
			DebugLocation(19, 14);
			PushFollow(Follow._proposiciones_in_programa75);
			proposiciones2=proposiciones();
			PopFollow();

			adaptor.AddChild(root_0, proposiciones2.Tree);
			DebugLocation(19, 28);
			PushFollow(Follow._fin_in_programa77);
			fin3=fin();
			PopFollow();

			adaptor.AddChild(root_0, fin3.Tree);
			DebugLocation(19, 32);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:19:32: ( FINL )?
			int alt1=2;
			try { DebugEnterSubRule(1);
			try { DebugEnterDecision(1, false);
			int LA1_1 = input.LA(1);

			if ((LA1_1==FINL))
			{
				alt1 = 1;
			}
			} finally { DebugExitDecision(1); }
			switch (alt1)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:19:33: FINL
				{
				DebugLocation(19, 33);
				FINL4=(IToken)Match(input,FINL,Follow._FINL_in_programa80); 
				FINL4_tree = (object)adaptor.Create(FINL4);
				adaptor.AddChild(root_0, FINL4_tree);

				}
				break;

			}
			} finally { DebugExitSubRule(1); }

			DebugLocation(19, 40);
			EOF5=(IToken)Match(input,EOF,Follow._EOF_in_programa84); 
			EOF5_tree = (object)adaptor.Create(EOF5);
			adaptor.AddChild(root_0, EOF5_tree);

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("programa", 1);
			LeaveRule("programa", 1);
			LeaveRule_programa();
		}
		DebugLocation(20, 4);
		} finally { DebugExitRule(GrammarFileName, "programa"); }
		return retval;

	}
	// $ANTLR end "programa"

	partial void EnterRule_inicio();
	partial void LeaveRule_inicio();
	// $ANTLR start "inicio"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:23:1: inicio : ( raiz | proposicion );
	[GrammarRule("inicio")]
	private AstParserRuleReturnScope<object, IToken> inicio()
	{
		EnterRule_inicio();
		EnterRule("inicio", 2);
		TraceIn("inicio", 2);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		AstParserRuleReturnScope<object, IToken> raiz6 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> proposicion7 = default(AstParserRuleReturnScope<object, IToken>);

		try { DebugEnterRule(GrammarFileName, "inicio");
		DebugLocation(23, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:24:5: ( raiz | proposicion )
			int alt2=2;
			try { DebugEnterDecision(2, false);
			int LA2_1 = input.LA(1);

			if ((LA2_1==ID))
			{
				int LA2_2 = input.LA(2);

				if ((LA2_2==START))
				{
					alt2 = 1;
				}
				else if (((LA2_2>=BASE && LA2_2<=BYTE)||LA2_2==F1CODOP||LA2_2==F2CODOP||LA2_2==F34CODOP||LA2_2==PLUS||(LA2_2>=RESB && LA2_2<=RESW)||LA2_2==WORD))
				{
					alt2 = 2;
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 2, 1, input, 2);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}
			else if (((LA2_1>=BASE && LA2_1<=BYTE)||LA2_1==F1CODOP||LA2_1==F2CODOP||LA2_1==F34CODOP||LA2_1==PLUS||(LA2_1>=RESB && LA2_1<=RESW)||LA2_1==WORD))
			{
				alt2 = 2;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 2, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(2); }
			switch (alt2)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:24:7: raiz
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(24, 7);
				PushFollow(Follow._raiz_in_inicio102);
				raiz6=raiz();
				PopFollow();

				adaptor.AddChild(root_0, raiz6.Tree);

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:25:7: proposicion
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(25, 7);
				PushFollow(Follow._proposicion_in_inicio110);
				proposicion7=proposicion();
				PopFollow();

				adaptor.AddChild(root_0, proposicion7.Tree);

				}
				break;

			}
			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("inicio", 2);
			LeaveRule("inicio", 2);
			LeaveRule_inicio();
		}
		DebugLocation(26, 4);
		} finally { DebugExitRule(GrammarFileName, "inicio"); }
		return retval;

	}
	// $ANTLR end "inicio"

	partial void EnterRule_raiz();
	partial void LeaveRule_raiz();
	// $ANTLR start "raiz"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:28:1: raiz : et= etiqueta s= START v= ( NUM | HEXSUF )? FINL -> ^( DIR $et $s ( $v)? ) ;
	[GrammarRule("raiz")]
	private AstParserRuleReturnScope<object, IToken> raiz()
	{
		EnterRule_raiz();
		EnterRule("raiz", 3);
		TraceIn("raiz", 3);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken s = default(IToken);
		IToken v = default(IToken);
		IToken FINL8 = default(IToken);
		AstParserRuleReturnScope<object, IToken> et = default(AstParserRuleReturnScope<object, IToken>);

		object s_tree = default(object);
		object v_tree = default(object);
		object FINL8_tree = default(object);
		RewriteRuleITokenStream stream_FINL=new RewriteRuleITokenStream(adaptor,"token FINL");
		RewriteRuleITokenStream stream_NUM=new RewriteRuleITokenStream(adaptor,"token NUM");
		RewriteRuleITokenStream stream_START=new RewriteRuleITokenStream(adaptor,"token START");
		RewriteRuleITokenStream stream_HEXSUF=new RewriteRuleITokenStream(adaptor,"token HEXSUF");
		RewriteRuleSubtreeStream stream_etiqueta=new RewriteRuleSubtreeStream(adaptor,"rule etiqueta");
		try { DebugEnterRule(GrammarFileName, "raiz");
		DebugLocation(28, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:29:5: (et= etiqueta s= START v= ( NUM | HEXSUF )? FINL -> ^( DIR $et $s ( $v)? ) )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:29:7: et= etiqueta s= START v= ( NUM | HEXSUF )? FINL
			{
			DebugLocation(29, 9);
			PushFollow(Follow._etiqueta_in_raiz129);
			et=etiqueta();
			PopFollow();

			stream_etiqueta.Add(et.Tree);
			DebugLocation(29, 20);
			s=(IToken)Match(input,START,Follow._START_in_raiz133);  
			stream_START.Add(s);

			DebugLocation(29, 28);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:29:29: ( NUM | HEXSUF )?
			int alt3=3;
			try { DebugEnterSubRule(3);
			try { DebugEnterDecision(3, false);
			int LA3_1 = input.LA(1);

			if ((LA3_1==NUM))
			{
				alt3 = 1;
			}
			else if ((LA3_1==HEXSUF))
			{
				alt3 = 2;
			}
			} finally { DebugExitDecision(3); }
			switch (alt3)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:29:30: NUM
				{
				DebugLocation(29, 30);
				v=(IToken)Match(input,NUM,Follow._NUM_in_raiz138);  
				stream_NUM.Add(v);


				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:29:36: HEXSUF
				{
				DebugLocation(29, 36);
				v=(IToken)Match(input,HEXSUF,Follow._HEXSUF_in_raiz142);  
				stream_HEXSUF.Add(v);


				}
				break;

			}
			} finally { DebugExitSubRule(3); }

			DebugLocation(29, 45);
			FINL8=(IToken)Match(input,FINL,Follow._FINL_in_raiz146);  
			stream_FINL.Add(FINL8);



			{
			// AST REWRITE
			// elements: et, v, s
			// token labels: s, v
			// rule labels: retval, et
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleITokenStream stream_s=new RewriteRuleITokenStream(adaptor,"token s",s);
			RewriteRuleITokenStream stream_v=new RewriteRuleITokenStream(adaptor,"token v",v);
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);
			RewriteRuleSubtreeStream stream_et=new RewriteRuleSubtreeStream(adaptor,"rule et",et!=null?et.Tree:null);

			root_0 = (object)adaptor.Nil();
			// 30:7: -> ^( DIR $et $s ( $v)? )
			{
				DebugLocation(30, 10);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:30:10: ^( DIR $et $s ( $v)? )
				{
				object root_1 = (object)adaptor.Nil();
				DebugLocation(30, 12);
				root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(DIR, "DIR"), root_1);

				DebugLocation(30, 17);
				adaptor.AddChild(root_1, stream_et.NextTree());
				DebugLocation(30, 21);
				adaptor.AddChild(root_1, stream_s.NextNode());
				DebugLocation(30, 24);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:30:24: ( $v)?
				if (stream_v.HasNext)
				{
					DebugLocation(30, 24);
					adaptor.AddChild(root_1, stream_v.NextNode());

				}
				stream_v.Reset();

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("raiz", 3);
			LeaveRule("raiz", 3);
			LeaveRule_raiz();
		}
		DebugLocation(31, 4);
		} finally { DebugExitRule(GrammarFileName, "raiz"); }
		return retval;

	}
	// $ANTLR end "raiz"

	partial void EnterRule_fin();
	partial void LeaveRule_fin();
	// $ANTLR start "fin"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:33:1: fin : e= END ent= entrada ( FINL )? -> ^( INSTR $e ( $ent)? ) ;
	[GrammarRule("fin")]
	private AstParserRuleReturnScope<object, IToken> fin()
	{
		EnterRule_fin();
		EnterRule("fin", 4);
		TraceIn("fin", 4);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken e = default(IToken);
		IToken FINL9 = default(IToken);
		AstParserRuleReturnScope<object, IToken> ent = default(AstParserRuleReturnScope<object, IToken>);

		object e_tree = default(object);
		object FINL9_tree = default(object);
		RewriteRuleITokenStream stream_FINL=new RewriteRuleITokenStream(adaptor,"token FINL");
		RewriteRuleITokenStream stream_END=new RewriteRuleITokenStream(adaptor,"token END");
		RewriteRuleSubtreeStream stream_entrada=new RewriteRuleSubtreeStream(adaptor,"rule entrada");
		try { DebugEnterRule(GrammarFileName, "fin");
		DebugLocation(33, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:35:5: (e= END ent= entrada ( FINL )? -> ^( INSTR $e ( $ent)? ) )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:35:7: e= END ent= entrada ( FINL )?
			{
			DebugLocation(35, 8);
			e=(IToken)Match(input,END,Follow._END_in_fin192);  
			stream_END.Add(e);

			DebugLocation(35, 16);
			PushFollow(Follow._entrada_in_fin196);
			ent=entrada();
			PopFollow();

			stream_entrada.Add(ent.Tree);
			DebugLocation(35, 25);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:35:25: ( FINL )?
			int alt4=2;
			try { DebugEnterSubRule(4);
			try { DebugEnterDecision(4, false);
			int LA4_1 = input.LA(1);

			if ((LA4_1==FINL))
			{
				alt4 = 1;
			}
			} finally { DebugExitDecision(4); }
			switch (alt4)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:35:26: FINL
				{
				DebugLocation(35, 26);
				FINL9=(IToken)Match(input,FINL,Follow._FINL_in_fin199);  
				stream_FINL.Add(FINL9);


				}
				break;

			}
			} finally { DebugExitSubRule(4); }



			{
			// AST REWRITE
			// elements: ent, e
			// token labels: e
			// rule labels: ent, retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleITokenStream stream_e=new RewriteRuleITokenStream(adaptor,"token e",e);
			RewriteRuleSubtreeStream stream_ent=new RewriteRuleSubtreeStream(adaptor,"rule ent",ent!=null?ent.Tree:null);
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (object)adaptor.Nil();
			// 36:7: -> ^( INSTR $e ( $ent)? )
			{
				DebugLocation(36, 10);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:36:10: ^( INSTR $e ( $ent)? )
				{
				object root_1 = (object)adaptor.Nil();
				DebugLocation(36, 12);
				root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(INSTR, "INSTR"), root_1);

				DebugLocation(36, 19);
				adaptor.AddChild(root_1, stream_e.NextNode());
				DebugLocation(36, 22);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:36:22: ( $ent)?
				if (stream_ent.HasNext)
				{
					DebugLocation(36, 22);
					adaptor.AddChild(root_1, stream_ent.NextTree());

				}
				stream_ent.Reset();

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("fin", 4);
			LeaveRule("fin", 4);
			LeaveRule_fin();
		}
		DebugLocation(37, 4);
		} finally { DebugExitRule(GrammarFileName, "fin"); }
		return retval;

	}
	// $ANTLR end "fin"

	partial void EnterRule_entrada();
	partial void LeaveRule_entrada();
	// $ANTLR start "entrada"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:39:1: entrada : ( ID )? ;
	[GrammarRule("entrada")]
	private AstParserRuleReturnScope<object, IToken> entrada()
	{
		EnterRule_entrada();
		EnterRule("entrada", 5);
		TraceIn("entrada", 5);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken ID10 = default(IToken);

		object ID10_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "entrada");
		DebugLocation(39, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:40:5: ( ( ID )? )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:40:7: ( ID )?
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(40, 7);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:40:7: ( ID )?
			int alt5=2;
			try { DebugEnterSubRule(5);
			try { DebugEnterDecision(5, false);
			int LA5_1 = input.LA(1);

			if ((LA5_1==ID))
			{
				alt5 = 1;
			}
			} finally { DebugExitDecision(5); }
			switch (alt5)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:40:7: ID
				{
				DebugLocation(40, 7);
				ID10=(IToken)Match(input,ID,Follow._ID_in_entrada237); 
				ID10_tree = (object)adaptor.Create(ID10);
				adaptor.AddChild(root_0, ID10_tree);

				}
				break;

			}
			} finally { DebugExitSubRule(5); }


			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("entrada", 5);
			LeaveRule("entrada", 5);
			LeaveRule_entrada();
		}
		DebugLocation(41, 4);
		} finally { DebugExitRule(GrammarFileName, "entrada"); }
		return retval;

	}
	// $ANTLR end "entrada"

	partial void EnterRule_proposiciones();
	partial void LeaveRule_proposiciones();
	// $ANTLR start "proposiciones"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:44:1: proposiciones : ( proposicion )+ ;
	[GrammarRule("proposiciones")]
	private AstParserRuleReturnScope<object, IToken> proposiciones()
	{
		EnterRule_proposiciones();
		EnterRule("proposiciones", 6);
		TraceIn("proposiciones", 6);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		AstParserRuleReturnScope<object, IToken> proposicion11 = default(AstParserRuleReturnScope<object, IToken>);

		try { DebugEnterRule(GrammarFileName, "proposiciones");
		DebugLocation(44, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:45:5: ( ( proposicion )+ )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:45:7: ( proposicion )+
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(45, 7);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:45:7: ( proposicion )+
			int cnt6=0;
			try { DebugEnterSubRule(6);
			while (true)
			{
				int alt6=2;
				try { DebugEnterDecision(6, false);
				int LA6_1 = input.LA(1);

				if (((LA6_1>=BASE && LA6_1<=BYTE)||LA6_1==F1CODOP||LA6_1==F2CODOP||LA6_1==F34CODOP||LA6_1==ID||LA6_1==PLUS||(LA6_1>=RESB && LA6_1<=RESW)||LA6_1==WORD))
				{
					alt6 = 1;
				}


				} finally { DebugExitDecision(6); }
				switch (alt6)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:45:8: proposicion
					{
					DebugLocation(45, 8);
					PushFollow(Follow._proposicion_in_proposiciones257);
					proposicion11=proposicion();
					PopFollow();

					adaptor.AddChild(root_0, proposicion11.Tree);

					}
					break;

				default:
					if (cnt6 >= 1)
						goto loop6;

					EarlyExitException eee6 = new EarlyExitException( 6, input );
					DebugRecognitionException(eee6);
					throw eee6;
				}
				cnt6++;
			}
			loop6:
				;

			} finally { DebugExitSubRule(6); }


			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("proposiciones", 6);
			LeaveRule("proposiciones", 6);
			LeaveRule_proposiciones();
		}
		DebugLocation(46, 4);
		} finally { DebugExitRule(GrammarFileName, "proposiciones"); }
		return retval;

	}
	// $ANTLR end "proposiciones"

	partial void EnterRule_proposicion();
	partial void LeaveRule_proposicion();
	// $ANTLR start "proposicion"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:49:1: proposicion : ( instruccion | directiva );
	[GrammarRule("proposicion")]
	private AstParserRuleReturnScope<object, IToken> proposicion()
	{
		EnterRule_proposicion();
		EnterRule("proposicion", 7);
		TraceIn("proposicion", 7);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		AstParserRuleReturnScope<object, IToken> instruccion12 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> directiva13 = default(AstParserRuleReturnScope<object, IToken>);

		try { DebugEnterRule(GrammarFileName, "proposicion");
		DebugLocation(49, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:50:5: ( instruccion | directiva )
			int alt7=2;
			try { DebugEnterDecision(7, false);
			switch (input.LA(1))
			{
			case ID:
				{
				int LA7_2 = input.LA(2);

				if ((LA7_2==F1CODOP||LA7_2==F2CODOP||LA7_2==F34CODOP||LA7_2==PLUS))
				{
					alt7 = 1;
				}
				else if (((LA7_2>=BASE && LA7_2<=BYTE)||(LA7_2>=RESB && LA7_2<=RESW)||LA7_2==WORD))
				{
					alt7 = 2;
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 7, 1, input, 2);
					DebugRecognitionException(nvae);
					throw nvae;
				}
				}
				break;
			case F1CODOP:
			case F2CODOP:
			case F34CODOP:
			case PLUS:
				{
				alt7 = 1;
				}
				break;
			case BASE:
			case BYTE:
			case RESB:
			case RESW:
			case WORD:
				{
				alt7 = 2;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 7, 0, input, 1);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(7); }
			switch (alt7)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:50:7: instruccion
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(50, 7);
				PushFollow(Follow._instruccion_in_proposicion277);
				instruccion12=instruccion();
				PopFollow();

				adaptor.AddChild(root_0, instruccion12.Tree);

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:51:7: directiva
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(51, 7);
				PushFollow(Follow._directiva_in_proposicion285);
				directiva13=directiva();
				PopFollow();

				adaptor.AddChild(root_0, directiva13.Tree);

				}
				break;

			}
			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("proposicion", 7);
			LeaveRule("proposicion", 7);
			LeaveRule_proposicion();
		}
		DebugLocation(52, 4);
		} finally { DebugExitRule(GrammarFileName, "proposicion"); }
		return retval;

	}
	// $ANTLR end "proposicion"

	partial void EnterRule_instruccion();
	partial void LeaveRule_instruccion();
	// $ANTLR start "instruccion"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:55:1: instruccion : ( etiqueta )? opinstruccion FINL -> ^( INSTR ( etiqueta )? opinstruccion ) ;
	[GrammarRule("instruccion")]
	private AstParserRuleReturnScope<object, IToken> instruccion()
	{
		EnterRule_instruccion();
		EnterRule("instruccion", 8);
		TraceIn("instruccion", 8);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken FINL16 = default(IToken);
		AstParserRuleReturnScope<object, IToken> etiqueta14 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> opinstruccion15 = default(AstParserRuleReturnScope<object, IToken>);

		object FINL16_tree = default(object);
		RewriteRuleITokenStream stream_FINL=new RewriteRuleITokenStream(adaptor,"token FINL");
		RewriteRuleSubtreeStream stream_etiqueta=new RewriteRuleSubtreeStream(adaptor,"rule etiqueta");
		RewriteRuleSubtreeStream stream_opinstruccion=new RewriteRuleSubtreeStream(adaptor,"rule opinstruccion");
		try { DebugEnterRule(GrammarFileName, "instruccion");
		DebugLocation(55, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:56:5: ( ( etiqueta )? opinstruccion FINL -> ^( INSTR ( etiqueta )? opinstruccion ) )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:56:7: ( etiqueta )? opinstruccion FINL
			{
			DebugLocation(56, 7);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:56:7: ( etiqueta )?
			int alt8=2;
			try { DebugEnterSubRule(8);
			try { DebugEnterDecision(8, false);
			int LA8_1 = input.LA(1);

			if ((LA8_1==ID))
			{
				alt8 = 1;
			}
			} finally { DebugExitDecision(8); }
			switch (alt8)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:56:7: etiqueta
				{
				DebugLocation(56, 7);
				PushFollow(Follow._etiqueta_in_instruccion303);
				etiqueta14=etiqueta();
				PopFollow();

				stream_etiqueta.Add(etiqueta14.Tree);

				}
				break;

			}
			} finally { DebugExitSubRule(8); }

			DebugLocation(56, 17);
			PushFollow(Follow._opinstruccion_in_instruccion306);
			opinstruccion15=opinstruccion();
			PopFollow();

			stream_opinstruccion.Add(opinstruccion15.Tree);
			DebugLocation(56, 31);
			FINL16=(IToken)Match(input,FINL,Follow._FINL_in_instruccion308);  
			stream_FINL.Add(FINL16);



			{
			// AST REWRITE
			// elements: etiqueta, opinstruccion
			// token labels: 
			// rule labels: retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (object)adaptor.Nil();
			// 57:7: -> ^( INSTR ( etiqueta )? opinstruccion )
			{
				DebugLocation(57, 10);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:57:10: ^( INSTR ( etiqueta )? opinstruccion )
				{
				object root_1 = (object)adaptor.Nil();
				DebugLocation(57, 12);
				root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(INSTR, "INSTR"), root_1);

				DebugLocation(57, 18);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:57:18: ( etiqueta )?
				if (stream_etiqueta.HasNext)
				{
					DebugLocation(57, 19);
					adaptor.AddChild(root_1, stream_etiqueta.NextTree());

				}
				stream_etiqueta.Reset();
				DebugLocation(57, 30);
				adaptor.AddChild(root_1, stream_opinstruccion.NextTree());

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("instruccion", 8);
			LeaveRule("instruccion", 8);
			LeaveRule_instruccion();
		}
		DebugLocation(58, 4);
		} finally { DebugExitRule(GrammarFileName, "instruccion"); }
		return retval;

	}
	// $ANTLR end "instruccion"

	partial void EnterRule_directiva();
	partial void LeaveRule_directiva();
	// $ANTLR start "directiva"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:61:1: directiva : ( etiqueta )? tipodirectiva ( opdirectiva )? FINL -> ^( DIR ( etiqueta )? tipodirectiva ( opdirectiva )? ) ;
	[GrammarRule("directiva")]
	private AstParserRuleReturnScope<object, IToken> directiva()
	{
		EnterRule_directiva();
		EnterRule("directiva", 9);
		TraceIn("directiva", 9);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken FINL20 = default(IToken);
		AstParserRuleReturnScope<object, IToken> etiqueta17 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> tipodirectiva18 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> opdirectiva19 = default(AstParserRuleReturnScope<object, IToken>);

		object FINL20_tree = default(object);
		RewriteRuleITokenStream stream_FINL=new RewriteRuleITokenStream(adaptor,"token FINL");
		RewriteRuleSubtreeStream stream_etiqueta=new RewriteRuleSubtreeStream(adaptor,"rule etiqueta");
		RewriteRuleSubtreeStream stream_opdirectiva=new RewriteRuleSubtreeStream(adaptor,"rule opdirectiva");
		RewriteRuleSubtreeStream stream_tipodirectiva=new RewriteRuleSubtreeStream(adaptor,"rule tipodirectiva");
		try { DebugEnterRule(GrammarFileName, "directiva");
		DebugLocation(61, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:62:5: ( ( etiqueta )? tipodirectiva ( opdirectiva )? FINL -> ^( DIR ( etiqueta )? tipodirectiva ( opdirectiva )? ) )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:62:7: ( etiqueta )? tipodirectiva ( opdirectiva )? FINL
			{
			DebugLocation(62, 7);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:62:7: ( etiqueta )?
			int alt9=2;
			try { DebugEnterSubRule(9);
			try { DebugEnterDecision(9, false);
			int LA9_1 = input.LA(1);

			if ((LA9_1==ID))
			{
				alt9 = 1;
			}
			} finally { DebugExitDecision(9); }
			switch (alt9)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:62:7: etiqueta
				{
				DebugLocation(62, 7);
				PushFollow(Follow._etiqueta_in_directiva345);
				etiqueta17=etiqueta();
				PopFollow();

				stream_etiqueta.Add(etiqueta17.Tree);

				}
				break;

			}
			} finally { DebugExitSubRule(9); }

			DebugLocation(62, 17);
			PushFollow(Follow._tipodirectiva_in_directiva348);
			tipodirectiva18=tipodirectiva();
			PopFollow();

			stream_tipodirectiva.Add(tipodirectiva18.Tree);
			DebugLocation(62, 31);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:62:31: ( opdirectiva )?
			int alt10=2;
			try { DebugEnterSubRule(10);
			try { DebugEnterDecision(10, false);
			int LA10_1 = input.LA(1);

			if (((LA10_1>=CHCONST && LA10_1<=CONSTHEX)||(LA10_1>=HEXCONST && LA10_1<=ID)||LA10_1==NUM))
			{
				alt10 = 1;
			}
			} finally { DebugExitDecision(10); }
			switch (alt10)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:62:32: opdirectiva
				{
				DebugLocation(62, 32);
				PushFollow(Follow._opdirectiva_in_directiva351);
				opdirectiva19=opdirectiva();
				PopFollow();

				stream_opdirectiva.Add(opdirectiva19.Tree);

				}
				break;

			}
			} finally { DebugExitSubRule(10); }

			DebugLocation(62, 46);
			FINL20=(IToken)Match(input,FINL,Follow._FINL_in_directiva355);  
			stream_FINL.Add(FINL20);



			{
			// AST REWRITE
			// elements: etiqueta, tipodirectiva, opdirectiva
			// token labels: 
			// rule labels: retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (object)adaptor.Nil();
			// 63:7: -> ^( DIR ( etiqueta )? tipodirectiva ( opdirectiva )? )
			{
				DebugLocation(63, 10);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:63:10: ^( DIR ( etiqueta )? tipodirectiva ( opdirectiva )? )
				{
				object root_1 = (object)adaptor.Nil();
				DebugLocation(63, 12);
				root_1 = (object)adaptor.BecomeRoot((object)adaptor.Create(DIR, "DIR"), root_1);

				DebugLocation(63, 16);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:63:16: ( etiqueta )?
				if (stream_etiqueta.HasNext)
				{
					DebugLocation(63, 17);
					adaptor.AddChild(root_1, stream_etiqueta.NextTree());

				}
				stream_etiqueta.Reset();
				DebugLocation(63, 28);
				adaptor.AddChild(root_1, stream_tipodirectiva.NextTree());
				DebugLocation(63, 42);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:63:42: ( opdirectiva )?
				if (stream_opdirectiva.HasNext)
				{
					DebugLocation(63, 43);
					adaptor.AddChild(root_1, stream_opdirectiva.NextTree());

				}
				stream_opdirectiva.Reset();

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("directiva", 9);
			LeaveRule("directiva", 9);
			LeaveRule_directiva();
		}
		DebugLocation(64, 4);
		} finally { DebugExitRule(GrammarFileName, "directiva"); }
		return retval;

	}
	// $ANTLR end "directiva"

	partial void EnterRule_tipodirectiva();
	partial void LeaveRule_tipodirectiva();
	// $ANTLR start "tipodirectiva"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:67:1: tipodirectiva : ( BYTE | WORD | RESB | RESW | BASE );
	[GrammarRule("tipodirectiva")]
	private AstParserRuleReturnScope<object, IToken> tipodirectiva()
	{
		EnterRule_tipodirectiva();
		EnterRule("tipodirectiva", 10);
		TraceIn("tipodirectiva", 10);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken set21 = default(IToken);

		object set21_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "tipodirectiva");
		DebugLocation(67, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:68:5: ( BYTE | WORD | RESB | RESW | BASE )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(68, 5);

			set21=(IToken)input.LT(1);
			if ((input.LA(1)>=BASE && input.LA(1)<=BYTE)||(input.LA(1)>=RESB && input.LA(1)<=RESW)||input.LA(1)==WORD)
			{
				input.Consume();
				adaptor.AddChild(root_0, (object)adaptor.Create(set21));
				state.errorRecovery=false;
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				throw mse;
			}


			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("tipodirectiva", 10);
			LeaveRule("tipodirectiva", 10);
			LeaveRule_tipodirectiva();
		}
		DebugLocation(73, 4);
		} finally { DebugExitRule(GrammarFileName, "tipodirectiva"); }
		return retval;

	}
	// $ANTLR end "tipodirectiva"

	partial void EnterRule_etiqueta();
	partial void LeaveRule_etiqueta();
	// $ANTLR start "etiqueta"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:76:1: etiqueta : ID ;
	[GrammarRule("etiqueta")]
	private AstParserRuleReturnScope<object, IToken> etiqueta()
	{
		EnterRule_etiqueta();
		EnterRule("etiqueta", 11);
		TraceIn("etiqueta", 11);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken ID22 = default(IToken);

		object ID22_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "etiqueta");
		DebugLocation(76, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:77:5: ( ID )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:77:7: ID
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(77, 7);
			ID22=(IToken)Match(input,ID,Follow._ID_in_etiqueta447); 
			ID22_tree = (object)adaptor.Create(ID22);
			adaptor.AddChild(root_0, ID22_tree);

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("etiqueta", 11);
			LeaveRule("etiqueta", 11);
			LeaveRule_etiqueta();
		}
		DebugLocation(78, 4);
		} finally { DebugExitRule(GrammarFileName, "etiqueta"); }
		return retval;

	}
	// $ANTLR end "etiqueta"

	partial void EnterRule_opinstruccion();
	partial void LeaveRule_opinstruccion();
	// $ANTLR start "opinstruccion"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:81:1: opinstruccion : formato ;
	[GrammarRule("opinstruccion")]
	private AstParserRuleReturnScope<object, IToken> opinstruccion()
	{
		EnterRule_opinstruccion();
		EnterRule("opinstruccion", 12);
		TraceIn("opinstruccion", 12);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		AstParserRuleReturnScope<object, IToken> formato23 = default(AstParserRuleReturnScope<object, IToken>);

		try { DebugEnterRule(GrammarFileName, "opinstruccion");
		DebugLocation(81, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:82:5: ( formato )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:82:7: formato
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(82, 7);
			PushFollow(Follow._formato_in_opinstruccion465);
			formato23=formato();
			PopFollow();

			adaptor.AddChild(root_0, formato23.Tree);

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("opinstruccion", 12);
			LeaveRule("opinstruccion", 12);
			LeaveRule_opinstruccion();
		}
		DebugLocation(83, 4);
		} finally { DebugExitRule(GrammarFileName, "opinstruccion"); }
		return retval;

	}
	// $ANTLR end "opinstruccion"

	partial void EnterRule_formato();
	partial void LeaveRule_formato();
	// $ANTLR start "formato"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:86:1: formato : ( f1 | f2 | f3 | f4 | indexado );
	[GrammarRule("formato")]
	private AstParserRuleReturnScope<object, IToken> formato()
	{
		EnterRule_formato();
		EnterRule("formato", 13);
		TraceIn("formato", 13);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		AstParserRuleReturnScope<object, IToken> f124 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> f225 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> f326 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> f427 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> indexado28 = default(AstParserRuleReturnScope<object, IToken>);

		try { DebugEnterRule(GrammarFileName, "formato");
		DebugLocation(86, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:87:5: ( f1 | f2 | f3 | f4 | indexado )
			int alt11=5;
			try { DebugEnterDecision(11, false);
			switch (input.LA(1))
			{
			case F1CODOP:
				{
				alt11 = 1;
				}
				break;
			case F2CODOP:
				{
				alt11 = 2;
				}
				break;
			case F34CODOP:
				{
				int LA11_2 = input.LA(2);

				if ((LA11_2==AT||LA11_2==FINL||LA11_2==ID||(LA11_2>=NUM && LA11_2<=NUMERAL)||LA11_2==33))
				{
					alt11 = 3;
				}
				else if ((LA11_2==INDICE))
				{
					alt11 = 5;
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 11, 3, input, 2);
					DebugRecognitionException(nvae);
					throw nvae;
				}
				}
				break;
			case PLUS:
				{
				alt11 = 4;
				}
				break;
			default:
				{
					NoViableAltException nvae = new NoViableAltException("", 11, 0, input, 1);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}

			} finally { DebugExitDecision(11); }
			switch (alt11)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:87:7: f1
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(87, 7);
				PushFollow(Follow._f1_in_formato483);
				f124=f1();
				PopFollow();

				adaptor.AddChild(root_0, f124.Tree);

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:88:7: f2
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(88, 7);
				PushFollow(Follow._f2_in_formato491);
				f225=f2();
				PopFollow();

				adaptor.AddChild(root_0, f225.Tree);

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:89:7: f3
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(89, 7);
				PushFollow(Follow._f3_in_formato499);
				f326=f3();
				PopFollow();

				adaptor.AddChild(root_0, f326.Tree);

				}
				break;
			case 4:
				DebugEnterAlt(4);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:90:7: f4
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(90, 7);
				PushFollow(Follow._f4_in_formato507);
				f427=f4();
				PopFollow();

				adaptor.AddChild(root_0, f427.Tree);

				}
				break;
			case 5:
				DebugEnterAlt(5);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:91:7: indexado
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(91, 7);
				PushFollow(Follow._indexado_in_formato515);
				indexado28=indexado();
				PopFollow();

				adaptor.AddChild(root_0, indexado28.Tree);

				}
				break;

			}
			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("formato", 13);
			LeaveRule("formato", 13);
			LeaveRule_formato();
		}
		DebugLocation(92, 4);
		} finally { DebugExitRule(GrammarFileName, "formato"); }
		return retval;

	}
	// $ANTLR end "formato"

	partial void EnterRule_f1();
	partial void LeaveRule_f1();
	// $ANTLR start "f1"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:95:1: f1 : F1CODOP ;
	[GrammarRule("f1")]
	private AstParserRuleReturnScope<object, IToken> f1()
	{
		EnterRule_f1();
		EnterRule("f1", 14);
		TraceIn("f1", 14);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken F1CODOP29 = default(IToken);

		object F1CODOP29_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "f1");
		DebugLocation(95, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:96:5: ( F1CODOP )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:96:7: F1CODOP
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(96, 7);
			F1CODOP29=(IToken)Match(input,F1CODOP,Follow._F1CODOP_in_f1533); 
			F1CODOP29_tree = (object)adaptor.Create(F1CODOP29);
			adaptor.AddChild(root_0, F1CODOP29_tree);

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("f1", 14);
			LeaveRule("f1", 14);
			LeaveRule_f1();
		}
		DebugLocation(97, 4);
		} finally { DebugExitRule(GrammarFileName, "f1"); }
		return retval;

	}
	// $ANTLR end "f1"

	partial void EnterRule_f2();
	partial void LeaveRule_f2();
	// $ANTLR start "f2"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:100:1: f2 : ( F2CODOP REG | F2CODOP REG ',' REG | F2CODOP REG ',' NUM );
	[GrammarRule("f2")]
	private AstParserRuleReturnScope<object, IToken> f2()
	{
		EnterRule_f2();
		EnterRule("f2", 15);
		TraceIn("f2", 15);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken F2CODOP30 = default(IToken);
		IToken REG31 = default(IToken);
		IToken F2CODOP32 = default(IToken);
		IToken REG33 = default(IToken);
		IToken char_literal34 = default(IToken);
		IToken REG35 = default(IToken);
		IToken F2CODOP36 = default(IToken);
		IToken REG37 = default(IToken);
		IToken char_literal38 = default(IToken);
		IToken NUM39 = default(IToken);

		object F2CODOP30_tree = default(object);
		object REG31_tree = default(object);
		object F2CODOP32_tree = default(object);
		object REG33_tree = default(object);
		object char_literal34_tree = default(object);
		object REG35_tree = default(object);
		object F2CODOP36_tree = default(object);
		object REG37_tree = default(object);
		object char_literal38_tree = default(object);
		object NUM39_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "f2");
		DebugLocation(100, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:101:5: ( F2CODOP REG | F2CODOP REG ',' REG | F2CODOP REG ',' NUM )
			int alt12=3;
			try { DebugEnterDecision(12, false);
			int LA12_1 = input.LA(1);

			if ((LA12_1==F2CODOP))
			{
				int LA12_2 = input.LA(2);

				if ((LA12_2==REG))
				{
					int LA12_3 = input.LA(3);

					if ((LA12_3==33))
					{
						int LA12_4 = input.LA(4);

						if ((LA12_4==REG))
						{
							alt12 = 2;
						}
						else if ((LA12_4==NUM))
						{
							alt12 = 3;
						}
						else
						{
							NoViableAltException nvae = new NoViableAltException("", 12, 3, input, 4);
							DebugRecognitionException(nvae);
							throw nvae;
						}
					}
					else if ((LA12_3==FINL))
					{
						alt12 = 1;
					}
					else
					{
						NoViableAltException nvae = new NoViableAltException("", 12, 2, input, 3);
						DebugRecognitionException(nvae);
						throw nvae;
					}
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 12, 1, input, 2);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 12, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(12); }
			switch (alt12)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:101:7: F2CODOP REG
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(101, 7);
				F2CODOP30=(IToken)Match(input,F2CODOP,Follow._F2CODOP_in_f2551); 
				F2CODOP30_tree = (object)adaptor.Create(F2CODOP30);
				adaptor.AddChild(root_0, F2CODOP30_tree);
				DebugLocation(101, 15);
				REG31=(IToken)Match(input,REG,Follow._REG_in_f2553); 
				REG31_tree = (object)adaptor.Create(REG31);
				adaptor.AddChild(root_0, REG31_tree);

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:102:7: F2CODOP REG ',' REG
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(102, 7);
				F2CODOP32=(IToken)Match(input,F2CODOP,Follow._F2CODOP_in_f2561); 
				F2CODOP32_tree = (object)adaptor.Create(F2CODOP32);
				adaptor.AddChild(root_0, F2CODOP32_tree);
				DebugLocation(102, 15);
				REG33=(IToken)Match(input,REG,Follow._REG_in_f2563); 
				REG33_tree = (object)adaptor.Create(REG33);
				adaptor.AddChild(root_0, REG33_tree);
				DebugLocation(102, 19);
				char_literal34=(IToken)Match(input,33,Follow._33_in_f2565); 
				char_literal34_tree = (object)adaptor.Create(char_literal34);
				adaptor.AddChild(root_0, char_literal34_tree);
				DebugLocation(102, 23);
				REG35=(IToken)Match(input,REG,Follow._REG_in_f2567); 
				REG35_tree = (object)adaptor.Create(REG35);
				adaptor.AddChild(root_0, REG35_tree);

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:103:7: F2CODOP REG ',' NUM
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(103, 7);
				F2CODOP36=(IToken)Match(input,F2CODOP,Follow._F2CODOP_in_f2575); 
				F2CODOP36_tree = (object)adaptor.Create(F2CODOP36);
				adaptor.AddChild(root_0, F2CODOP36_tree);
				DebugLocation(103, 15);
				REG37=(IToken)Match(input,REG,Follow._REG_in_f2577); 
				REG37_tree = (object)adaptor.Create(REG37);
				adaptor.AddChild(root_0, REG37_tree);
				DebugLocation(103, 19);
				char_literal38=(IToken)Match(input,33,Follow._33_in_f2579); 
				char_literal38_tree = (object)adaptor.Create(char_literal38);
				adaptor.AddChild(root_0, char_literal38_tree);
				DebugLocation(103, 23);
				NUM39=(IToken)Match(input,NUM,Follow._NUM_in_f2581); 
				NUM39_tree = (object)adaptor.Create(NUM39);
				adaptor.AddChild(root_0, NUM39_tree);

				}
				break;

			}
			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("f2", 15);
			LeaveRule("f2", 15);
			LeaveRule_f2();
		}
		DebugLocation(104, 4);
		} finally { DebugExitRule(GrammarFileName, "f2"); }
		return retval;

	}
	// $ANTLR end "f2"

	partial void EnterRule_f3();
	partial void LeaveRule_f3();
	// $ANTLR start "f3"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:107:1: f3 : ( simple3 | indirecto3 | inmediato3 );
	[GrammarRule("f3")]
	private AstParserRuleReturnScope<object, IToken> f3()
	{
		EnterRule_f3();
		EnterRule("f3", 16);
		TraceIn("f3", 16);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		AstParserRuleReturnScope<object, IToken> simple340 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> indirecto341 = default(AstParserRuleReturnScope<object, IToken>);
		AstParserRuleReturnScope<object, IToken> inmediato342 = default(AstParserRuleReturnScope<object, IToken>);

		try { DebugEnterRule(GrammarFileName, "f3");
		DebugLocation(107, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:108:5: ( simple3 | indirecto3 | inmediato3 )
			int alt13=3;
			try { DebugEnterDecision(13, false);
			int LA13_1 = input.LA(1);

			if ((LA13_1==F34CODOP))
			{
				switch (input.LA(2))
				{
				case AT:
					{
					alt13 = 2;
					}
					break;
				case NUMERAL:
					{
					alt13 = 3;
					}
					break;
				case FINL:
				case ID:
				case NUM:
				case 33:
					{
					alt13 = 1;
					}
					break;
				default:
					{
						NoViableAltException nvae = new NoViableAltException("", 13, 1, input, 2);
						DebugRecognitionException(nvae);
						throw nvae;
					}
				}

			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 13, 0, input, 1);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(13); }
			switch (alt13)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:108:7: simple3
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(108, 7);
				PushFollow(Follow._simple3_in_f3599);
				simple340=simple3();
				PopFollow();

				adaptor.AddChild(root_0, simple340.Tree);

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:109:7: indirecto3
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(109, 7);
				PushFollow(Follow._indirecto3_in_f3607);
				indirecto341=indirecto3();
				PopFollow();

				adaptor.AddChild(root_0, indirecto341.Tree);

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:110:7: inmediato3
				{
				root_0 = (object)adaptor.Nil();

				DebugLocation(110, 7);
				PushFollow(Follow._inmediato3_in_f3615);
				inmediato342=inmediato3();
				PopFollow();

				adaptor.AddChild(root_0, inmediato342.Tree);

				}
				break;

			}
			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("f3", 16);
			LeaveRule("f3", 16);
			LeaveRule_f3();
		}
		DebugLocation(111, 4);
		} finally { DebugExitRule(GrammarFileName, "f3"); }
		return retval;

	}
	// $ANTLR end "f3"

	partial void EnterRule_f4();
	partial void LeaveRule_f4();
	// $ANTLR start "f4"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:114:1: f4 : PLUS f3 ;
	[GrammarRule("f4")]
	private AstParserRuleReturnScope<object, IToken> f4()
	{
		EnterRule_f4();
		EnterRule("f4", 17);
		TraceIn("f4", 17);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken PLUS43 = default(IToken);
		AstParserRuleReturnScope<object, IToken> f344 = default(AstParserRuleReturnScope<object, IToken>);

		object PLUS43_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "f4");
		DebugLocation(114, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:115:5: ( PLUS f3 )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:115:7: PLUS f3
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(115, 7);
			PLUS43=(IToken)Match(input,PLUS,Follow._PLUS_in_f4633); 
			PLUS43_tree = (object)adaptor.Create(PLUS43);
			adaptor.AddChild(root_0, PLUS43_tree);
			DebugLocation(115, 12);
			PushFollow(Follow._f3_in_f4635);
			f344=f3();
			PopFollow();

			adaptor.AddChild(root_0, f344.Tree);

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("f4", 17);
			LeaveRule("f4", 17);
			LeaveRule_f4();
		}
		DebugLocation(116, 4);
		} finally { DebugExitRule(GrammarFileName, "f4"); }
		return retval;

	}
	// $ANTLR end "f4"

	partial void EnterRule_indexado();
	partial void LeaveRule_indexado();
	// $ANTLR start "indexado"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:119:1: indexado : F34CODOP INDICE ;
	[GrammarRule("indexado")]
	private AstParserRuleReturnScope<object, IToken> indexado()
	{
		EnterRule_indexado();
		EnterRule("indexado", 18);
		TraceIn("indexado", 18);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken F34CODOP45 = default(IToken);
		IToken INDICE46 = default(IToken);

		object F34CODOP45_tree = default(object);
		object INDICE46_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "indexado");
		DebugLocation(119, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:120:5: ( F34CODOP INDICE )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:120:7: F34CODOP INDICE
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(120, 7);
			F34CODOP45=(IToken)Match(input,F34CODOP,Follow._F34CODOP_in_indexado653); 
			F34CODOP45_tree = (object)adaptor.Create(F34CODOP45);
			adaptor.AddChild(root_0, F34CODOP45_tree);
			DebugLocation(120, 16);
			INDICE46=(IToken)Match(input,INDICE,Follow._INDICE_in_indexado655); 
			INDICE46_tree = (object)adaptor.Create(INDICE46);
			adaptor.AddChild(root_0, INDICE46_tree);

			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("indexado", 18);
			LeaveRule("indexado", 18);
			LeaveRule_indexado();
		}
		DebugLocation(121, 4);
		} finally { DebugExitRule(GrammarFileName, "indexado"); }
		return retval;

	}
	// $ANTLR end "indexado"

	partial void EnterRule_simple3();
	partial void LeaveRule_simple3();
	// $ANTLR start "simple3"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:124:1: simple3 : F34CODOP ( ID | NUM )? ( ',' REG )? ;
	[GrammarRule("simple3")]
	private AstParserRuleReturnScope<object, IToken> simple3()
	{
		EnterRule_simple3();
		EnterRule("simple3", 19);
		TraceIn("simple3", 19);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken F34CODOP47 = default(IToken);
		IToken set48 = default(IToken);
		IToken char_literal49 = default(IToken);
		IToken REG50 = default(IToken);

		object F34CODOP47_tree = default(object);
		object set48_tree = default(object);
		object char_literal49_tree = default(object);
		object REG50_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "simple3");
		DebugLocation(124, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:125:5: ( F34CODOP ( ID | NUM )? ( ',' REG )? )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:125:7: F34CODOP ( ID | NUM )? ( ',' REG )?
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(125, 7);
			F34CODOP47=(IToken)Match(input,F34CODOP,Follow._F34CODOP_in_simple3673); 
			F34CODOP47_tree = (object)adaptor.Create(F34CODOP47);
			adaptor.AddChild(root_0, F34CODOP47_tree);
			DebugLocation(125, 16);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:125:16: ( ID | NUM )?
			int alt14=2;
			try { DebugEnterSubRule(14);
			try { DebugEnterDecision(14, false);
			int LA14_1 = input.LA(1);

			if ((LA14_1==ID||LA14_1==NUM))
			{
				alt14 = 1;
			}
			} finally { DebugExitDecision(14); }
			switch (alt14)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:
				{
				DebugLocation(125, 16);

				set48=(IToken)input.LT(1);
				if (input.LA(1)==ID||input.LA(1)==NUM)
				{
					input.Consume();
					adaptor.AddChild(root_0, (object)adaptor.Create(set48));
					state.errorRecovery=false;
				}
				else
				{
					MismatchedSetException mse = new MismatchedSetException(null,input);
					DebugRecognitionException(mse);
					throw mse;
				}


				}
				break;

			}
			} finally { DebugExitSubRule(14); }

			DebugLocation(125, 28);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:125:28: ( ',' REG )?
			int alt15=2;
			try { DebugEnterSubRule(15);
			try { DebugEnterDecision(15, false);
			int LA15_1 = input.LA(1);

			if ((LA15_1==33))
			{
				alt15 = 1;
			}
			} finally { DebugExitDecision(15); }
			switch (alt15)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:125:29: ',' REG
				{
				DebugLocation(125, 29);
				char_literal49=(IToken)Match(input,33,Follow._33_in_simple3685); 
				char_literal49_tree = (object)adaptor.Create(char_literal49);
				adaptor.AddChild(root_0, char_literal49_tree);
				DebugLocation(125, 33);
				REG50=(IToken)Match(input,REG,Follow._REG_in_simple3687); 
				REG50_tree = (object)adaptor.Create(REG50);
				adaptor.AddChild(root_0, REG50_tree);

				}
				break;

			}
			} finally { DebugExitSubRule(15); }


			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("simple3", 19);
			LeaveRule("simple3", 19);
			LeaveRule_simple3();
		}
		DebugLocation(126, 4);
		} finally { DebugExitRule(GrammarFileName, "simple3"); }
		return retval;

	}
	// $ANTLR end "simple3"

	partial void EnterRule_indirecto3();
	partial void LeaveRule_indirecto3();
	// $ANTLR start "indirecto3"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:129:1: indirecto3 : F34CODOP AT ( NUM | ID ) ;
	[GrammarRule("indirecto3")]
	private AstParserRuleReturnScope<object, IToken> indirecto3()
	{
		EnterRule_indirecto3();
		EnterRule("indirecto3", 20);
		TraceIn("indirecto3", 20);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken F34CODOP51 = default(IToken);
		IToken AT52 = default(IToken);
		IToken set53 = default(IToken);

		object F34CODOP51_tree = default(object);
		object AT52_tree = default(object);
		object set53_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "indirecto3");
		DebugLocation(129, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:130:5: ( F34CODOP AT ( NUM | ID ) )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:130:7: F34CODOP AT ( NUM | ID )
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(130, 7);
			F34CODOP51=(IToken)Match(input,F34CODOP,Follow._F34CODOP_in_indirecto3708); 
			F34CODOP51_tree = (object)adaptor.Create(F34CODOP51);
			adaptor.AddChild(root_0, F34CODOP51_tree);
			DebugLocation(130, 16);
			AT52=(IToken)Match(input,AT,Follow._AT_in_indirecto3710); 
			AT52_tree = (object)adaptor.Create(AT52);
			adaptor.AddChild(root_0, AT52_tree);
			DebugLocation(130, 19);

			set53=(IToken)input.LT(1);
			if (input.LA(1)==ID||input.LA(1)==NUM)
			{
				input.Consume();
				adaptor.AddChild(root_0, (object)adaptor.Create(set53));
				state.errorRecovery=false;
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				throw mse;
			}


			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("indirecto3", 20);
			LeaveRule("indirecto3", 20);
			LeaveRule_indirecto3();
		}
		DebugLocation(131, 4);
		} finally { DebugExitRule(GrammarFileName, "indirecto3"); }
		return retval;

	}
	// $ANTLR end "indirecto3"

	partial void EnterRule_inmediato3();
	partial void LeaveRule_inmediato3();
	// $ANTLR start "inmediato3"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:134:1: inmediato3 : F34CODOP NUMERAL ( NUM | ID ) ;
	[GrammarRule("inmediato3")]
	private AstParserRuleReturnScope<object, IToken> inmediato3()
	{
		EnterRule_inmediato3();
		EnterRule("inmediato3", 21);
		TraceIn("inmediato3", 21);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken F34CODOP54 = default(IToken);
		IToken NUMERAL55 = default(IToken);
		IToken set56 = default(IToken);

		object F34CODOP54_tree = default(object);
		object NUMERAL55_tree = default(object);
		object set56_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "inmediato3");
		DebugLocation(134, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:135:5: ( F34CODOP NUMERAL ( NUM | ID ) )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:135:7: F34CODOP NUMERAL ( NUM | ID )
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(135, 7);
			F34CODOP54=(IToken)Match(input,F34CODOP,Follow._F34CODOP_in_inmediato3734); 
			F34CODOP54_tree = (object)adaptor.Create(F34CODOP54);
			adaptor.AddChild(root_0, F34CODOP54_tree);
			DebugLocation(135, 16);
			NUMERAL55=(IToken)Match(input,NUMERAL,Follow._NUMERAL_in_inmediato3736); 
			NUMERAL55_tree = (object)adaptor.Create(NUMERAL55);
			adaptor.AddChild(root_0, NUMERAL55_tree);
			DebugLocation(135, 24);

			set56=(IToken)input.LT(1);
			if (input.LA(1)==ID||input.LA(1)==NUM)
			{
				input.Consume();
				adaptor.AddChild(root_0, (object)adaptor.Create(set56));
				state.errorRecovery=false;
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				throw mse;
			}


			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("inmediato3", 21);
			LeaveRule("inmediato3", 21);
			LeaveRule_inmediato3();
		}
		DebugLocation(136, 4);
		} finally { DebugExitRule(GrammarFileName, "inmediato3"); }
		return retval;

	}
	// $ANTLR end "inmediato3"

	partial void EnterRule_opdirectiva();
	partial void LeaveRule_opdirectiva();
	// $ANTLR start "opdirectiva"
	// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:139:1: opdirectiva : ( NUM | CONSTHEX | CONSTCAD | HEXSUF | ID | CHCONST | HEXCONST );
	[GrammarRule("opdirectiva")]
	private AstParserRuleReturnScope<object, IToken> opdirectiva()
	{
		EnterRule_opdirectiva();
		EnterRule("opdirectiva", 22);
		TraceIn("opdirectiva", 22);
		AstParserRuleReturnScope<object, IToken> retval = new AstParserRuleReturnScope<object, IToken>();
		retval.Start = (IToken)input.LT(1);

		object root_0 = default(object);

		IToken set57 = default(IToken);

		object set57_tree = default(object);
		try { DebugEnterRule(GrammarFileName, "opdirectiva");
		DebugLocation(139, 4);
		try
		{
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:140:5: ( NUM | CONSTHEX | CONSTCAD | HEXSUF | ID | CHCONST | HEXCONST )
			DebugEnterAlt(1);
			// C:\\dev\\SW\\Practica 01 Calculadora\\Gram_SICXE.g:
			{
			root_0 = (object)adaptor.Nil();

			DebugLocation(140, 5);

			set57=(IToken)input.LT(1);
			if ((input.LA(1)>=CHCONST && input.LA(1)<=CONSTHEX)||(input.LA(1)>=HEXCONST && input.LA(1)<=ID)||input.LA(1)==NUM)
			{
				input.Consume();
				adaptor.AddChild(root_0, (object)adaptor.Create(set57));
				state.errorRecovery=false;
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				throw mse;
			}


			}

			retval.Stop = (IToken)input.LT(-1);

			retval.Tree = (object)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
			retval.Tree = (object)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("opdirectiva", 22);
			LeaveRule("opdirectiva", 22);
			LeaveRule_opdirectiva();
		}
		DebugLocation(147, 4);
		} finally { DebugExitRule(GrammarFileName, "opdirectiva"); }
		return retval;

	}
	// $ANTLR end "opdirectiva"
	#endregion Rules


	#region Follow sets
	private static class Follow
	{
		public static readonly BitSet _inicio_in_programa73 = new BitSet(new ulong[]{0xB4215060UL});
		public static readonly BitSet _proposiciones_in_programa75 = new BitSet(new ulong[]{0x800UL});
		public static readonly BitSet _fin_in_programa77 = new BitSet(new ulong[]{0x40000UL});
		public static readonly BitSet _FINL_in_programa80 = new BitSet(new ulong[]{0x0UL});
		public static readonly BitSet _EOF_in_programa84 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _raiz_in_inicio102 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _proposicion_in_inicio110 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _etiqueta_in_raiz129 = new BitSet(new ulong[]{0x40000000UL});
		public static readonly BitSet _START_in_raiz133 = new BitSet(new ulong[]{0x1140000UL});
		public static readonly BitSet _NUM_in_raiz138 = new BitSet(new ulong[]{0x40000UL});
		public static readonly BitSet _HEXSUF_in_raiz142 = new BitSet(new ulong[]{0x40000UL});
		public static readonly BitSet _FINL_in_raiz146 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _END_in_fin192 = new BitSet(new ulong[]{0x240000UL});
		public static readonly BitSet _entrada_in_fin196 = new BitSet(new ulong[]{0x40002UL});
		public static readonly BitSet _FINL_in_fin199 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _ID_in_entrada237 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _proposicion_in_proposiciones257 = new BitSet(new ulong[]{0xB4215062UL});
		public static readonly BitSet _instruccion_in_proposicion277 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _directiva_in_proposicion285 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _etiqueta_in_instruccion303 = new BitSet(new ulong[]{0x4015000UL});
		public static readonly BitSet _opinstruccion_in_instruccion306 = new BitSet(new ulong[]{0x40000UL});
		public static readonly BitSet _FINL_in_instruccion308 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _etiqueta_in_directiva345 = new BitSet(new ulong[]{0xB0000060UL});
		public static readonly BitSet _tipodirectiva_in_directiva348 = new BitSet(new ulong[]{0x13C0380UL});
		public static readonly BitSet _opdirectiva_in_directiva351 = new BitSet(new ulong[]{0x40000UL});
		public static readonly BitSet _FINL_in_directiva355 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _ID_in_etiqueta447 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _formato_in_opinstruccion465 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _f1_in_formato483 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _f2_in_formato491 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _f3_in_formato499 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _f4_in_formato507 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _indexado_in_formato515 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _F1CODOP_in_f1533 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _F2CODOP_in_f2551 = new BitSet(new ulong[]{0x8000000UL});
		public static readonly BitSet _REG_in_f2553 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _F2CODOP_in_f2561 = new BitSet(new ulong[]{0x8000000UL});
		public static readonly BitSet _REG_in_f2563 = new BitSet(new ulong[]{0x200000000UL});
		public static readonly BitSet _33_in_f2565 = new BitSet(new ulong[]{0x8000000UL});
		public static readonly BitSet _REG_in_f2567 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _F2CODOP_in_f2575 = new BitSet(new ulong[]{0x8000000UL});
		public static readonly BitSet _REG_in_f2577 = new BitSet(new ulong[]{0x200000000UL});
		public static readonly BitSet _33_in_f2579 = new BitSet(new ulong[]{0x1000000UL});
		public static readonly BitSet _NUM_in_f2581 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _simple3_in_f3599 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _indirecto3_in_f3607 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _inmediato3_in_f3615 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _PLUS_in_f4633 = new BitSet(new ulong[]{0x10000UL});
		public static readonly BitSet _f3_in_f4635 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _F34CODOP_in_indexado653 = new BitSet(new ulong[]{0x400000UL});
		public static readonly BitSet _INDICE_in_indexado655 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _F34CODOP_in_simple3673 = new BitSet(new ulong[]{0x201200002UL});
		public static readonly BitSet _33_in_simple3685 = new BitSet(new ulong[]{0x8000000UL});
		public static readonly BitSet _REG_in_simple3687 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _F34CODOP_in_indirecto3708 = new BitSet(new ulong[]{0x10UL});
		public static readonly BitSet _AT_in_indirecto3710 = new BitSet(new ulong[]{0x1200000UL});
		public static readonly BitSet _set_in_indirecto3712 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _F34CODOP_in_inmediato3734 = new BitSet(new ulong[]{0x2000000UL});
		public static readonly BitSet _NUMERAL_in_inmediato3736 = new BitSet(new ulong[]{0x1200000UL});
		public static readonly BitSet _set_in_inmediato3738 = new BitSet(new ulong[]{0x2UL});
	}
	#endregion Follow sets
}
